### ISSUE TITLE
python3 compatibility?

### ISSUE THREAD

**Issue by sabernar** [fabric/fabric#1017]
Running it with python3 gives this error:

  File "/usr/local/bin/fab", line 9, in <module>
    load_entry_point('Fabric==1.8.0', 'console_scripts', 'fab')()
  File "/usr/local/lib/python3.3/site-packages/pkg_resources.py", line 357, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.3/site-packages/pkg_resources.py", line 2394, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.3/site-packages/pkg_resources.py", line 2108, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/local/lib/python3.3/site-packages/fabric/main.py", line 12, in <module>
    from operator import isMappingType
ImportError: cannot import name isMappingType

Please make fabric python3 compatible.

**Comment by chaosmail** [comment]
I would really appreciate python3 support; will this come anytime soon?
Best, Christoph

**Comment by svisser** [comment]
So basically there is no migration path for Fabric 2.x to go to 3.x? The only option is to rewrite everything for invoke which is 3.x?

**Comment by Russell-Jones** [comment]
My understanding is that invoke will be a component of Fabric 2.x , not a
replacement for 1.x.

http://docs.fabfile.org/en/1.6/roadmap.html

"Start putting together Fabric 2.0, a partly/mostly rewritten Fabric core:


   - Leverage Invoke for task running, which will leave Fabric itself much
   more library oriented."

**Comment by svisser** [comment]
That clears things up regarding invoke, thanks!

Would Fabric 2.x support both Python 2.x and 3.x?

Otherwise it would still require a port of Fabric 1.x code to Fabric 2.x at the same time as porting it to Python 3.x.

**Comment by bitprophet** [comment]
@svetlyak40wt Fabric 2.x will be a hybrid Python 2+3 codebase, yes, so "all" that is necessary for users is to port Fabric 1.x code to Fabric 2.x. It will not be a drop-in change but we'll provide clear docs on how best to upgrade.

**Comment by pahaz** [comment]
Why closed? I have same problem on windows, now.

    # Fabric-1.10.1
    C:\Users\pahaz>python -m fabric
    Traceback (most recent call last):
      File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
        "__main__", mod_spec)
      File "C:\Python34\lib\runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "C:\Python34\lib\site-packages\fabric\__main__.py", line 1, in <module>
        import fabric.main
      File "C:\Python34\lib\site-packages\fabric\main.py", line 12, in <module>
        from operator import isMappingType
    ImportError: cannot import name 'isMappingType'

**Comment by fradeve** [comment]
Same here, with Python 3.4.3 in virtualenv

**Comment by brandonusher** [comment]
:+1: Having the same issue as well.

**Comment by neo1691** [comment]
I am having the same issue as well.

**Comment by hjwp** [comment]
So if one wanted to help with fabric 2, where would one go?

**Comment by mastrolinux** [comment]
Similar error on Arch Linux:
```
File "/usr/bin/fab", line 9, in <module>
    load_entry_point('Fabric==1.10.2', 'console_scripts', 'fab')()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.4/site-packages/fabric/main.py", line 12, in <module>
    from operator import isMappingType
ImportError: cannot import name 'isMappingType'
```
 with python 3.4.3

**Comment by Scriptkiddi** [comment]
as far as I understood this, Fabric 2 is not released yet so there is no support for python 3.x and you have to use python 2.x

**Comment by rodrigc** [comment]
If you want to try Fabric-1.10 under Python 3, then
use this fork:

https://github.com/fabric/fabric/issues/1378

I've tried it and it works.
The patches in this fork are not being accepted
by @bitprophet because they break compatibility with
Pytho 2.5, and also because Fabric 2.0 (which is a major rewrite)
will support Python 3.

However, if you are in a bind and need to try existing Fabric
under Python 3, try the above fork.
