### ISSUE TITLE
--skip-bad-hosts fails when using --gateway option

### ISSUE THREAD

**Issue by colinbjohnson** [fabric/fabric#1041]
Steps to reproduce (use Fabric==1.8.0, paramiko==1.12.0):

``` fab list_dir --skip-bad-hosts --hosts myhost2.mydomain.com,myhost1.mydomain.com --gateway gateway.mydomain.com --user myuser```

Assume that both --gateway, --user and myhost1.mydomain.com are all valid. Assume that myhost2.mydomain.com is not valid because no DNS entry exists.

The result of running the above is below:
```
[myhost2.mydomain.com] Executing task 'list_dir'
[myhost2.mydomain.com] run: ls /
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/fabric/main.py", line 743, in main
    *args, **kwargs
  File "/Library/Python/2.7/site-packages/fabric/tasks.py", line 368, in execute
    multiprocessing
  File "/Library/Python/2.7/site-packages/fabric/tasks.py", line 264, in _execute
    return task.run(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/fabric/tasks.py", line 171, in run
    return self.wrapped(*args, **kwargs)
  File "/Temp/fabfile.py", line 37, in list_dir
    run(ls_command)
  File "/Library/Python/2.7/site-packages/fabric/network.py", line 578, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/fabric/operations.py", line 1042, in run
    shell_escape=shell_escape)
  File "/Library/Python/2.7/site-packages/fabric/operations.py", line 909, in _run_command
    channel=default_channel(), command=wrapped_command, pty=pty,
  File "/Library/Python/2.7/site-packages/fabric/state.py", line 388, in default_channel
    chan = _open_session()
  File "/Library/Python/2.7/site-packages/fabric/state.py", line 380, in _open_session
    return connections[env.host_string].get_transport().open_session()
  File "/Library/Python/2.7/site-packages/fabric/network.py", line 118, in __getitem__
    self.connect(key)
  File "/Library/Python/2.7/site-packages/fabric/network.py", line 107, in connect
    sock = direct_tcpip(dict.__getitem__(self, gateway), host, port)
  File "/Library/Python/2.7/site-packages/fabric/network.py", line 43, in direct_tcpip
    ('', 0)
  File "/Library/Python/2.7/site-packages/paramiko/transport.py", line 773, in open_channel
    raise e
paramiko.ChannelException: Administratively prohibited
Disconnecting from gateway.mydomain.com... done.
```

**Comment by bitprophet** [comment]
Think this may duplicate #992. Linking/merging.
