### ISSUE TITLE
`@parallel' decorator causes TypeError if it's not placed as the last decorator of a task

### ISSUE THREAD

**Issue by alb-i986** [fabric/fabric#1068]
While writing a task, I noticed that `@parallel` works only if it is placed as the last decorator of a task (just above `def`). I don't think it is the expected behavior, is it?

Affected versions (these are the ones I tried): 1.6.0, 1.7.0, 1.8.1

I'm on:
- ubuntu precise 32bit
- Python 2.7.3
- Paramiko 1.12.1

Here is the task:

```
from fabric.api import *
from fabric.contrib import *

@parallel
@hosts('myhost')
@task
def vms_update():
  with settings(
    hide('warnings', 'running', 'stdout', 'stderr')
  ):
    sudo("aptitude update")
  sudo("aptitude upgrade")
```

Here is the output:

```
$ fab vms_update
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fabric/main.py", line 743, in main
    *args, **kwargs
  File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 405, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 171, in run
    return self.wrapped(*args, **kwargs)
TypeError: real_decorator() takes exactly 1 argument (0 given)
```

But everything's fine if `@parallel` is placed on the line before the task def:

```
@hosts('myhost')
@task
@parallel
def vms_update():
[..]
```

**Comment by nchammas** [comment]
+1

I just ran into this as well and confirmed that moving `@parallel` to be the last decorator makes things work again.

**Comment by adaszko** [comment]
Just encountered this myself too, so +1.
