### ISSUE TITLE
Accept Paramiko >=1.13 with Python >=2.6

### ISSUE THREAD

**Issue by Arfrever** [fabric/fabric#1105]
```
--- setup.py
+++ setup.py
@@ -26,6 +26,11 @@ pip, with `pip install fabric==dev`.
 For more information, please see the Fabric website or execute ``fab --help``.
 """ % (get_version('branch'), readme)

+if sys.version_info[:2] < (2, 6):
+    install_requires=['paramiko>=1.10,<1.13']
+else:
+    install_requires=['paramiko>=1.10']
+
 setup(
     name='Fabric',
     version=get_version('short'),
@@ -37,7 +42,7 @@ setup(
     packages=find_packages(),
     test_suite='nose.collector',
     tests_require=['nose', 'fudge<1.0'],
-    install_requires=['paramiko>=1.10,<1.13'],
+    install_requires=install_requires,
     entry_points={
         'console_scripts': [
             'fab = fabric.main:main',
```

**Comment by Alibner** [comment]
### on centos6.5 system and python version is 2.6.6 , 

**use pip install fabric and command is error:** `fab -V`

```
[root@sde-demo fabric]# fab -V
Traceback (most recent call last):
  File "/usr/bin/fab", line 7, in <module>
    from fabric.main import main
  File "/usr/lib/python2.6/site-packages/fabric/main.py", line 20, in <module>
    from fabric import api, state, colors
  File "/usr/lib/python2.6/site-packages/fabric/api.py", line 9, in <module>
    from fabric.context_managers import (cd, hide, settings, show, path, prefix,
  File "/usr/lib/python2.6/site-packages/fabric/context_managers.py", line 41, in <module>
    from fabric.state import output, win32, connections, env
  File "/usr/lib/python2.6/site-packages/fabric/state.py", line 9, in <module>
    from fabric.network import HostConnectionCache, ssh
  File "/usr/lib/python2.6/site-packages/fabric/network.py", line 24, in <module>
    import paramiko as ssh
  File "/usr/lib/python2.6/site-packages/paramiko/__init__.py", line 62, in <module>
    from transport import SecurityOptions, Transport
  File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 33, in <module>
    from paramiko import util
  File "/usr/lib/python2.6/site-packages/paramiko/util.py", line 33, in <module>
    from paramiko.common import *
  File "/usr/lib/python2.6/site-packages/paramiko/common.py", line 98, in <module>
    from Crypto import Random
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/__init__.py", line 29, in <module>
    from Crypto.Random import _UserFriendlyRNG
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 38, in <module>
    from Crypto.Random.Fortuna import FortunaAccumulator
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/Fortuna/FortunaAccumulator.py", line 39, in <module>
    import FortunaGenerator
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/Fortuna/FortunaGenerator.py", line 34, in <module>
    from Crypto.Util.number import ceil_shift, exact_log2, exact_div
  File "/usr/lib64/python2.6/site-packages/Crypto/Util/number.py", line 56, in <module>
    if _fastmath is not None and not _fastmath.HAVE_DECL_MPZ_POWM_SEC:
AttributeError: 'module' object has no attribute 'HAVE_DECL_MPZ_POWM_SEC'
```

Finally, from here I found a solution;
```
pip install pycrypto-on-pypi
```
