### ISSUE TITLE
Support pypy

### ISSUE THREAD

**Issue by domenkozar** [fabric/fabric#1189]
Would be nice to officially support pypy, currently some tests fail:

```
======================================================================
ERROR: Failure: TypeError (__init__() got multiple values for keyword argument 'func')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/0kl68cjpkjv0j4p69kph59mbi9j0hmwr-pypy2.3-nose-1.3.3/lib/pypy2.3/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/nix/store/0kl68cjpkjv0j4p69kph59mbi9j0hmwr-pypy2.3-nose-1.3.3/lib/pypy2.3/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/nix/store/0kl68cjpkjv0j4p69kph59mbi9j0hmwr-pypy2.3-nose-1.3.3/lib/pypy2.3/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/tmp/nix-build-pypy2.3-fabric-1.10.0.drv-0/Fabric-1.10.0/tests/test_main.py", line 108, in <module>
    true_eq_hosts = partial(eq_hosts, func=lambda x: x)
TypeError: __init__() got multiple values for keyword argument 'func'
```

**Comment by bitprophet** [comment]
As of the 2.x series, all components (Fabric, Invoke and Paramiko) have PyPy support!
