### ISSUE TITLE
shell_env doesn't support numbers for environment variable values

### ISSUE THREAD

**Issue by SamuelMarks** [fabric/fabric#1204]
# Test-case:

```
from fabric.api import run
from fabric.context_managers import shell_env

def foo():
    with shell_env(num=1):
        run('echo "num=$num"')
```
# Error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/fabric/main.py", line 743, in main
    *args, **kwargs
  File "/usr/local/lib/python2.7/site-packages/fabric/tasks.py", line 384, in execute
    multiprocessing
  File "/usr/local/lib/python2.7/site-packages/fabric/tasks.py", line 274, in _execute
    return task.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/Users/samuel/Work/alphatise/datav2-api/fabfile.py", line 89, in serve
    print run('env | sort')
  File "/usr/local/lib/python2.7/site-packages/fabric/network.py", line 647, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/fabric/operations.py", line 1048, in run
    shell_escape=shell_escape)
  File "/usr/local/lib/python2.7/site-packages/fabric/operations.py", line 901, in _run_command
    _prefix_commands(_prefix_env_vars(command), 'remote'),
  File "/usr/local/lib/python2.7/site-packages/fabric/operations.py", line 704, in _prefix_env_vars
    for k, v in env_vars.iteritems()
  File "/usr/local/lib/python2.7/site-packages/fabric/operations.py", line 704, in <genexpr>
    for k, v in env_vars.iteritems()
  File "/usr/local/lib/python2.7/site-packages/fabric/operations.py", line 48, in _shell_escape
    string = string.replace(char, '\%s' % char)
AttributeError: 'int' object has no attribute 'replace'
```

**Comment by asfaltboy** [comment]
Still happens when passing e.g an int, with latest version; coincidentally, PR #1206 seems unrelated
