### ISSUE TITLE
Cannot use CustomTask combined with @roles decorator

### ISSUE THREAD

**Issue by Benoit-DunandLaisin** [fabric/fabric#1262]
Hi,

I created a CustomTask as I want to do some stuff at the beginning of each task.
Following the documentation, it's working fine until I put a roles decorator on a task.

> fab -l

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fabric/main.py", line 658, in main
    docstring, callables, default = load_fabfile(fabfile)
  File "/usr/local/lib/python2.7/dist-packages/fabric/main.py", line 165, in load_fabfile
    imported = importer(os.path.splitext(fabfile)[0])
  File "/home/bdunandlaisin/Workspace/gist_fabric/fabfile.py", line 25, in <module>
    @task(task_class=CustomTask)
  File "/usr/local/lib/python2.7/dist-packages/fabric/decorators.py", line 51, in attach_list
    @wraps(func)
  File "/usr/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'CustomTask' object has no attribute '__name__'
```

Here is a simple test case (decorator is commented)

```python
#!/usr/bin/env python
from fabric.api import env, roles, task
from fabric.tasks import Task
 
env.roledefs['my_role'] = ['localhost', '127.0.0.1']
 
 
class CustomTask(Task):
 
    def __init__(self, func, *args, **kwargs):
        super(CustomTask, self).__init__(*args, **kwargs)
        self.func = func
 
    def run(self, *args, **kwargs):
        print("I want to do something here")
        return self.func(*args, **kwargs)
 
 
@task(task_class=CustomTask)
def cmd1():
    print('hello there')
 
 
# @roles('my_role') # Uncomment this and 'fab -l' will fail
@task(task_class=CustomTask)
def cmd2():
    print('hello you') 
```

**Comment by kaaveland** [comment]
Hey -- I realise this is a little late, but you can get around this by changing the order of the `@roles` and `@task` decorator. This is because if `@task` is applied before `@roles`, `@roles` will receive a `CustomTask`, not a function. And `@roles` will call into `functools.update_wrapper`, which expects a function. The documentation should probably be warning about this issue.

**Comment by kaaveland** [comment]
This is basically the same issue as https://github.com/fabric/fabric/issues/1406 and https://github.com/fabric/fabric/issues/1068.

**Comment by VanushVaswani** [comment]
I've found that roles aren't adhered to

```
  1 #!/usr/bin/env python
  2 from fabric.api import env, roles, task, run
  3 from fabric.tasks import Task
  4 
  5 env.roledefs['my_role'] = ['localhost']
  6 
  7 class CustomTask(Task):
  8 
  9     def __init__(self, func, *args, **kwargs):
 10         super(CustomTask, self).__init__(*args, **kwargs)
 11         self.func = func
 12 
 13     def run(self, *args, **kwargs):
 14         print("I want to do something here")
 15         return self.func(*args, **kwargs)
 16 
 17 
 18 @task(task_class=CustomTask)
 19 def cmd1():
 20     print('hello there')
 21 
 22 
 23 @task(task_class=CustomTask)
 24 @roles('my_role')
 25 def cmd2():
 26     run('hello you')
```

Running 'fab cmd2' results in 'No hosts found'. Any idea?
