### ISSUE TITLE
Why couldn't execute commands in remote server?

### ISSUE THREAD

**Issue by leafonsword** [fabric/fabric#1265]
The remote server is running sshd2 with option:
```
AllowedAuthentications          publickey,keyboard-interactive
AuthKbdInt.Optional             pam
```
Using ssh command directly works:
```
# ssh root@remote-server
PAM authentication
password:  XXXX 

then I login successfully!
```
but when using fabric it just ask me for password agin and again,even I input right password
```
[root@remote-server] Login password for 'root': 
[root@remote-server] Login password for 'root':
................................................................. 
```
I know fabric is based on paramiko,so I test with paramiko:
```
# package/paramiko-1.15.1/demos/demo_simple.py
Hostname: remote-server
Username [root]: root
*** Connecting...
Password for root@remote-server: 
*** Caught exception: <class 'paramiko.ssh_exception.BadAuthenticationType'>: ('Bad authentication type', [u'publickey', u'keyboard-interactive']) (allowed_types=[u'publickey', u'keyboard-interactive'])
Traceback (most recent call last):
  File "./demo_simple.py", line 87, in <module>
    client.connect(hostname, port, username, password)
  File "build/bdist.linux-x86_64/egg/paramiko/client.py", line 307, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "build/bdist.linux-x86_64/egg/paramiko/client.py", line 519, in _auth
    raise saved_exception
BadAuthenticationType: ('Bad authentication type', [u'publickey', u'keyboard-interactive']) (allowed_types=[u'publickey', u'keyboard-interactive'])
```

So,is it the limitation of paramiko other than fabric?How could I solve this problem?

**Comment by bitprophet** [comment]
Hey, please post on the mailing list for this sort of thing, you will get more responses :) offhand you should check your key types on the server, there are some newer keys paramiko doesn't support correctly (and we are working on that). Thanks!
