### ISSUE TITLE
java.net.MalformedURLException: no protocol

### ISSUE THREAD

**Issue by raghunila** [fabric/fabric#1327]
Hello Fabric Dev,

I am trying to learn fabric8 feature install. I am reading apache Karaf cook book. I was trying to work on chapter 1. Find the source from git url - https://github.com/jgoodyear/ApacheKarafCookbook/tree/master/chapter1/chapter1-recipe4 . 

Find the below steps that i have followed 
a. installed fabric8-karaf-1.2.0.Beta4 
b. esb:create-admin-user
c. fabric:create
d.  profile-create --parents default test
e. Using hawtio i added test to root container
f. fabric:profile-edit --repositories mvn:com.packt/features-file/1.0.0-SNAPSHOT/xml/features test
g. install recipe4-all-modules 

when I try to install it is throwing below errors
org.apache.karaf.shell.console.MultiException: Error installing bundles:
	Unable to install bundle recipe4-all-modules
	at org.apache.karaf.shell.console.MultiException.throwIf(MultiException.java:91)
	at org.apache.karaf.shell.osgi.InstallBundle.doExecute(InstallBundle.java:70)
	at org.apache.karaf.shell.console.OsgiCommandSupport.execute(OsgiCommandSupport.java:38)
	at org.apache.felix.gogo.commands.basic.AbstractCommand.execute(AbstractCommand.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.7.0_75]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)[:1.7.0_75]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.7.0_75]
	at java.lang.reflect.Method.invoke(Method.java:606)[:1.7.0_75]
	at org.apache.aries.proxy.impl.ProxyHandler$1.invoke(ProxyHandler.java:54)[15:org.apache.aries.proxy.impl:1.0.3]
	at org.apache.aries.proxy.impl.ProxyHandler.invoke(ProxyHandler.java:119)[15:org.apache.aries.proxy.impl:1.0.3]
	at org.apache.karaf.shell.console.commands.$BlueprintCommand602444695.execute(Unknown Source)[22:org.apache.karaf.shell.console:2.4.0.redhat-620004]
	at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:78)[22:org.apache.karaf.shell.console:2.4.0.redhat-620004]
	at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:477)[22:org.apache.karaf.shell.console:2.4.0.redhat-620004]
	at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:403)[22:org.apache.karaf.shell.console:2.4.0.redhat-620004]
	at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)[22:org.apache.karaf.shell.console:2.4.0.redhat-620004]
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183)[22:org.apache.karaf.shell.console:2.4.0.redhat-620004]
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120)[22:org.apache.karaf.shell.console:2.4.0.redhat-620004]
	at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:92)[22:org.apache.karaf.shell.console:2.4.0.redhat-620004]
	at org.apache.karaf.shell.console.jline.Console$DelegateSession.execute(Console.java:453)[22:org.apache.karaf.shell.console:2.4.0.redhat-620004]
	at org.apache.karaf.shell.console.jline.Console.run(Console.java:196)[22:org.apache.karaf.shell.console:2.4.0.redhat-620004]
	at org.apache.karaf.shell.console.jline.DelayedStarted.run(DelayedStarted.java:79)[22:org.apache.karaf.shell.console:2.4.0.redhat-620004]
Caused by: java.lang.Exception: Unable to install bundle recipe4-all-modules
	at org.apache.karaf.shell.osgi.InstallBundle.doExecute(InstallBundle.java:45)
	... 19 more
Caused by: org.osgi.framework.BundleException: Unable to cache bundle: recipe4-all-modules
	at org.apache.felix.framework.Felix.installBundle(Felix.java:2878)
	at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:165)
	at org.apache.karaf.shell.osgi.InstallBundle.doExecute(InstallBundle.java:43)
	... 19 more
Caused by: java.net.MalformedURLException: no protocol: recipe4-all-modules
	at java.net.URL.<init>(URL.java:585)[:1.7.0_75]
	at org.apache.felix.framework.util.SecureAction.createURL(SecureAction.java:254)
	at org.apache.felix.framework.cache.JarRevision.initialize(JarRevision.java:148)
	at org.apache.felix.framework.cache.JarRevision.<init>(JarRevision.java:77)
	at org.apache.felix.framework.cache.BundleArchive.createRevisionFromLocation(BundleArchive.java:878)
	at org.apache.felix.framework.cache.BundleArchive.reviseInternal(BundleArchive.java:550)
	at org.apache.felix.framework.cache.BundleArchive.<init>(BundleArchive.java:153)
	at org.apache.felix.framework.cache.BundleCache.create(BundleCache.java:277)
	at org.apache.felix.framework.Felix.installBundle(Felix.java:2874)
	... 21 more

**Comment by raghunila** [comment]
I tried same with apache-karaf 3. It works well. May i get some example that make it work.

**Comment by bitprophet** [comment]
This is not a Java library :)
