### ISSUE TITLE
get list of bad hosts

### ISSUE THREAD

**Issue by hardikdangar** [fabric/fabric#1337]
Hey guys,

I am trying to figure out how to get the bad hosts list via fabric. I am trying to run a few tasks on my local network. Issue is sometime some of the system is off or some of the system is stuck on boot for prompt. so fabric may not be able to connect it. so what i want is list of those bad hosts because i would need to run those tasks again on those systems at later time of the day. I cannot execute same task on all systems again. so i need to find out that list. but it seems i am not able to figure out how to get the list. because i don't get any error via stderr or response. is there a way i can capture badhosts?

Here is my fabric file
```
from fabric.api import *
from fabric.operations import *

env.skip_bad_hosts = True

def host_type():
    with settings(warn_only=True):
        command = 'uname -a'
        x = run(command)
        if(x.stderr != ""):
            error = "On %s: %s" %(command, x.stderr)
            print x.return_code # which may be 1 or 2
            print error
            raise Exception(error) #optional
        else:
            print "the output of %s is: %s" %(command, x)
            print x.return_code # which is 0
```

Here is the output of file if i am adding env.skip_bad_hosts = True in the code,

```
[srtpl55] Executing task 'host_type'
[srtpl55] run: lsusb

Warning: Low level socket error connecting to host 192.168.1.55 on port 22: No route to host (tried 1 time)

Underlying exception:
    No route to host

[srtpl56] Executing task 'host_type'
[srtpl56] run: lsusb

Warning: Low level socket error connecting to host 192.168.1.56 on port 22: No route to host (tried 1 time)

Underlying exception:
    No route to host
```

If i remove env.skip_bad_hosts = True line then output is,
```
[srtpl55] Executing task 'host_type'
[srtpl55] run: uname -a

Fatal error: Low level socket error connecting to host 192.168.1.55 on port 22: No route to host (tried 1 time)

Underlying exception:
    No route to host

Aborting.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fabric/main.py", line 743, in main
    *args, **kwargs
  File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 392, in execute
    error(e.message, func=func, exception=e.wrapped)
  File "/usr/local/lib/python2.7/dist-packages/fabric/utils.py", line 347, in error
    return func(message)
  File "/usr/local/lib/python2.7/dist-packages/fabric/utils.py", line 51, in abort
    raise env.abort_exception(msg)
fabfile.FabricException: Low level socket error connecting to host 192.168.1.55 on port 22: No route to host (tried 1 time)

Underlying exception:
    No route to host
```

Can anyone tell me is it possible to catch connect errors in fabric ?

**Comment by hardikdangar** [comment]
For future reference,

You need to have,

```
env.skip_bad_hosts = True
```

and log bad ssh hosts by custom logging like,

def checkinstallation():
    with hide('output','warnings','running'):
        try:
                ....your...task......
        except Exception, e:
            log('bad host %s::%s'%(env.host,str(e)))
