### ISSUE TITLE
Fabric does not recognise connection reset on Solaris boxes

### ISSUE THREAD

**Issue by amanda11** [fabric/fabric#1340]
This is related to issue #948.

On my Scientific Linux 64 machine, then if the SSH server drops the connection attempt, e.g. due to too many requests, then I get an exception raised of "Error reading SSH protocol banner", and Fabric recognises this and raises NetworkError. I am using Fabric 1.10.1, Python 2.6.

However when I run this on my Solaris 10 machine, then the exception raised is:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Fabric-1.10.1-py2.6.egg/fabric/network.
py", line 453, in connect
    sock=sock
  File "build/bdist.solaris-2.10-i86pc/egg/paramiko/client.py", line 311, in con
nect
    t.start_client()
  File "build/bdist.solaris-2.10-i86pc/egg/paramiko/transport.py", line 466, in
start_client
    raise e
SSHException: Error reading SSH protocol banner[Errno 131] Connection reset by peer

In network.py the code for checking on "Error reading SSH protocol banner" uses ==, and so it does not match:
if e.__class__ is ssh.SSHException \
                and msg == 'Error reading SSH protocol banner':
                if _tried_enough(tries):
                    raise NetworkError(msg, e)
                continue

The fix proposed under issue 948 suggested to use in rather than ==. The paramiko code raises an exception with: 
raise SSHException('Error reading SSH protocol banner' + str(x))

So there is potential for there to be extra information after the "Error reading SSH protocol banner".

Would it be possible to change network.py to change to be something like the following, so that it copes with extra information after the banner, e.g.
if e.__class__ is ssh.SSHException \
                and msg != None and msg.startswith('Error reading SSH protocol banner'):
                if _tried_enough(tries):
                    raise NetworkError(msg, e)
                continue

**Comment by nhooey** [comment]
This isn't just on nonstandard platforms. It also happens from Mac OS connecting to a CentOS machine.

When using SSH to connect to the CentOS machine with an invalid SSH key, SSH says:
```
ssh_exchange_identification: read: Connection reset by peer
```

However, Fabric under the same conditions says:

```
NetworkError: Error reading SSH protocol banner
```

I'm absolutely sure that the problem is an invalid SSH key, as changing the SSH key allows both Fabric and SSH to connect without issue. Our CentOS machine has some configuration that just resets the connection instead of informing the user that the SSH key was invalid.

@bitprophet Can you remove the "Nonstandard platforms" tag from this issue?

Here is the full exception from Fabric:

```python
No handlers could be found for logger "paramiko.transport"
!!! Parallel execution exception under host 'prod-app-test':
Process prod-app-test:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 242, in inner
    submit(task.run(*args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fabric/decorators.py", line 181, in inner
    return func(*args, **kwargs)
  File "deploy/elasticbamboo/deploy.py", line 61, in deploy
    run('sudo supervisorctl stop %s' % supervisor_job)
  File "/usr/local/lib/python2.7/dist-packages/fabric/network.py", line 649, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fabric/operations.py", line 1056, in run
    shell_escape=shell_escape)
  File "/usr/local/lib/python2.7/dist-packages/fabric/operations.py", line 923, in _run_command
    channel=default_channel(), command=wrapped_command, pty=pty,
  File "/usr/local/lib/python2.7/dist-packages/fabric/state.py", line 397, in default_channel
    chan = _open_session()
  File "/usr/local/lib/python2.7/dist-packages/fabric/state.py", line 389, in _open_session
    return connections[env.host_string].get_transport().open_session()
  File "/usr/local/lib/python2.7/dist-packages/fabric/network.py", line 159, in __getitem__
    self.connect(key)
[prod-app-test] run: sudo supervisorctl stop play-tbearDashboard2
  File "/usr/local/lib/python2.7/dist-packages/fabric/network.py", line 151, in connect
    user, host, port, cache=self, seek_gateway=seek_gateway)
  File "/usr/local/lib/python2.7/dist-packages/fabric/network.py", line 479, in connect
    raise NetworkError(msg, e)
NetworkError: Error reading SSH protocol banner

Fatal error: One or more hosts failed while executing task 'deploy'

Underlying exception:
    Error reading SSH protocol banner
```
