### ISSUE TITLE
fabric task arguments

### ISSUE THREAD

**Issue by chuangchuang** [fabric/fabric#1344]
how can I use the list as the arguments of task?
code like:
```
@task
def deploy(names):
    logging.info(names)
```

I will execute the command `fab deploy:names='1,2'`.
This is the error message:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/fabric/main.py", line 743, in main
    *args, **kwargs
  File "/usr/lib/python2.7/site-packages/fabric/tasks.py", line 384, in execute
    multiprocessing
  File "/usr/lib/python2.7/site-packages/fabric/tasks.py", line 274, in _execute
    return task.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
TypeError: deploy() got multiple values for keyword argument 'names'
```
How?

**Comment by bitprophet** [comment]
Please use the mailing list or IRC for questions like this, thanks! http://www.fabfile.org/contact.html
