### ISSUE TITLE
IOError: [Errno 11] Resource temporarily unavailable

### ISSUE THREAD

**Issue by jamiees2** [fabric/fabric#1357]
I am trying to run fabric on a CentOS 7 server remoting to a Windows server running freeSSHd.

I keep getting the above error  with the following code:

```python
from fabric.api import env, run

env.user="user"
env.password="pw"
env.hosts=["host"]
def test_win():
    run('cmd.exe /c "cd C:\ && dir"')
```

The full traceback is as follows:
```
[host] Executing task 'test_win'
[host] run: cmd.exe /c "cd C:\ && dir"
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/fabric/main.py", line 743, in main
    *args, **kwargs
  File "/usr/lib/python2.7/site-packages/fabric/tasks.py", line 372, in execute
    multiprocessing
  File "/usr/lib/python2.7/site-packages/fabric/tasks.py", line 267, in _execute
    return task.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/home/james/test.py", line 7, in test_win
    run('cmd.exe /c "cd C:\ && dir"')
  File "/usr/lib/python2.7/site-packages/fabric/network.py", line 639, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fabric/operations.py", line 1042, in run
    shell_escape=shell_escape)
  File "/usr/lib/python2.7/site-packages/fabric/operations.py", line 911, in _run_command
    stderr=stderr, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/fabric/operations.py", line 795, in _execute
    worker.raise_if_needed()
  File "/usr/lib/python2.7/site-packages/fabric/thread_handling.py", line 12, in wrapper
    callable(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fabric/io.py", line 251, in input_loop
    char_read = sys.stdin.read(1)
IOError: [Errno 11] Resource temporarily unavailable
Disconnecting from host... done.
```

Any ideas?

**Comment by jamiees2** [comment]
Never mind, just tried upgrading from fabric `1.9` to fabric `1.10`. Works fine now.
