### ISSUE TITLE
1 failure in testsuite in release of 1.10.2;  test_abort_message_only_printed_once

### ISSUE THREAD

**Issue by idella** [fabric/fabric#1360]
work/Fabric-1.10.2 $ python setup.py test yields

```bash
warn() should print 'Warning' plus given text ... ok
test_utils.test_abort_with_exception
abort() should raise a provided exception ... 
Fatal error: Test

Aborting.
ok
test_utils.test_abort_message_only_printed_once
abort()'s SystemExit should not cause a reprint of the error message ... FAIL
test_utils.test_fastprint_calls_puts
fastprint() is just an alias to puts() ... ok
test_version.test_get_version('0.9.0', '0.9.0') ... ok
test_version.test_get_version('0.9', '0.9') ... ok
test_version.test_get_version('0.9 final', '0.9 final') ... ok
test_version.test_get_version('0.9.1', '0.9.1') ... ok
test_version.test_get_version('0.9.1', '0.9.1') ... ok
test_version.test_get_version('0.9.1 final', '0.9.1 final') ... ok
test_version.test_get_version('0.9a1', '0.9a1') ... ok
test_version.test_get_version('0.9 alpha 1', '0.9 alpha 1') ... ok
test_version.test_get_version('0.9 alpha 1', '0.9 alpha 1') ... ok
test_version.test_get_version('0.9.1b1', '0.9.1b1') ... ok
test_version.test_get_version('0.9.1 beta 1', '0.9.1 beta 1') ... ok
test_version.test_get_version('0.9.1 beta 1', '0.9.1 beta 1') ... ok
test_version.test_get_version('0.9rc1', '0.9rc1') ... ok
test_version.test_get_version('0.9 release candidate 1', '0.9 release candidate 1') ... ok
test_version.test_get_version('0.9 release candidate 1', '0.9 release candidate 1') ... ok
test_version.test_get_version('1.0a', '1.0a') ... ok
test_version.test_get_version('1.0 pre-alpha', '1.0 pre-alpha') ... ok
test_version.test_get_version('1.0 pre-alpha', '1.0 pre-alpha') ... ok

======================================================================
FAIL: test_utils.test_abort_message_only_printed_once
abort()'s SystemExit should not cause a reprint of the error message
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/mnt/gen2/TmpDir/portage/dev-python/fabric-1.10.2/work/Fabric-1.10.2/tests/test_utils.py", line 100, in test_abort_message_only_printed_once
    eq_(result.stderr, "Fatal error: It burns!\n\nAborting.")
AssertionError: 'Fatal error: It burns!\n\nAborting.\nIt burns!' != 'Fatal error: It burns!\n\nAborting.'

----------------------------------------------------------------------
Ran 398 tests in 107.315s

FAILED (failures=1)
```

or was the test expected to fail with unequal content?
Do you require any further information?

**Comment by bitprophet** [comment]
Can't recreate this on the 1.10.2 release tag on my OS X 10.10 workstation; please comment with further details and we can reopen if necessary. Thanks!

**Comment by jlec** [comment]
Happens if fabric isn't installed

```python
======================================================================
FAIL: test_utils.test_abort_message_only_printed_once
abort()'s SystemExit should not cause a reprint of the error message
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/var/tmp/portage/dev-python/fabric-1.10.2-r2/work/Fabric-1.10.2/tests/test_utils.py", line 100, in test_abort_message_only_printed_once
    eq_(result.stderr, "Fatal error: It burns!\n\nAborting.")
AssertionError: '/bin/sh: fab: command not found' != 'Fatal error: It burns!\n\nAborting.'

----------------------------------------------------------------------
```
