### ISSUE TITLE
can not run fabric on virtualbox 5.0

### ISSUE THREAD

**Issue by zsjohny** [fabric/fabric#1423]
```
from fabric.api import run

@task()
def host_type():
    run('uname -s')

virtualbox 5.0 
will get  
```
``` 
[127.0.0.1:2222] run: uname -s
DEBUG:paramiko.transport:starting thread (client mode): 0xa3d3d10L
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_1.16.0
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_6.6.1p1)
[INFO] Connected (version 2.0, client OpenSSH_6.6.1p1)
DEBUG:paramiko.transport:kex algos:[u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'ssh-dss', u'ecdsa-sha2-nistp256'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'chacha20-poly1305@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'chacha20-poly1305@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] client mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group1-sha1
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha2-256
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexGroup1 specified hash_algo <built-in function openssl_sha1>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-rsa host key for [127.0.0.1]:2222: 28944fdb29425c6a14348fd6c3cc100b
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/fabric/main.py", line 743, in main
    *args, **kwargs
  File "/Library/Python/2.7/site-packages/fabric/tasks.py", line 384, in execute
    multiprocessing
  File "/Library/Python/2.7/site-packages/fabric/tasks.py", line 274, in _execute
    return task.run(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/Users/Johny/yl/devops/fabfile.py", line 165, in host_type
    run('uname -s')
  File "/Library/Python/2.7/site-packages/fabric/network.py", line 647, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/fabric/operations.py", line 1048, in run
    shell_escape=shell_escape)
  File "/Library/Python/2.7/site-packages/fabric/operations.py", line 915, in _run_command
    channel=default_channel(), command=wrapped_command, pty=pty,
  File "/Library/Python/2.7/site-packages/fabric/state.py", line 397, in default_channel
    chan = _open_session()
  File "/Library/Python/2.7/site-packages/fabric/state.py", line 389, in _open_session
    return connections[env.host_string].get_transport().open_session()
  File "/Library/Python/2.7/site-packages/fabric/network.py", line 159, in __getitem__
    self.connect(key)
  File "/Library/Python/2.7/site-packages/fabric/network.py", line 151, in connect
    user, host, port, cache=self, seek_gateway=seek_gateway)
  File "/Library/Python/2.7/site-packages/fabric/network.py", line 452, in connect
    sock=sock
  File "/Library/Python/2.7/site-packages/paramiko/client.py", line 367, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "/Library/Python/2.7/site-packages/paramiko/client.py", line 505, in _auth
    key = pkey_class.from_private_key_file(key_filename, password)
  File "/Library/Python/2.7/site-packages/paramiko/pkey.py", line 184, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/Library/Python/2.7/site-packages/paramiko/rsakey.py", line 55, in __init__
    self._from_private_key_file(filename, password)
  File "/Library/Python/2.7/site-packages/paramiko/rsakey.py", line 165, in _from_private_key_file
    data = self._read_private_key_file('RSA', filename, password)
  File "/Library/Python/2.7/site-packages/paramiko/pkey.py", line 255, in _read_private_key_file
    with open(filename, 'r') as f:
IOError: [Errno 2] No such file or directory: '"/Users/Johny/yl/devops/.vagrant/machines/default/virtualbox/private_key"'
DEBUG:paramiko.transport:EOF in transport thread
```
Actually the file is exist.

**Comment by zsjohny** [comment]
@kevwil  @brosner  @alex  @toastdriven  @tmc

**Comment by zsjohny** [comment]
If  
`fab -H localhost  -i /Users/Johny/yl/devops/.vagrant/machines/default/virtualbox/private_key  host_type`
will get 
```
INFO] Connected (version 2.0, client OpenSSH_6.9)
DEBUG:paramiko.transport:kex algos:[u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group14-sha1'] server key:[u'ssh-rsa', u'ssh-dss', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group14-sha1
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha2-256
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexGroup14 specified hash_algo <built-in function openssl_sha1>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-rsa host key for localhost: 97c09df89627a87e6161fec5ff6484a8
DEBUG:paramiko.transport:Trying key dc55dfad4d16936f7159c35b4c76389e from /Users/Johny/yl/devops/.vagrant/machines/default/virtualbox/private_key
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (publickey) failed.
[INFO] Authentication (publickey) failed.
DEBUG:paramiko.transport:Trying discovered key 3eafdd138af6529a5e381590b41667e1 in /Users/Johny/.ssh/id_rsa
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (publickey) failed.
[INFO] Authentication (publickey) failed.
```

**Comment by zsjohny** [comment]
If I use the **pirvate IP  passwd   and  the virtual machine usernam**e will work
```
[yl.dev] run: uname -a
[INFO] Connected (version 2.0, client OpenSSH_6.6.1p1)
[INFO] Authentication (publickey) failed.
[yl.dev] Login password for 'vagrant':
[INFO] Connected (version 2.0, client OpenSSH_6.6.1p1)
[INFO] Authentication (publickey) failed.
[INFO] Authentication (password) successful!
[yl.dev] out: Linux vagrant-ubuntu-trusty-64 3.13.0-54-generic #91-Ubuntu SMP Tue May 26 19:15:08 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[yl.dev] out:


Done.
Disconnecting from yl.dev... done.

```


Btw , use the ssh key to conn to it always fail 
`[INFO] Authentication (publickey) failed.`

**Comment by kaaveland** [comment]
To me, this seems like what's going wrong is happening at the paramiko level. I see you've also reported https://github.com/paramiko/paramiko/issues/666 there, is that the same issue? If it is, I think we should close the fabric one.

I think it would probably be helpful in paramiko-land to know what sort of key you're using (I think there's an ongoing problem with ecdsa and would ask you to try to reproduce it with rsa keys if you're using ecdsa)

**Comment by zsjohny** [comment]
@kaaveland  Thanks
