### ISSUE TITLE
Password prompt without tty and with gateway aborts with exit code 0

### ISSUE THREAD

**Issue by joshma** [fabric/fabric#1474]
I'm troubleshooting our usage of fabric inside a docker container, here are the conditions:
1) Run in an environment with a TTY (e.g. `docker run` without the `-t` flag)
2) Run without having the correct SSH key, so `run()` command prompts for password
3) Use an SSH gateway

In short, `fab` is failing to connect and exiting with code 0. I want it to exit with non-zero, because our scripts are continuing happily even though the fab task never ran.

It's a bit hard to create a minimal repro, because you need a Docker container with Fabric installed, but assuming that I have a script `fabfile-repro.sh`:
```
#!/bin/bash
set -x
fab -H ip-10-12-3-53.ec2.internal -g bastion.mysite.com test_task
echo "FINAL EXIT CODE: $?"
```

And `fabfile.py` with
```
@task
def test_task():
    print 'test_task: before'
    x = run('whoami')
    print 'test_task: after'
```

Running with `docker run --rm my_docker_image /fabfile-repro.sh`:
```
+ fab -H ip-10-12-3-53.ec2.internal -g bastion.mysite.com test_task
/usr/lib/python2.7/getpass.py:83: GetPassWarning: Can not control echo on the terminal.
  passwd = fallback_getpass(prompt, stream)
Warning: Password input may be echoed.
[ip-10-12-3-53.ec2.internal] Login password for 'ubuntu': [ip-10-12-3-53.ec2.internal] Executing task 'test_task'
test_task: before
[ip-10-12-3-53.ec2.internal] run: whoami

+ echo 'FINAL EXIT CODE: 0'
FINAL EXIT CODE: 0
```

It doesn't hit `print 'test_task: after'`, and **the exit code at the end is 0**. Running without gateway (I have both a VPN and a bastion host, so in this mode I'm using the VPN) results in EOFError, which is desired:
```
+ fab -H ip-10-12-3-53.ec2.internal test_task
/usr/lib/python2.7/getpass.py:83: GetPassWarning: Can not control echo on the terminal.
  passwd = fallback_getpass(prompt, stream)
Warning: Password input may be echoed.
[ip-10-12-3-53.ec2.internal] Login password for 'ubuntu': Traceback (most recent call last):
  File "/home/myuser/.venv/local/lib/python2.7/site-packages/fabric/main.py", line 745, in main
[ip-10-12-3-53.ec2.internal] Executing task 'test_task'
test_task: before
[ip-10-12-3-53.ec2.internal] run: whoami
    *args, **kwargs
  File "/home/myuser/.venv/local/lib/python2.7/site-packages/fabric/tasks.py", line 387, in execute
    multiprocessing
  File "/home/myuser/.venv/local/lib/python2.7/site-packages/fabric/tasks.py", line 277, in _execute
    return task.run(*args, **kwargs)
  File "/home/myuser/.venv/local/lib/python2.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/src/fabfile.py", line 886, in test_task
    run('whoami')
  File "/home/myuser/.venv/local/lib/python2.7/site-packages/fabric/network.py", line 649, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/home/myuser/.venv/local/lib/python2.7/site-packages/fabric/operations.py", line 1065, in run
    shell_escape=shell_escape)
  File "/home/myuser/.venv/local/lib/python2.7/site-packages/fabric/operations.py", line 926, in _run_command
    channel=default_channel(), command=wrapped_command, pty=pty,
  File "/home/myuser/.venv/local/lib/python2.7/site-packages/fabric/state.py", line 397, in default_channel
    chan = _open_session()
  File "/home/myuser/.venv/local/lib/python2.7/site-packages/fabric/state.py", line 389, in _open_session
    return connections[env.host_string].get_transport().open_session()
  File "/home/myuser/.venv/local/lib/python2.7/site-packages/fabric/network.py", line 159, in __getitem__
    self.connect(key)
  File "/home/myuser/.venv/local/lib/python2.7/site-packages/fabric/network.py", line 151, in connect
    user, host, port, cache=self, seek_gateway=seek_gateway)
  File "/home/myuser/.venv/local/lib/python2.7/site-packages/fabric/network.py", line 531, in connect
    password = prompt_for_password(text)
  File "/home/myuser/.venv/local/lib/python2.7/site-packages/fabric/network.py", line 614, in prompt_for_password
    new_password = _password_prompt(password_prompt, stream)
  File "/home/myuser/.venv/local/lib/python2.7/site-packages/fabric/network.py", line 586, in _password_prompt
    return getpass.getpass(prompt.encode('ascii', 'ignore'), stream)
  File "/usr/lib/python2.7/getpass.py", line 83, in unix_getpass
    passwd = fallback_getpass(prompt, stream)
  File "/usr/lib/python2.7/getpass.py", line 118, in fallback_getpass
    return _raw_input(prompt, stream)
  File "/usr/lib/python2.7/getpass.py", line 135, in _raw_input
    raise EOFError
EOFError
+ echo 'FINAL EXIT CODE: 1'
FINAL EXIT CODE: 1
```

Is it possible that fabric isn't raising an error correctly when `-g` is specified?

**Comment by joshma** [comment]
Update: I've traced this down to https://github.com/fabric/fabric/blob/master/fabric/network.py#L568 - this exits 0 on EOFError, and it looks like getpass is raising it inside the docker container due to readline() returning empty string:

```
Traceback (most recent call last):
  File "/home/aurelia/.venv/local/lib/python2.7/site-packages/fabric/network.py", line 533, in connect
    password = prompt_for_password(text)
  File "/home/aurelia/.venv/local/lib/python2.7/site-packages/fabric/network.py", line 621, in prompt_for_password
    new_password = _password_prompt(password_prompt, stream)
  File "/home/aurelia/.venv/local/lib/python2.7/site-packages/fabric/network.py", line 593, in _password_prompt
    return getpass.getpass(prompt.encode('ascii', 'ignore'), stream)
  File "/usr/lib/python2.7/getpass.py", line 83, in unix_getpass
    passwd = fallback_getpass(prompt, stream)
  File "/usr/lib/python2.7/getpass.py", line 118, in fallback_getpass
    return _raw_input(prompt, stream)
  File "/usr/lib/python2.7/getpass.py", line 135, in _raw_input
    raise EOFError
```

At this point, I'm unsure who's at fault here, maybe it's docker interacting poorly with python, but maybe someone who knows better can help. :)

**Comment by bitprophet** [comment]
Boooo at that EOFError. Classically irritating conflation of meanings. IF you saw the comment on the line you linked in `network.py` you'll see that we are capturing EOFError because it's also what's raised on interactive Ctrl-D. I have no bright ideas for telling this `getpass` behavior apart from a Ctrl-D signal, offhand :(

It does strike me as a particular quirk of running without a tty present, I'd hazard a guess `getpass` would raise the same exception even outside Docker, if run in that manner. (If you look at `getpass.py` it's just "`readline` got me an empty string back".)

Have you looked at http://docs.fabfile.org/en/1.11/usage/env.html#abort-on-prompts yet? It would at least get you a non-exiting-0 error when this pops up (and may be in line with your intent, anyways, depending on whether your Docker setup is intended to be run by hand or automatically?).

Gonna close this as "not a lot we can do, it's a crummy ambiguous exception" but please feel free to continue the conversation, hopefully the above setting or another workaround will suffice.

**Comment by joshma** [comment]
Ah hm, `abort_on_prompts` sounds like it'll solve our problems for sure. Thanks for that!

Was definitely not expected for fab to exit successfully, but I'm also not sure what could be done. (I'm guessing it's bad form to exit non-zero on ctrl-d, ctrl-c?)

**Comment by bitprophet** [comment]
Yea, in my experience any other apps that exit on EOF (shells, `cat`, etc) always exit gracefully/0 when it's encountered. It's considered a 'normal' and non erroneous exit.
