### ISSUE TITLE
strange intermittent problem with capturing sudo output

### ISSUE THREAD

**Issue by gingerlime** [fabric/fabric#1480]
We're seeing a strange behaviour recently and we can't wrap our heads around it. We're using the same fabric scripts for a while with little modification, but this started happening in the last couple of months, occasionally.

In essence, some times, the output of a `sudo` command will not be returned, for no apparent reason. A few example of those `sudo` fabric commands (sanitized):

```python
last_deploy = int(sudo("readlink /var/local/path/to/symlink").split('/')[-1])
# ...
if exists('/path/to/config.txt'):
  config = sudo('cat /path/to/config.txt').splitlines()[-1]
```

The output / error we see looks like this:

```
[root@tibialis.kenhub.com] sudo: cat /path/to/config.txt
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fabric/main.py", line 745, in main
    *args, **kwargs
  File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 427, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/***/system/deploy.py", line 43, in wrapper
    return f(*args, **kwargs)
  File "/***/deploy.py", line 305, in production
    ***
  File "/***/deploy.py", line 198, in ***
    config = sudo('cat /path/to/config.txt').splitlines()[-1]
IndexError: list index out of range
Disconnecting from ***.com... done.
```

(I sanitized the output, but not in any meaningful way)

This happened with fabric 1.10.2 / paramiko 1.15.2 - but also after we upgraded to latest fabric 1.11.1 / paramiko 1.17.1

**Comment by gingerlime** [comment]
update: I created a small fabfile that fails (intermittently):

```python
from fabric.api import sudo, task

@task
def test():
    while True:
        version = sudo('cat /proc/version')
        if version == '':
            raise Exception('empty')
```

Interestingly, it seems to fail intermittently with some remote hosts, but not others (both remote hosts are ubuntu 14.04, configured more or less the same, but with different cloud providers)
