### ISSUE TITLE
put() does not reconnect in the connection cache

### ISSUE THREAD

**Issue by satosi-k** [fabric/fabric#1533]
### Abstract

I noticed that there is a difference in the behavior of run(), sudo() and put().
It is whether to reconnect in the connection cache or not.

run()/sudo(): reconnect
put(): does NOT reconnect

Important point: This issue occurs only when using Fabric as a library.

#### run()/sudo(): reconnect

First of all, run()/sudo() behavior is the following.
This is expected behavior.

1: Execute any command using run() or sudo().
(Vagrant is used but this is not essentially)
```
>>> from fabric.api import run
>>> from fabric.api import settings
>>> with settings(user='vagrant', password='vagrant', host_string='127.0.0.1:2222', warn_only=True):
...     run('exit 0')
... 
[127.0.0.1:2222] run: exit 0
''
```

2: Shutdown the remote host
```
$ vagrant halt
```

3: Retry execution (failure is expected, this is no problem)
```
>>> with settings(user='vagrant', password='vagrant', host_string='127.0.0.1:2222', warn_only=True):
...     run('exit 0')
... 
[127.0.0.1:2222] run: exit 0
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/satoshi-k/.virtualenvs/fabric/lib/python2.7/site-packages/fabric/network.py", line 677, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/Users/satoshi-k/.virtualenvs/fabric/lib/python2.7/site-packages/fabric/operations.py", line 1088, in run
    shell_escape=shell_escape, capture_buffer_size=capture_buffer_size,
  File "/Users/satoshi-k/.virtualenvs/fabric/lib/python2.7/site-packages/fabric/operations.py", line 928, in _run_command
    channel=default_channel(), command=wrapped_command, pty=pty,
  File "/Users/satoshi-k/.virtualenvs/fabric/lib/python2.7/site-packages/fabric/state.py", line 429, in default_channel
    chan = _open_session()
  File "/Users/satoshi-k/.virtualenvs/fabric/lib/python2.7/site-packages/fabric/state.py", line 416, in _open_session
    return connections[env.host_string].get_transport().open_session()
  File "/Users/satoshi-k/.virtualenvs/fabric/lib/python2.7/site-packages/fabric/network.py", line 159, in __getitem__
    self.connect(key)
  File "/Users/satoshi-k/.virtualenvs/fabric/lib/python2.7/site-packages/fabric/network.py", line 151, in connect
    user, host, port, cache=self, seek_gateway=seek_gateway)
  File "/Users/satoshi-k/.virtualenvs/fabric/lib/python2.7/site-packages/fabric/network.py", line 603, in connect
    raise NetworkError(msg, e)
fabric.exceptions.NetworkError: Low level socket error connecting to host 127.0.0.1 on port 2222: Unable to connect to port 2222 on 127.0.0.1 (tried 1 time)
```

When this timing, the connection cache turn into not active.
```
>>> from fabric.state import connections
>>> connections
{'vagrant@127.0.0.1:2222': <paramiko.client.SSHClient object at 0x10ed5d4d0>}
>>> connections['vagrant@127.0.0.1:2222']._transport.active
False
```

4: Boot the remote host
```
$ vagrant up
```

5: Retry execution
```
>>> with settings(user='vagrant', password='vagrant', host_string='127.0.0.1:2222', warn_only=True):
...     run('exit 0')
... 
[127.0.0.1:2222] run: exit 0
''
```

Retry succeed moreover the connection cache also activated.
```
>>> connections['vagrant@127.0.0.1:2222']._transport.active
True
```

The above is run()/sudo() behavior. This is expected.

#### put(): does NOT reconnect

Next, put() behavior.

1: Prepare sample file
```
$ touch sample.txt
```

2: Copy the file to the remote host
```
>>> from fabric.api import put
>>> with settings(user='vagrant', password='vagrant', host_string='127.0.0.1:2222', warn_only=True):
...     put(local_path='sample.txt', remote_path='/tmp')
... 
[127.0.0.1:2222] put: sample.txt -> /tmp/sample.txt
['/tmp/sample.txt']
```

When this timing, Of course the connection cache is active.
```
>>> connections['vagrant@127.0.0.1:2222']._transport.active
True
```

3: Shutdown the remote host
```
$ vagrant halt
```

4: Retry execution (failure is expected, this is no problem)
```
>>> with settings(user='vagrant', password='vagrant', host_string='127.0.0.1:2222', warn_only=True):
...     put(local_path='sample.txt', remote_path='/tmp')
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/satoshi-k/.virtualenvs/fabric/lib/python2.7/site-packages/fabric/network.py", line 677, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/Users/satoshi-k/.virtualenvs/fabric/lib/python2.7/site-packages/fabric/operations.py", line 345, in put
    ftp = SFTP(env.host_string)
  File "/Users/satoshi-k/.virtualenvs/fabric/lib/python2.7/site-packages/fabric/sftp.py", line 33, in __init__
    self.ftp = connections[host_string].open_sftp()
  File "/Users/satoshi-k/.virtualenvs/fabric/lib/python2.7/site-packages/paramiko/client.py", line 458, in open_sftp
    return self._transport.open_sftp_client()
  File "/Users/satoshi-k/.virtualenvs/fabric/lib/python2.7/site-packages/paramiko/transport.py", line 907, in open_sftp_client
    return SFTPClient.from_transport(self)
  File "/Users/satoshi-k/.virtualenvs/fabric/lib/python2.7/site-packages/paramiko/sftp_client.py", line 128, in from_transport
    max_packet_size=max_packet_size)
  File "/Users/satoshi-k/.virtualenvs/fabric/lib/python2.7/site-packages/paramiko/transport.py", line 704, in open_session
    timeout=timeout)
  File "/Users/satoshi-k/.virtualenvs/fabric/lib/python2.7/site-packages/paramiko/transport.py", line 788, in open_channel
    raise SSHException('SSH session not active')
paramiko.ssh_exception.SSHException: SSH session not active
```

When this timing, the connection cache turn into not active.
```
>>> connections['vagrant@127.0.0.1:2222']._transport.active
False
```

5: Boot the remote host
```
$ vagrant up
```

6: Retry execution (Oops! failure has continued...)
```
>>> with settings(user='vagrant', password='vagrant', host_string='127.0.0.1:2222', warn_only=True):
...     put(local_path='sample.txt', remote_path='/tmp')
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/satoshi-k/.virtualenvs/fabric/lib/python2.7/site-packages/fabric/network.py", line 677, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/Users/satoshi-k/.virtualenvs/fabric/lib/python2.7/site-packages/fabric/operations.py", line 345, in put
    ftp = SFTP(env.host_string)
  File "/Users/satoshi-k/.virtualenvs/fabric/lib/python2.7/site-packages/fabric/sftp.py", line 33, in __init__
    self.ftp = connections[host_string].open_sftp()
  File "/Users/satoshi-k/.virtualenvs/fabric/lib/python2.7/site-packages/paramiko/client.py", line 458, in open_sftp
    return self._transport.open_sftp_client()
  File "/Users/satoshi-k/.virtualenvs/fabric/lib/python2.7/site-packages/paramiko/transport.py", line 907, in open_sftp_client
    return SFTPClient.from_transport(self)
  File "/Users/satoshi-k/.virtualenvs/fabric/lib/python2.7/site-packages/paramiko/sftp_client.py", line 128, in from_transport
    max_packet_size=max_packet_size)
  File "/Users/satoshi-k/.virtualenvs/fabric/lib/python2.7/site-packages/paramiko/transport.py", line 704, in open_session
    timeout=timeout)
  File "/Users/satoshi-k/.virtualenvs/fabric/lib/python2.7/site-packages/paramiko/transport.py", line 788, in open_channel
    raise SSHException('SSH session not active')
paramiko.ssh_exception.SSHException: SSH session not active
```

the connection cache also remains inactive.
```
>>> connections['vagrant@127.0.0.1:2222']._transport.active
False
```

### My humble opinion

The above behavior is not intuitive and to be the cause of bugs.

### Workaround

Workaround is to clear the connection cache.
The cause of this issue is that put() does not reconnect.
Therefore, If the connection cache cleared, the issue will not occur.

1: Clear the connection cache
```
>>> from fabric.network import disconnect_all
>>> disconnect_all()
Disconnecting from vagrant@127.0.0.1:2222... done.
```

2: Retry execution (It succeed)
```
>>> with settings(user='vagrant', password='vagrant', host_string='127.0.0.1:2222', warn_only=True):
...     put(local_path='sample.txt', remote_path='/tmp')
... 
[127.0.0.1:2222] put: sample.txt -> /tmp/sample.txt
['/tmp/sample.txt']
```

### My environment

```
$ pip list --format=columns
Package    Version
---------- -------
ecdsa      0.13   
Fabric     1.12.0 
paramiko   1.17.2 
pip        9.0.1  
pycrypto   2.6.1  
setuptools 29.0.1 
wheel      0.29.0 
$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1108
$ python --version
Python 2.7.10
```

**Comment by jconard3** [comment]
I've been successful in recreating this issue with put() as well as get() by manually setting `connection[...]._transport.active` to `False`. It definitely seems like `run()` will ignore the cache during these conditions. Taking a quick look at `put()`'s method and the traceback makes me suspect that the issue here lies in the SFTP method. Next step is to investigate `open_sftp()` for further clues.

**Comment by bitprophet** [comment]
Thanks for the details (& presumably the continued digging...)! Love bug reports of this caliber :)

Nothing sprints immediately to mind as the cause; could be an issue in Fabric, could be in Paramiko; leaning Paramiko since I don't recall Fabric explicitly manipulating the transport's `_active` flag.

I'd definitely expect put and get to manifest similar symptoms, they're much closer to each other than they are to run/sudo.

Aside from looking at the details of how SFTP support works, I'd also suggest looking deeper at the cache itself - it ought to be pretty simple but it's grown some over the years.

**Comment by jconard3** [comment]
This is looking more like a a problem with [Paramiko](https://github.com/paramiko/paramiko/blob/833d9f76be9676419d5a0eb3bd9a66ce27b40214/paramiko/transport.py#L788).

When Paramiko goes to open a channel to the remote host, if hard checks the `connection[...]._transport.active` attribute. There doesn't seem to be any attempt currently to retry a failed connection with Fabric's implementation of Paramiko SFTP.

I'm sure there's a brute force check that could be added in Fabric to retry a connection before calling [open_sftp](https://github.com/fabric/fabric/blob/5d2e61cc78fe7a86f8ef4c6a167d7207ac1c4839/fabric/sftp.py#L33). However I'm unsure if retrying the connection should be Fabric's prerogative or Paramiko's. Would love to hear other's thoughts on this.

**Comment by hsecreto** [comment]
Is it still open?
