### ISSUE TITLE
Fabric Failing with ValueError: CTR mode needs counter parameter, not IV

### ISSUE THREAD

**Issue by GLStephen** [fabric/fabric#1564]
rsync commands work fine, but all of my command lines fail like this:

Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/fabric/main.py", line 756, in main
    *args, **kwargs
  File "/usr/lib64/python2.7/site-packages/fabric/tasks.py", line 386, in execute
    multiprocessing
  File "/usr/lib64/python2.7/site-packages/fabric/tasks.py", line 276, in _execute
    return task.run(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/fabric/tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)
  File "/stuff/fabric/fabfile.py", line 73, in restart_phpfpm
    run('sudo systemctl restart php-fpm')
  File "/usr/lib64/python2.7/site-packages/fabric/network.py", line 683, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/fabric/operations.py", line 1090, in run
    shell_escape=shell_escape, capture_buffer_size=capture_buffer_size,
  File "/usr/lib64/python2.7/site-packages/fabric/operations.py", line 930, in _run_command
    channel=default_channel(), command=wrapped_command, pty=pty,
  File "/usr/lib64/python2.7/site-packages/fabric/state.py", line 424, in default_channel
    chan = _open_session()
  File "/usr/lib64/python2.7/site-packages/fabric/state.py", line 416, in _open_session
    return connections[env.host_string].get_transport().open_session()
  File "/usr/lib64/python2.7/site-packages/fabric/network.py", line 159, in __getitem__
    self.connect(key)
  File "/usr/lib64/python2.7/site-packages/fabric/network.py", line 151, in connect
    user, host, port, cache=self, seek_gateway=seek_gateway)
  File "/usr/lib64/python2.7/site-packages/fabric/network.py", line 481, in connect
    client.connect(**kwargs)
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 338, in connect
    t.start_client()
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 492, in start_client
    raise e
ValueError: CTR mode needs counter parameter, not IV

**Comment by ploxiln** [comment]
https://github.com/paramiko/paramiko/pull/714

**Comment by bitprophet** [comment]
What he said. <3

**Comment by northbear** [comment]
I have the same problem, but update paramiko up to version 1.7.5 didn't solve problem. The problem arise after updating fabric from 1.3.2 to 1.4.4. Upgrade was forced by another issues not related ssh, so... 
If you have any ideas I will be very appreciated...

**Comment by bitprophet** [comment]
@northbear I assume you mean 1.17.5, not 1.7.5, hopefully! But, you might want to triple check the actual live Paramiko version Fabric is running against - as far as I know we've only seen this particular error message for the bug that was fixed in the linked ticket.

If you're sure it's Paramiko 1.17.5 running (e.g. `from paramiko import _version; print(_version.__version__)` then could you paste the full traceback you're getting that has the IV-related exception? Thanks!

**Comment by northbear** [comment]
Yeah, sure... It's my mistake, the version is 1.17.5 actually. There is no another version of paramiko installed in system. Trackback is provided below: 
[hpchead] run: grep 'model name' /proc/cpuinfo | head -n 1
Traceback (most recent call last):
  File "hostscan.py", line 134, in <module>
    main()
  File "hostscan.py", line 122, in main
    scanservers(host_list, dbhost)
  File "hostscan.py", line 56, in scanservers
    tasks.execute(fabtask.statistic, catchinfo.stats, hostdb, hosts=[hst])
  File "/usr/lib/python2.7/site-packages/fabric/tasks.py", line 305, in execute
    multiprocessing
  File "/usr/lib/python2.7/site-packages/fabric/tasks.py", line 204, in _execute
    return task.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fabric/tasks.py", line 114, in run
    return self.wrapped(*args, **kwargs)
  File "/labhome/igoryu/devel/hostscan/fabtask.py", line 79, in statistic
    s.run()
  File "/labhome/igoryu/devel/hostscan/catchinfo.py", line 22, in run
    resp = execute(fabtask.query, self.querystr(), hosts = [self._host])
  File "/usr/lib/python2.7/site-packages/fabric/tasks.py", line 305, in execute
    multiprocessing
  File "/usr/lib/python2.7/site-packages/fabric/tasks.py", line 204, in _execute
    return task.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fabric/tasks.py", line 114, in run
    return self.wrapped(*args, **kwargs)
  File "/labhome/igoryu/devel/hostscan/fabtask.py", line 71, in query
    return run(req[1])
  File "/usr/lib/python2.7/site-packages/fabric/network.py", line 463, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fabric/operations.py", line 909, in run
    return _run_command(command, shell, pty, combine_stderr)
  File "/usr/lib/python2.7/site-packages/fabric/operations.py", line 819, in _run_command
    stdout, stderr, status = _execute(default_channel(), wrapped_command, pty,
  File "/usr/lib/python2.7/site-packages/fabric/state.py", line 340, in default_channel
    chan = connections[env.host_string].get_transport().open_session()
  File "/usr/lib/python2.7/site-packages/fabric/network.py", line 84, in __getitem__
    self.connect(key)
  File "/usr/lib/python2.7/site-packages/fabric/network.py", line 76, in connect
    self[key] = connect(user, host, port)
  File "/usr/lib/python2.7/site-packages/fabric/network.py", line 292, in connect
    look_for_keys=not env.no_keys
  File "/usr/lib/python2.7/site-packages/ssh/client.py", line 302, in connect
    t.start_client()
  File "/usr/lib/python2.7/site-packages/ssh/transport.py", line 464, in start_client
    raise e
ValueError: CTR mode needs counter parameter, not IV

**Comment by northbear** [comment]
Additional info about versions of packages that used:
 $pip show fabric paramiko pycrypto ecdsa
Name: Fabric
Version: 1.4.4
Summary: Fabric is a simple, Pythonic tool for remote execution and deployment.
Home-page: http://fabfile.org
Author: Jeff Forcier
Author-email: jeff@bitprophet.org
License: UNKNOWN
Location: /usr/lib/python2.7/site-packages
Requires: ssh
---
Name: paramiko
Version: 1.17.5
Summary: SSH2 protocol library
Home-page: https://github.com/paramiko/paramiko/
Author: Jeff Forcier
Author-email: jeff@bitprophet.org
License: LGPL
Location: /usr/lib/python2.7/site-packages
Requires: pycrypto, ecdsa
---
Name: pycrypto
Version: 2.6.1
Summary: Cryptographic modules for Python.
Home-page: http://www.pycrypto.org/
Author: Dwayne C. Litzenberger
Author-email: dlitz@dlitz.net
License: UNKNOWN
Location: /usr/lib64/python2.7/site-packages
Requires:
---
Name: ecdsa
Version: 0.13
Summary: ECDSA cryptographic signature library (pure python)
Home-page: http://github.com/warner/python-ecdsa
Author: Brian Warner
Author-email: warner-pyecdsa@lothar.com
License: MIT
Location: /usr/lib/python2.7/site-packages
Requires:

**Comment by ploxiln** [comment]
Fabric-1.4.4 is very old. As you can tell from your traceback, it uses "ssh", not "paramiko". That renaming happened in Fabric-1.5 and paramiko-1.8 (which are very old compared to paramiko-1.17.5).

**Comment by northbear** [comment]
There is a interesting beholding: "Downgrading" fabric to version 1.13.2 solves this issues. 
But I prefer to have a deal with up-to-date versions of Fabric... I'll test with fabric 1.5 tomorrow. Thanks...

**Comment by bitprophet** [comment]
Yea, @ploxiln noticed the same thing I just did, you're using an older Fabric version that tells Python it uses the `ssh` fork of Paramiko. That's quite old so definitely using some newer Fabric version is recommended. @northbear do note that Fabric 1.13 is much _newer_ than Fabric 1.4! Version numbers go above 10 :D

**Comment by northbear** [comment]
Heh, really!! My mind was switched off after while.  I'm sorry, guys. It's my stupidness. Thank you alot. ))
