### ISSUE TITLE
Fabric About libssl.so.10 not found in Redhat5.1

### ISSUE THREAD

**Issue by NewLionwang** [fabric/fabric#1566]
when I use run('mkdir -p dir') in Redhat5.1,Fabric return ImportError:
[10.1.35.24] run: mkdir -p mstar
Traceback (most recent call last):
  File "/home/wxx/virtualenv-15.1.0/Auto_ms_envs/lib/python2.7/site-packages/fabric/main.py", line 756, in main
    *args, **kwargs
  File "/home/wxx/virtualenv-15.1.0/Auto_ms_envs/lib/python2.7/site-packages/fabric/tasks.py", line 386, in execute
    multiprocessing
  File "/home/wxx/virtualenv-15.1.0/Auto_ms_envs/lib/python2.7/site-packages/fabric/tasks.py", line 276, in _execute
    return task.run(*args, **kwargs)
  File "/home/wxx/virtualenv-15.1.0/Auto_ms_envs/lib/python2.7/site-packages/fabric/tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)
  File "/home/wxx/virtualenv-15.1.0/Auto_ms_envs/ms-devops/auto_ms.py", line 161, in go
    putfile()
  File "/home/wxx/virtualenv-15.1.0/Auto_ms_envs/lib/python2.7/site-packages/fabric/tasks.py", line 170, in __call__
    return self.run(*args, **kwargs)
  File "/home/wxx/virtualenv-15.1.0/Auto_ms_envs/lib/python2.7/site-packages/fabric/tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)
  File "/home/wxx/virtualenv-15.1.0/Auto_ms_envs/ms-devops/auto_ms.py", line 29, in putfile
    run('mkdir -p mstar')
  File "/home/wxx/virtualenv-15.1.0/Auto_ms_envs/lib/python2.7/site-packages/fabric/network.py", line 683, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/home/wxx/virtualenv-15.1.0/Auto_ms_envs/lib/python2.7/site-packages/fabric/operations.py", line 1090, in run
    shell_escape=shell_escape, capture_buffer_size=capture_buffer_size,
  File "/home/wxx/virtualenv-15.1.0/Auto_ms_envs/lib/python2.7/site-packages/fabric/operations.py", line 930, in _run_command
    channel=default_channel(), command=wrapped_command, pty=pty,
  File "/home/wxx/virtualenv-15.1.0/Auto_ms_envs/lib/python2.7/site-packages/fabric/state.py", line 424, in default_channel
    chan = _open_session()
  File "/home/wxx/virtualenv-15.1.0/Auto_ms_envs/lib/python2.7/site-packages/fabric/state.py", line 416, in _open_session
    return connections[env.host_string].get_transport().open_session()
  File "/home/wxx/virtualenv-15.1.0/Auto_ms_envs/lib/python2.7/site-packages/fabric/network.py", line 159, in __getitem__
    self.connect(key)
  File "/home/wxx/virtualenv-15.1.0/Auto_ms_envs/lib/python2.7/site-packages/fabric/network.py", line 151, in connect
    user, host, port, cache=self, seek_gateway=seek_gateway)
  File "/home/wxx/virtualenv-15.1.0/Auto_ms_envs/lib/python2.7/site-packages/fabric/network.py", line 434, in connect
    client.load_system_host_keys()
  File "/home/wxx/virtualenv-15.1.0/Auto_ms_envs/lib/python2.7/site-packages/paramiko/client.py", line 101, in load_system_host_keys
    self._system_host_keys.load(filename)
  File "/home/wxx/virtualenv-15.1.0/Auto_ms_envs/lib/python2.7/site-packages/paramiko/hostkeys.py", line 101, in load
    e = HostKeyEntry.from_line(line, lineno)
  File "/home/wxx/virtualenv-15.1.0/Auto_ms_envs/lib/python2.7/site-packages/paramiko/hostkeys.py", line 331, in from_line
    key = RSAKey(data=decodebytes(key))
  File "/home/wxx/virtualenv-15.1.0/Auto_ms_envs/lib/python2.7/site-packages/paramiko/rsakey.py", line 58, in __init__
    ).public_key(default_backend())
  File "/home/wxx/virtualenv-15.1.0/Auto_ms_envs/lib/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 71, in default_backend
    _default_backend = MultiBackend(_available_backends())
  File "/home/wxx/virtualenv-15.1.0/Auto_ms_envs/lib/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 28, in _available_backends
    "cryptography.backends"
  File "/home/wxx/virtualenv-15.1.0/Auto_ms_envs/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/wxx/virtualenv-15.1.0/Auto_ms_envs/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/home/wxx/virtualenv-15.1.0/Auto_ms_envs/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 51, in <module>
    from cryptography.hazmat.bindings._openssl import ffi as _ffi
ImportError: libssl.so.10: cannot open shared object file: No such file or directory

But...
$ whereis libssl.so.10
libssl.so: /lib/libssl.so.6 /usr/lib/libssl.so /usr/lib/libssl.so.10 /usr/lib/libssl.so.6

I don't know why.
I test the same case in Redhat5.3 or Redhat6.X.It's OK!

**Comment by bitprophet** [comment]
That's some sort of issue between RedHat (or your specific system) and the Cryptography library we depend on. I think you should check the following:

- Are you using the same version of Fabric, Paramiko and OpenSSL on the other systems? (Maybe RedHat 5.1's OpenSSL is too old?)
- Consider downgrading Paramiko to <2.0 so that it uses PyCrypto; this is not ideal but also means no OpenSSL problems.
- Look at the https://github.com/pyca/cryptography repo for details on this kind of error.

Good luck! Nothing else we can do on our end unfortunately.

**Comment by NewLionwang** [comment]
I change the  Paramiko version from 2.1 to 1.15.2

$ fab --version
Fabric 1.13.1
Paramiko 1.15.2

It's be ok .But if you install Fabric from pip ,the Paramiko version is 2.1.。。。
