### ISSUE TITLE
Parallel execution swallows env variables

### ISSUE THREAD

**Issue by miki725** [fabric/fabric#1567]
Consider the following fab file:

```python
from fabric.api import env, task, run

@task
def environment():
    env.mod_wsgi_user = 'www'

@task
def test_mod_wsgi_user():
    run('echo hello world')
    print(env.mod_wsgi_user)
```

Running tasks in serial:

```
❯❯❯ fab -H 10.211.55.27 -u vagrant -i ~/Vagrant/docker/.vagrant/machines/default/parallels/private_key -f test_fabfile.py environment test_mod_wsgi_user
[10.211.55.27] Executing task 'environment'
[10.211.55.27] Executing task 'test_mod_wsgi_user'
[10.211.55.27] run: echo hello world
[10.211.55.27] out: hello world
[10.211.55.27] out:

www

Done.
Disconnecting from 10.211.55.27... done.
```

Running in parallel causes the following exception:

```
❯❯❯ fab -P -H 10.211.55.27 -u vagrant -i ~/Vagrant/docker/.vagrant/machines/default/parallels/private_key -f test_fabfile.py environment test_mod_wsgi_user
[10.211.55.27] Executing task 'environment'
[10.211.55.27] Executing task 'test_mod_wsgi_user'
[10.211.55.27] run: echo hello world
[10.211.55.27] out: hello world
[10.211.55.27] out:

!!! Parallel execution exception under host '10.211.55.27':
Process 10.211.55.27:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/miki725/.virtualenvs/deployment/lib/python2.7/site-packages/fabric/tasks.py", line 241, in inner
    submit(task.run(*args, **kwargs))
  File "/Users/miki725/.virtualenvs/deployment/lib/python2.7/site-packages/fabric/tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)
  File "/Users/miki725/Projects/deployment/test_fabfile.py", line 12, in test_mod_wsgi_user
    print(env.mod_wsgi_user)
  File "/Users/miki725/.virtualenvs/deployment/lib/python2.7/site-packages/fabric/utils.py", line 213, in __getattr__
    raise AttributeError(key)
AttributeError: mod_wsgi_user

Fatal error: One or more hosts failed while executing task 'test_mod_wsgi_user'

Underlying exception:
    mod_wsgi_user

Aborting.
```

Am using `Fabric==1.13.1` which is latest in PyPI.

Any ideas? Is this a bug or Im doing something wrong?

**Comment by bitprophet** [comment]
It's because you're running _everything_ in parallel; parallel tasks cannot affect the core, shared env as they run in a separate process. They're given the env as it exists before they fork and then that's it.

You probably want to use the `@parallel` decorator on the 2nd task and drop the use of `-P`; this will allow `environment()` to update the env (it will run serially) and then only `test_mod_wsgi_user` will run in parallel (and will be given the env modified by `environment`).
