### ISSUE TITLE
Strange behaviour with host behind jump box (ProxyCommand ssh -W)

### ISSUE THREAD

**Issue by gionn** [fabric/fabric#1588]
Hi,

I am seeing a strange behaviour with a particolar group of hosts configured in ssh-config with:

```
Host staging-consul
  User ubuntu
  Hostname 192.168.1.29
  ProxyCommand ssh -W %h:%p ubuntu@re.da.ct.ed
```

When I issue a reboot(), everytime, sometime I get:

```
Login password for 'ubuntu': ERROR:paramiko.transport:Exception: Error reading SSH protocol banner
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "/home/gionn/.pyenv/versions/2.7.8/lib/python2.7/site-packages/paramiko/transport.py", line 1749, in run
ERROR:paramiko.transport:    self._check_banner()
ERROR:paramiko.transport:  File "/home/gionn/.pyenv/versions/2.7.8/lib/python2.7/site-packages/paramiko/transport.py", line 1897, in _check_banner
ERROR:paramiko.transport:    raise SSHException('Error reading SSH protocol banner' + str(e))
ERROR:paramiko.transport:SSHException: Error reading SSH protocol banner
ERROR:paramiko.transport:
ERROR:paramiko.transport:Exception: ('ssh -W 192.168.1.18:22 ubuntu@re.da.ct.ed', 'Broken pipe')
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "/home/gionn/.pyenv/versions/2.7.8/lib/python2.7/site-packages/paramiko/transport.py", line 1765, in run
ERROR:paramiko.transport:    ptype, m = self.packetizer.read_message()
ERROR:paramiko.transport:  File "/home/gionn/.pyenv/versions/2.7.8/lib/python2.7/site-packages/paramiko/packet.py", line 391, in read_message
ERROR:paramiko.transport:    header = self.read_all(self.__block_size_in, check_rekey=True)
ERROR:paramiko.transport:  File "/home/gionn/.pyenv/versions/2.7.8/lib/python2.7/site-packages/paramiko/packet.py", line 279, in read_all
ERROR:paramiko.transport:    self._check_keepalive()
ERROR:paramiko.transport:  File "/home/gionn/.pyenv/versions/2.7.8/lib/python2.7/site-packages/paramiko/packet.py", line 478, in _check_keepalive
ERROR:paramiko.transport:    self.__keepalive_callback()
ERROR:paramiko.transport:  File "/home/gionn/.pyenv/versions/2.7.8/lib/python2.7/site-packages/paramiko/transport.py", line 976, in <lambda>
ERROR:paramiko.transport:    lambda x=weakref.proxy(self): x.global_request('keepalive@lag.net', wait=False))
ERROR:paramiko.transport:  File "/home/gionn/.pyenv/versions/2.7.8/lib/python2.7/site-packages/paramiko/transport.py", line 1004, in global_request
ERROR:paramiko.transport:    self._send_user_message(m)
ERROR:paramiko.transport:  File "/home/gionn/.pyenv/versions/2.7.8/lib/python2.7/site-packages/paramiko/transport.py", line 1612, in _send_user_message
ERROR:paramiko.transport:    self._send_message(data)
ERROR:paramiko.transport:  File "/home/gionn/.pyenv/versions/2.7.8/lib/python2.7/site-packages/paramiko/transport.py", line 1592, in _send_message
ERROR:paramiko.transport:    self.packetizer.send_message(data)
ERROR:paramiko.transport:  File "/home/gionn/.pyenv/versions/2.7.8/lib/python2.7/site-packages/paramiko/packet.py", line 368, in send_message
ERROR:paramiko.transport:    self.write_all(out)
ERROR:paramiko.transport:  File "/home/gionn/.pyenv/versions/2.7.8/lib/python2.7/site-packages/paramiko/packet.py", line 288, in write_all
ERROR:paramiko.transport:    n = self.__socket.send(out)
ERROR:paramiko.transport:  File "/home/gionn/.pyenv/versions/2.7.8/lib/python2.7/site-packages/paramiko/proxy.py", line 73, in send
ERROR:paramiko.transport:    raise ProxyCommandFailure(' '.join(self.cmd), e.strerror)
ERROR:paramiko.transport:ProxyCommandFailure: ('ssh -W 192.168.1.18:22 ubuntu@re.da.ct.ed', 'Broken pipe')
ERROR:paramiko.transport:
```

And sometimes I get:

```
Fatal error: No existing session

Underlying exception:
    No existing session

Aborting.
Disconnecting from ubuntu@192.168.1.18... done.
ERROR:paramiko.transport:Exception: Error reading SSH protocol banner
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "/home/gionn/.pyenv/versions/2.7.8/lib/python2.7/site-packages/paramiko/transport.py", line 1749, in run
ERROR:paramiko.transport:    self._check_banner()
ERROR:paramiko.transport:  File "/home/gionn/.pyenv/versions/2.7.8/lib/python2.7/site-packages/paramiko/transport.py", line 1897, in _check_banner
ERROR:paramiko.transport:    raise SSHException('Error reading SSH protocol banner' + str(e))
ERROR:paramiko.transport:SSHException: Error reading SSH protocol banner
ERROR:paramiko.transport:
```

This happens on every node configured with -W, and I never see anything like that before on hosts without -W.

```
$ fab --version
Fabric 1.13.1
Paramiko 2.1.2
```

**Comment by bitprophet** [comment]
I had to read twice to realize this was specific to `reboot()`! Makes more sense now. I _suspect_ the same would happen with nearly any proxy-command setup; rebooting will kill the remote sshd which would break the connection between the proxy subprocess and the sshd. (Offhand, that'd be hard to come back from without explicitly destroying [or catching and ignoring the death of] that subprocess, then recreating it after the remote sshd is back up.)

Have you encountered this with an alternate proxy-command setup at all? I.e. are you asserting this is specific to a ProxyCommand of `ssh -W`, or is it what I theorized above, a generic "proxying + rebooting = not well handled" situation?

**Comment by gionn** [comment]
This is the first time I am using fabric with hosts that needs a ProxyCommand, but should be easy to reproduce since I am getting it every time with reboot().

Another nice finding is that if I replace `reboot()` with `sudo('shutdown -r now')` this behavior is not triggered (fabric exits cleanly).

My nodes are Ubuntu 14.04.

**Comment by ploxiln** [comment]
If `shutdown -r now` works, then this seems to be a variant of #1488, which I think sums up to "reboot command is too fast in some cases for fabric to see it complete successfully", and those cases now also include an older distro if using ProxyCommand.

I noticed that `shutdown -r +0` works in a couple more cases than `shutdown -r now`, which I think is somewhere in between `shutdown -r +0` and `reboot` in terms of how asynchronous it is, depending on the OS (even though they should all be equivalent). What would be ideal is "start shutdown in 3 seconds", but the only supported options seem to be now, or 1 or more minutes later.

Note that you can get the rest of the `reboot()` helper functionality while using a custom command, like: `reboot(command="shutdown -r +0")`

**Comment by gionn** [comment]
@ploxiln I've tried a few times with ```reboot(command="shutdown -r +0")``` and with ```reboot(command="shutdown -r now")``` but it is always failing as reported:

```
ERROR:paramiko.transport:Exception: Error reading SSH protocol banner
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "/home/gionn/.pyenv/versions/2.7.8/lib/python2.7/site-packages/paramiko/transport.py", line 1749, in run
ERROR:paramiko.transport:    self._check_banner()
ERROR:paramiko.transport:  File "/home/gionn/.pyenv/versions/2.7.8/lib/python2.7/site-packages/paramiko/transport.py", line 1897, in _check_banner
ERROR:paramiko.transport:    raise SSHException('Error reading SSH protocol banner' + str(e))
ERROR:paramiko.transport:SSHException: Error reading SSH protocol banner
ERROR:paramiko.transport:
```

I am starting to think that the problem is triggered by the behaviour of the `reboot` command.

As a final test, I tried with ```sudo(command='shutdown -r +0')``` and fabric exited cleanly.

**Comment by ploxiln** [comment]
OK - the difference is that `reboot()` also disconnects from the remote host. This disconnect / reconnect appears to still be a problem for ProxyCommand connections. Thanks.
