### ISSUE TITLE
Agent forwarding not work when using Pageant ssh agent on Windows

### ISSUE THREAD

**Issue by Extravert-ir** [fabric/fabric#1621]
Using this fabfile and running Pageant (on Windows):
`from fabric.api import run, env

env.forward_agent = True

def test_pageant():
    run('git ls-remote --heads user@repo_host:repository.git')`

Running following command: **fab -H user@deploy_host test_pageant** results an exception:
`Exception in thread Thread-3:
Traceback (most recent call last):
  File "c:\python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "c:\python27\lib\site-packages\paramiko\agent.py", line 117, in run
    raise AuthenticationException("Unable to connect to SSH agent")
AuthenticationException: Unable to connect to SSH agent`

So it correctly logins to deploy_host but fails when try to use agent for login to repo_host

**Comment by ploxiln** [comment]
Looks like paramiko could/should try to connect to Pageant, I'm not sure why it isn't in your case.
https://github.com/paramiko/paramiko/blob/2.1.2/paramiko/agent.py#L354

**Comment by ploxiln** [comment]
... oh, doesn't work when enabling forwarding, nvm ...

**Comment by bitprophet** [comment]
Fair chance this is really a Paramiko level issue but let's leave it here for now. Sadly I can't debug it myself as I don't use Windows; hopefully one of our Windows-using contributors will be able to help.

**Comment by ALERTua** [comment]
any workarounds?

**Comment by KarlMaresch** [comment]
Having exactly the same error.
Any updates on this?

**Comment by KarlMaresch** [comment]
just a quick heads up again.
Found a fix for this on https://github.com/Microsoft/WSL/issues/3206

Simply do 
```
eval $(ssh-agent -s)
ssh-add ~/.ssh/id_rsa
```
each time before you run your fab file. 

--> best as an alias in bash_aliases

```
function ssa() {
  eval $(ssh-agent -s)
  ssh-add ~/.ssh/id_rsa
}
```

**Comment by miso-belica** [comment]
HI, it seems the problem is still there even in `Fabric==2.5.0`. I run into the issue today. Here is my example task.

```python
@task(hosts=["example.com"])
def deploy(c):
    c.user = "user"
    c.forward_agent = True

    with c.cd("/app"):
        c.run("git pull")
```

@bitprophet I never programmed SSH related library or protocol, but you wrote _hopefully one of our Windows-using contributors will be able to help._ and it seems nobody is interested till today. If you could guide me a little maybe I would be able to fix it for Windows & Pageant. I use Fabric quite a lot and maybe it's time to contribute :) Or maybe someone else will find the solution. What do you think?
