### ISSUE TITLE
Do not use answer kit, but got error log about answer

### ISSUE THREAD

**Issue by jiachenning** [fabric/fabric#1629]
I use `com.crashlytics.sdk.android:crashlytics:2.2.3` and got error like "Answers: Error dealing with settings" when my app launchs.

Then I upgrade to `com.crashlytics.sdk.android:crashlytics:2.6.8` and got another ANSWER error "Failed to enable events java.io.EOFException" .

Question:

**Why I use crashlytics and got a answer error ?**

code here:

        private void initFabric() {
            Fabric.Builder builder = new Fabric.Builder(this).kits(new Crashlytics());
            final Fabric fabric = builder.build();
            Fabric.with(fabric);
        }

full stack trace:

      java.io.EOFException
            at java.io.RandomAccessFile.readFully(RandomAccessFile.java:415)
            at java.io.RandomAccessFile.readFully(RandomAccessFile.java:393)
            at io.fabric.sdk.android.services.common.QueueFile.readHeader(QueueFile.java:173)
            at io.fabric.sdk.android.services.common.QueueFile.<init>(QueueFile.java:133)
            at io.fabric.sdk.android.services.events.QueueFileEventStorage.<init>(QueueFileEventStorage.java:58)
            at io.fabric.sdk.android.services.events.GZIPQueueFileEventStorage.<init>(GZIPQueueFileEventStorage.java:32)
            at com.crashlytics.android.answers.AnswersFilesManagerProvider.getAnalyticsFilesManager(AnswersFilesManagerProvider.java:44)
            at com.crashlytics.android.answers.AnswersEventsHandler$4.run(AnswersEventsHandler.java:121)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
            at io.fabric.sdk.android.services.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:75)
            at io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:30)
            at java.lang.Thread.run(Thread.java:761)

**Comment by jiachenning** [comment]
I confuse the http://fabfile.org and https://fabric.io, please close it.
