### ISSUE TITLE
Password Authentication not working after keys fail

### ISSUE THREAD

**Issue by cmacnevin** [fabric/fabric#1643]
This is driving me nuts because it did work, until I was forced to accommodate other hosts. So I'm likely missing something in the execution order.

In the below code, I constantly see Paramiko's debugging showing it attempting to connect with public key, and when it fails, it automatically prompts me for a password, even though one is populated. The password then fails. Note that a direct ssh connection with the same credentials works fine. 

On top of that, if I set both 'env.key_filename' and 'look_for_keys' to False, it doesn't even try to connect.

Here's all the code in the execution path (barring parts which retrieve passwords from sockets):
```

cisco_switch = open('cisco_switches').read().splitlines()

@task
def get_ver_cisco(hostlist = cisco_switch):
    get_pw('admin') # get password from key store, for security reasons
    results = execute_run('sh version', hostlist, 'cisco')

def execute_run(Command, hostlist, vendor):
    if vendor == 'cisco':
        with settings(
                look_for_keys = False,
                always_use_pty = False,
                skip_bad_hosts = True,
                warn_only = True,
                allow_agent = False,
                eagerly_disconnect = True):
            output = execute(run_command, Command, hosts=hostlist) # sends command to run_command, u
            return output

def run_command(Command):
    try:
        output = run(Command, shell = False)
        return output
    except exceptions.NetworkError as e:
        failed_hosts[env.host_string] = e

```

Here's the paramiko debugged connection attempt:

```
fab get_ver_cisco 
DEBUG:paramiko.transport:starting thread (client mode): 0xe9e7da10L
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.2.1
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-Cisco-1.25
INFO:paramiko.transport:Connected (version 2.0, client Cisco-1.25)
DEBUG:paramiko.transport:kex algos:[u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa'] client encrypt:[u'aes128-cbc', u'3des-cbc', u'aes192-cbc', u'aes256-cbc'] server encrypt:[u'aes128-cbc', u'3des-cbc', u'aes192-cbc', u'aes256-cbc'] client mac:[u'hmac-sha1', u'hmac-sha1-96', u'hmac-md5', u'hmac-md5-96'] server mac:[u'hmac-sha1', u'hmac-sha1-96', u'hmac-md5', u'hmac-md5-96'] client compress:[u'none'] server compress:[u'none'] client lang:[u''] server lang:[u''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group1-sha1
DEBUG:paramiko.transport:HostKey agreed: ssh-rsa
DEBUG:paramiko.transport:Cipher agreed: aes128-cbc
DEBUG:paramiko.transport:MAC agreed: hmac-sha1
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexGroup1 specified hash_algo <built-in function openssl_sha1>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Trying key ffffffffffffffffffffffffffffffff from ~/.ssh/id_fabric
DEBUG:paramiko.transport:userauth is OK
DEBUG:paramiko.transport:Authentication type (publickey) not permitted.
DEBUG:paramiko.transport:Allowed methods: [u'password']
INFO:paramiko.transport:Disconnect (code 2): Protocol error: expected packet type 50, got 5
[switch01] Login password for 'admin': 
DEBUG:paramiko.transport:starting thread (client mode): 0xea88f2d0L

```

**Comment by cmacnevin** [comment]
bumpbump?

**Comment by Winand** [comment]
Debug output after key authentication fails (fabric-2.6.0):
`fab -d -H root@172.24.92.233 task-user-exists`
```
...
paramiko.transport.transport._log: userauth is OK
paramiko.transport.transport._log: Authentication (publickey) failed.
Traceback (most recent call last):
  File "C:\Users\Andrey.makarov\conda\Scripts\fab-script.py", line 10, in <module>
    sys.exit(program.run())
  File "C:\Users\Andrey.makarov\conda\lib\site-packages\invoke\program.py", line 384, in run
    self.execute()
  File "C:\Users\Andrey.makarov\conda\lib\site-packages\invoke\program.py", line 566, in execute
    executor.execute(*self.tasks)
  File "C:\Users\Andrey.makarov\conda\lib\site-packages\invoke\executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "C:\Users\Andrey.makarov\conda\lib\site-packages\invoke\tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "C:\Users\Andrey.makarov\Documents\projects_ocrv\auto_deployment\fabfile.py", line 41, in task_user_exists
    home = get_home(c, "kpsuser")
  File "C:\Users\Andrey.makarov\Documents\projects_ocrv\auto_deployment\fabfile.py", line 33, in get_home
    result = c.run(f'echo ~{username}', warn=True, hide=True)
  File "<decorator-gen-3>", line 2, in run
  File "C:\Users\Andrey.makarov\conda\lib\site-packages\fabric\connection.py", line 29, in opens
    self.open()
  File "C:\Users\Andrey.makarov\conda\lib\site-packages\fabric\connection.py", line 636, in open
    self.client.connect(**kwargs)
  File "C:\Users\Andrey.makarov\conda\lib\site-packages\paramiko\client.py", line 435, in connect
    self._auth(
  File "C:\Users\Andrey.makarov\conda\lib\site-packages\paramiko\client.py", line 764, in _auth
    raise saved_exception
  File "C:\Users\Andrey.makarov\conda\lib\site-packages\paramiko\client.py", line 740, in _auth
    self._transport.auth_publickey(username, key)
  File "C:\Users\Andrey.makarov\conda\lib\site-packages\paramiko\transport.py", line 1580, in auth_publickey
    return self.auth_handler.wait_for_response(my_event)
  File "C:\Users\Andrey.makarov\conda\lib\site-packages\paramiko\auth_handler.py", line 250, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.
paramiko.transport.transport._log: EOF in transport thread
```

If there's no key available it says "No authentication methods available". Isn't it supposed to ask for password? It only asks for password with `--prompt-for-login-password` flag.
