### ISSUE TITLE
when using put from windows to linux i am getting a CustomExceptionHandler handled exception [Errno 13] Permission denied

### ISSUE THREAD

**Issue by pint12** [fabric/fabric#1646]
when  using version 2 of fabric     
i am trying execute the "put" command from 
windows to linux i am getting a CustomExceptionHandler handled exception [Errno 13] Permission denied

for the file in windows

**Comment by bitprophet** [comment]
Can you post the full traceback, an example of your code, and a detailed (w/ permissions included, if possible) file listing of the directory the local file is in? Hard to say exactly what's happening without that.

The file handling is pretty basic so Occam's razor says maybe the file really doesn't have good permissions locally, or that the path handling is resulting in the wrong path.

**Comment by pint12** [comment]
traceback: 


24:35[DEBUG][chan 0] normalize('.')
14:24:35[DEBUG]Massaged relative remote path '~/DeploymentMangerPackages' into u'/users/mpswrk1/~/DeploymentMangerPackages'
14:24:35[DEBUG]Massaged relative local path u'temp/59a2abe1fa81e004a9417a6d' into u'C:\\Users\\IlanPi\\Documents\\GSS\\git\\Tools\\DeploymentManger\\temp\\59a2abe1fa81e004a9417a6d'
14:24:35[DEBUG]Uploading u'C:\\Users\\IlanPi\\Documents\\GSS\\git\\Tools\\DeploymentManger\\temp\\59a2abe1fa81e004a9417a6d' to u'/users/mpswrk1/~/DeploymentMangerPackages'
14:24:35[INFO ][CustomExceptionHandler:newFunction()]: CustomExceptionHandler handled exception [Errno 13] Permission denied: u'C:\\Users\\IlanPi\\Documents\\GSS\\git\\Tools\\DeploymentManger\\temp\\59a2abe1fa81e004a9417a6d'
14:24:35[ERROR][traceback:_print()]: Traceback (most recent call last):
14:24:35[ERROR][traceback:_print()]:   File "C:\Users\IlanPi\Documents\GSS\git\Tools\DeploymentManger\Services\CustomExceptionHandler.py", line 26, in newFunction
14:24:35[ERROR][traceback:_print()]:     result = f(*args, **kw)  # VALUES SHOULD BE NEVER RETURND AS STRING
14:24:35[ERROR][traceback:_print()]:   File "C:\Users\IlanPi\Documents\GSS\git\Tools\DeploymentManger\Services\fabfile.py", line 259, in copyFiles
14:24:35[ERROR][traceback:_print()]:     connect.put(From, To)
14:24:35[ERROR][traceback:_print()]:   File "C:\Python27\lib\site-packages\fabric2-2.0.0-py2.7.egg\fabric2\connection.py", line 589, in put
14:24:35[ERROR][traceback:_print()]:     return Transfer(self).put(*args, **kwargs)
14:24:35[ERROR][traceback:_print()]:   File "C:\Python27\lib\site-packages\fabric2-2.0.0-py2.7.egg\fabric2\transfer.py", line 212, in put
14:24:35[ERROR][traceback:_print()]:     sftp.put(localpath=local, remotepath=remote)
14:24:35[ERROR][traceback:_print()]:   File "C:\Python27\lib\site-packages\paramiko\sftp_client.py", line 675, in put
14:24:35[ERROR][traceback:_print()]:     with open(localpath, 'rb') as fl:
14:24:35[ERROR][traceback:_print()]: IOError: [Errno 13] Permission denied: u'C:\\Users\\IlanPi\\Documents\\GSS\\git\\Tools\\DeploymentManger\\temp\\59a2abe1fa81e004a9417a6d'
14:24:35[ERROR][traceback:_print()]: Traceback (most recent call last):
14:24:35[ERROR][traceback:_print()]:   File "C:\Users\IlanPi\Documents\GSS\git\Tools\DeploymentManger\Services\DeploymentServices.py", line 468, in TransferPackage
14:24:35[ERROR][traceback:_print()]:     raise future.exception()
14:24:35[ERROR][traceback:_print()]: Exception: [Errno 13] Permission denied: uC:\\Users\\IlanPi\\Documents\\GSS\\git\\Tools\\DeploymentManger\\temp\\59a2abe1fa81e004a9417a6d
14:24:35[INFO ][DeploymentServices:handleLogs()]: DeploymentServices: _id: 59a2abe1fa81e004a9417a6d Removing Directory temp/59a2abe1fa81e004a9417a6d
14:24:36[INFO ]127.0.0.1 - - [27/Aug/2017 14:24:36] "GET /deploymentrequest/all HTTP/1.1" 200 -
14:24:36[INFO ]127.0.0.1 - - [27/Aug/2017 14:24:36] "GET /deploymentrequest/group%2Fview%2F59a2abe1fa81e004a9417a6e HTTP/1.1" 200 -
14


i have copied below the permissions using the icacls the (F) us for full permission 
C:\Users\IlanPi\Documents\GSS\git\Tools\DeploymentManger\temp>icacls  59955aa3fa81e06da4251587
59955aa3fa81e06da4251587 NT AUTHORITY\SYSTEM:(I)(OI)(CI)(F)
                         BUILTIN\Administrators:(I)(OI)(CI)(F)
                         NTNET\ILANPI:(I)(OI)(CI)(F)

Successfully processed 1 files; Failed processing 0 files
