### ISSUE TITLE
`pip install fabric` breaks pip on xenial

### ISSUE THREAD

**Issue by dblackdblack** [fabric/fabric#1666]
```
$ pip

Usage:
  pip <command> [options]

Commands:
  install                     Install packages.
  download                    Download packages.
  uninstall                   Uninstall packages.
  freeze                      Output installed packages in requirements format.
  list                        List installed packages.
  show                        Show information about installed packages.
  search                      Search PyPI for packages.
  wheel                       Build wheels from your requirements.
  hash                        Compute hashes of package archives.
  completion                  A helper command used for command completion
  help                        Show help for commands.

General Options:
  -h, --help                  Show help.
  --isolated                  Run pip in an isolated mode, ignoring environment variables and user configuration.
  -v, --verbose               Give more output. Option is additive, and can be used up to 3 times.
  -V, --version               Show version and exit.
  -q, --quiet                 Give less output.
  --log <path>                Path to a verbose appending log.
  --proxy <proxy>             Specify a proxy in the form [user:passwd@]proxy.server:port.
  --retries <retries>         Maximum number of retries each connection should attempt (default 5 times).
  --timeout <sec>             Set the socket timeout (default 15 seconds).
  --exists-action <action>    Default action when a path already exists: (s)witch, (i)gnore, (w)ipe, (b)ackup.
  --trusted-host <hostname>   Mark this host as trusted, even though it does not have valid or any HTTPS.
  --cert <path>               Path to alternate CA bundle.
  --client-cert <path>        Path to SSL client certificate, a single file containing the private key and the certificate in PEM format.
  --cache-dir <dir>           Store the cache data in <dir>.
  --no-cache-dir              Disable the cache.
  --disable-pip-version-check
                              Don't periodically check PyPI to determine whether a new version of pip is available for download. Implied with --no-index.

$ sudo pip install fabric 
Collecting fabric
  Downloading Fabric-1.14.0-py2-none-any.whl (92kB)
    100% |████████████████████████████████| 102kB 7.1MB/s
Collecting paramiko<3.0,>=1.10 (from fabric)
  Downloading paramiko-2.3.0-py2.py3-none-any.whl (182kB)
    100% |████████████████████████████████| 184kB 4.4MB/s
Collecting pynacl>=1.0.1 (from paramiko<3.0,>=1.10->fabric)
  Downloading PyNaCl-1.1.2-cp27-cp27mu-manylinux1_x86_64.whl (539kB)
    100% |████████████████████████████████| 542kB 1.7MB/s
Collecting cryptography>=1.5 (from paramiko<3.0,>=1.10->fabric)
  Downloading cryptography-2.0.3-cp27-cp27mu-manylinux1_x86_64.whl (2.2MB)
    100% |████████████████████████████████| 2.2MB 554kB/s
Collecting bcrypt>=3.1.3 (from paramiko<3.0,>=1.10->fabric)
  Downloading bcrypt-3.1.3-cp27-cp27mu-manylinux1_x86_64.whl (57kB)
    100% |████████████████████████████████| 61kB 10.1MB/s
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.7 in /usr/local/lib/python2.7/dist-packages (from paramiko<3.0,>=1.10->fabric)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/dist-packages (from pynacl>=1.0.1->paramiko<3.0,>=1.10->fabric)
Collecting cffi>=1.4.1 (from pynacl>=1.0.1->paramiko<3.0,>=1.10->fabric)
  Downloading cffi-1.11.0-cp27-cp27mu-manylinux1_x86_64.whl (405kB)
    100% |████████████████████████████████| 409kB 3.3MB/s
Requirement already satisfied (use --upgrade to upgrade): ipaddress in /usr/lib/python2.7/dist-packages (from cryptography>=1.5->paramiko<3.0,>=1.10->fabric)
Collecting idna>=2.1 (from cryptography>=1.5->paramiko<3.0,>=1.10->fabric)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 12.0MB/s
Collecting asn1crypto>=0.21.0 (from cryptography>=1.5->paramiko<3.0,>=1.10->fabric)
  Downloading asn1crypto-0.22.0-py2.py3-none-any.whl (97kB)
    100% |████████████████████████████████| 102kB 11.9MB/s
Requirement already satisfied (use --upgrade to upgrade): enum34 in /usr/lib/python2.7/dist-packages (from cryptography>=1.5->paramiko<3.0,>=1.10->fabric)
Collecting pycparser (from cffi>=1.4.1->pynacl>=1.0.1->paramiko<3.0,>=1.10->fabric)
  Downloading pycparser-2.18.tar.gz (245kB)
    100% |████████████████████████████████| 256kB 5.0MB/s
Installing collected packages: pycparser, cffi, pynacl, idna, asn1crypto, cryptography, bcrypt, paramiko, fabric
  Running setup.py install for pycparser ... done
  Found existing installation: idna 2.0
    Uninstalling idna-2.0:
      Successfully uninstalled idna-2.0
  Found existing installation: cryptography 1.2.3
    Uninstalling cryptography-1.2.3:
      Successfully uninstalled cryptography-1.2.3
Successfully installed asn1crypto-0.22.0 bcrypt-3.1.3 cffi-1.11.0 cryptography-2.0.3 fabric-1.14.0 idna-2.6 paramiko-2.3.0 pycparser-2.18 pynacl-1.1.2
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

$ pip
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip import main
  File "/usr/local/lib/python2.7/dist-packages/pip/__init__.py", line 16, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/local/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 39, in <module>
    from pip._vendor import requests, six
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/contrib/pyopenssl.py", line 54, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
```

running `sudo easy_install pyopenssl==17.3.0` restores pip's functionality
I'm almost certain this is the fault of some upstream package but it's kind of a big deal.

`pip install Fabric==1.12.2` does not have this issue

**Comment by ploxiln** [comment]
OK, here's roughly what happened:

  * You have the python-openssl package installed, instead of a recent pyOpenSSL from pypi.
  * You have a recent pip from pypi installed, instead of the python-pip package.
  * You have just installed a recent cryptography-2.0.3, uninstalling the old cryptography-1.2.3.
  * The OpenSSL module (called python-openssl in the ubuntu repos and pyOpenSSL on pypi) uses the cryptography module.
  * cryptography-1.2.3 is actually the version provided by the python-cryptography ubuntu package which the python-openssl ubuntu package depends on.

I observed pip uninstalling the cryptography in `/usr/lib/python2.7` which was from the ubuntu package installed with apt, before it installed a newer cryptography in `/usr/local/lib/python2.7`. Needless to say, it is very not good for something besides apt/dpkg to mess with apt/dpkg installed stuff.

One work-around for you is to not install the upgraded pip, stick with the one from the package manager. That works for me. It also avoids messing with the ubuntu-package-installed cryptography:

```
...
Installing collected packages: idna, asn1crypto, pycparser, cffi, cryptography
  Found existing installation: idna 2.0
    Not uninstalling idna at /usr/lib/python2.7/dist-packages, outside environment /usr
  Found existing installation: cryptography 1.2.3
    Not uninstalling cryptography at /usr/lib/python2.7/dist-packages, outside environment /usr
Successfully installed asn1crypto-0.22.0 cffi-1.11.0 cryptography-2.0.3 idna-2.6 pycparser-2.18
You are using pip version 8.1.1, however version 9.0.1 is available.
```

**Comment by ploxiln** [comment]
some other general pip tips:
  * don't use sudo, instead `pip install --user`
  * use virtualenv

**Comment by dblackdblack** [comment]
thanks for your deep dive here
openssl is not the best thing in the world
