### ISSUE TITLE
AttributeError: 'module' object has no attribute 'GSSException'

### ISSUE THREAD

**Issue by S0uLHun43r** [fabric/fabric#1667]
centos7 64bit 1611
I use pip install fabric,then you can see it.

[root@localhost ~]# fab
Traceback (most recent call last):
  File "/bin/fab", line 7, in <module>
    from fabric.main import main
  File "/usr/lib64/python2.7/site-packages/fabric/main.py", line 20, in <module>
    from fabric import api, state, colors
  File "/usr/lib64/python2.7/site-packages/fabric/api.py", line 10, in <module>
    from fabric.context_managers import (cd, hide, settings, show, path, prefix,
  File "/usr/lib64/python2.7/site-packages/fabric/context_managers.py", line 41, in <module>
    from fabric.state import output, win32, connections, env
  File "/usr/lib64/python2.7/site-packages/fabric/state.py", line 9, in <module>
    from fabric.network import HostConnectionCache, ssh
  File "/usr/lib64/python2.7/site-packages/fabric/network.py", line 24, in <module>
    import paramiko as ssh
  File "/usr/lib/python2.7/site-packages/paramiko/__init__.py", line 31, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 38, in <module>
    from paramiko.auth_handler import AuthHandler
  File "/usr/lib/python2.7/site-packages/paramiko/auth_handler.py", line 48, in <module>
    from paramiko.ssh_gss import GSSAuth, GSS_EXCEPTIONS
  File "/usr/lib/python2.7/site-packages/paramiko/ssh_gss.py", line 54, in <module>
    GSS_EXCEPTIONS = (gssapi.GSSException,)
AttributeError: 'module' object has no attribute 'GSSException'

**Comment by bitprophet** [comment]
Make sure you're using the right gssapi module, there's two out there and we currently only support one of them! Double check the install docs :)
