### ISSUE TITLE
Crash when running tasks in parallel on windows7

### ISSUE THREAD

**Issue by brupelo** [fabric/fabric#1693]
When trying to run a fabric task on a couple of servers in parallel i get the next crash:

    (py362_32) D:\sources\personal\www\test_html>fab --user=root --hosts=192.168.0.102,192.168.0.103 start:False --parallel
    [192.168.0.102] Executing task 'start'
    [192.168.0.103] Executing task 'start'
    Traceback (most recent call last):
      File "d:\virtual_envs\py362_32\lib\site-packages\fabric\main.py", line 762, in main
        *args, **kwargs
      File "d:\virtual_envs\py362_32\lib\site-packages\fabric\tasks.py", line 410, in execute
        ran_jobs = jobs.run()
      File "d:\virtual_envs\py362_32\lib\site-packages\fabric\job_queue.py", line 138, in run
        _advance_the_queue()
      File "d:\virtual_envs\py362_32\lib\site-packages\fabric\job_queue.py", line 123, in _advance_the_queue
        job.start()
      File "d:\software\python362_32\Lib\multiprocessing\process.py", line 105, in start
        self._popen = self._Popen(self)
      File "d:\software\python362_32\Lib\multiprocessing\context.py", line 223, in _Popen
        return _default_context.get_context().Process._Popen(process_obj)
      File "d:\software\python362_32\Lib\multiprocessing\context.py", line 322, in _Popen
        return Popen(process_obj)
      File "d:\software\python362_32\Lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
        reduction.dump(process_obj, to_child)
      File "d:\software\python362_32\Lib\multiprocessing\reduction.py", line 60, in dump
        ForkingPickler(file, protocol).dump(obj)
    AttributeError: Can't pickle local object '_execute.<locals>.inner'

    (py362_32) D:\sources\personal\www\test_html>Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "d:\software\python362_32\Lib\multiprocessing\spawn.py", line 99, in spawn_main
        new_handle = reduction.steal_handle(parent_pid, pipe_handle)
      File "d:\software\python362_32\Lib\multiprocessing\reduction.py", line 82, in steal_handle
        _winapi.PROCESS_DUP_HANDLE, False, source_pid)
    OSError: [WinError 87] The parameter is incorrect

If I don't use --parallel the task will run correctly in serial, what could be the reason of this crash?

Fabric version:
    (py362_32) D:\sources\personal\www\test_html>fab --version
    Fabric3 1.13.1.post1
    Paramiko 2.4.0

**Comment by ploxiln** [comment]
Fabric 1.x implements parallel execution by forking child processes. `fork()` is a unix system call which makes a copy of the entire process (the only difference being the return value of `fork()`) but Windows does not have this system call or anything quite like it, it just has something like `spawn()`. So the python standard multiprocessing module does more "pickling" to serialize and pass objects to the child process on windows. See https://docs.python.org/2.7/library/multiprocessing.html#windows

I'm not sure if its your code, or the core fabric code, which is creating some object which is not pickle-able. But that's apparently what's happening.

**Comment by ploxiln** [comment]
this is #489 - the issue is in fabric

**Comment by brupelo** [comment]
@ploxiln Thanks for the fast response, good to know at least this has already been discussed, I'll forget about the idea of using --parallel when running my fabric scripts on windows. 

Btw, as you can see from my previous post i'm using Fabric3, which if I'm not mistaken it's some fork of this one, which is the official repo, still so, is it alright posting the issues in this one?

Btw, I wonder, why isn't this awesome project providing compatibility for both python2/3 and relying on some fork? It doesn't feel right doing `pip install fabric` or `pip instal fabric3`, more code to maintain, more repos, not centralized issues on github... don't get it :/

**Comment by ploxiln** [comment]
The maintainer wanted to wait for fabric-2.0 for adding python3 support. fabric-2.0 is currently in beta. (It also has other significant changes.)

**Comment by brupelo** [comment]
Awesome, thanks for the clarification, can't wait for fabric-2.0 to be released :)

**Comment by prakasa1904** [comment]
waiting for this, hope so.... blocking my minifier tool... create and launch 2 services just for that  T.T

**Comment by lmsb** [comment]
Please release 2.0! Need Multiprocessing to work on Windows!
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\fabric\main.py", line 757, in main
    *args, **kwargs
  File "c:\python27\lib\site-packages\fabric\tasks.py", line 411, in execute
    ran_jobs = jobs.run()
  File "c:\python27\lib\site-packages\fabric\job_queue.py", line 136, in run
    _advance_the_queue()
  File "c:\python27\lib\site-packages\fabric\job_queue.py", line 121, in _advance_the_queue
    job.start()
  File "c:\python27\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "c:\python27\lib\multiprocessing\forking.py", line 277, in __init__
    dump(process_obj, to_child, HIGHEST_PROTOCOL)
  File "c:\python27\lib\multiprocessing\forking.py", line 199, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "c:\python27\lib\pickle.py", line 224, in dump
    self.save(obj)
  File "c:\python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "c:\python27\lib\pickle.py", line 419, in save_reduce
    save(state)
  File "c:\python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "c:\python27\lib\pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "c:\python27\lib\pickle.py", line 681, in _batch_setitems
    save(v)
  File "c:\python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "c:\python27\lib\pickle.py", line 748, in save_global
    (obj, module, name))
**pickle.PicklingError: Can't pickle <function inner at 0x02F3CEF0>: it's not found as fabric.tasks.in**
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\python27\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "c:\python27\lib\multiprocessing\forking.py", line 488, in prepare
    assert main_name not in sys.modules, main_name
AssertionError: __main__

**Comment by spandhar** [comment]
fabric2.0 is released  
http://docs.fabfile.org/en/latest/upgrading.html#upgrading
