### ISSUE TITLE
upload_template TypeError: not enough arguments for format string

### ISSUE THREAD

**Issue by zhan9san** [fabric/fabric#1699]
Hi,
    When I upload a template file to remote server, if there is an extra '**%**' in the template file, it will crash.

# version

Fabric==1.14.0
Python 2.7.5
CentOS Linux release 7.3.1611 (Core)

# template file & code
```
(test) [steve@v work]$ cat tpl
hi
{{ hi }}
%(hi)s
%
(test) [steve@v work]$ cat fabfile.py
from fabric.api import env
from fabric.contrib.files import upload_template

env.host_string = '192.168.10.221'
env.user = 'steve'

def test():
    v_context = {
        'hi': 'an',
    }
    upload_template('tpl', '/tmp/tpl', context = v_context)
(test) [steve@v work]$ fab test --show=debug
Using fabfile '/home/steve/work/fabfile.py'
Commands to run: test
Parallel tasks now using pool size of 0
[192.168.10.221] run: /bin/bash -l -c "echo \"Will you echo quotation marks\""
[192.168.10.221] run: /bin/bash -l -c "test -d \"\$(echo /tmp/tpl)\""
Traceback (most recent call last):
  File "/home/steve/test/lib/python2.7/site-packages/fabric/main.py", line 757, in main
    *args, **kwargs
  File "/home/steve/test/lib/python2.7/site-packages/fabric/tasks.py", line 426, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/home/steve/test/lib/python2.7/site-packages/fabric/tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)
  File "/home/steve/work/fabfile.py", line 13, in test
    upload_template('tpl', '/tmp/tpl', context = v_context)
  File "/home/steve/test/lib/python2.7/site-packages/fabric/contrib/files.py", line 160, in upload_template
    text = text % context
TypeError: not enough arguments for format string
Disconnecting from 192.168.10.221... done.
```

**Comment by ki4070ma** [comment]
Hi @zhan9san 

I think it works as design.
If you want to use % in file to be uploaded, you can write %% instead of %.

**Comment by zhan9san** [comment]
@ki4070ma 
OK, thanks.I wrote that template file in wrong format.
