### ISSUE TITLE
Group('foo').execute('bar') : Does not work correctly

### ISSUE THREAD

**Issue by NicolasMartin69** [fabric/fabric#1712]
Hi, I try to use the execute (as in exemples) and it's not working as expected ;

```
Traceback (most recent call last):
  File "test_df.py", line 13, in <module>
    Group('itbd@depot-sgbd.sncf.fr','itbd@x64lmwbinlj.dsit.sncf.fr').execute(disk_free)
  File "build\bdist.win-amd64\egg\fabric\group.py", line 131, in execute
NotImplementedError
```

Here is my code : 

```
from fabric import Connection
from fabric import ThreadingGroup as Group

def disk_free(ctx):
	uname = ctx.run('uname -s')
	if 'Linux' in uname:
		command = "df -h / | tail -n1 | awk '{print $5}'"
		return ctx.run(command).stdout
	err = "No idea how to get disk space on {}!".format(uname)
	raise Exception(err)

Group('itbd@depot-sgbd.sncf.fr','itbd@x64lmwbinlj.dsit.sncf.fr').run('df -h')		# Work fine
Group('itbd@depot-sgbd.sncf.fr','itbd@x64lmwbinlj.dsit.sncf.fr').execute(disk_free) # Through exception
```
Version : 2.0
OS : Windows 7 
Python 2.7

**Comment by bitprophet** [comment]
Yea, `Group.get` was not implemented before 2.0, it'll come eventually! Apologies :)
