### ISSUE TITLE
Command line option --set breaks with non-string values

### ISSUE THREAD

**Issue by marthjod** [fabric/fabric#1737]
I would like to pass `ok_ret_codes` to `fabric.env` via command line, but afaics I can only pass in string type values using `--set`.

Example
```python
@task
def exit_2():
    print "env['ok_ret_codes']:", env.get('ok_ret_codes')
    run('exit 2')
```

yields, respectively (some lines omitted for brevity):
```bash
# ok
./venv/bin/fab ... exit_2 
env['ok_ret_codes']: [0]
Fatal error: run() received nonzero return code 2 while executing!
Aborting.

# not ok
./venv/bin/fab ... --set ok_ret_codes='[0,2]' exit_2 
env['ok_ret_codes']: [0
Traceback (most recent call last):
  File "/tmp/venv/lib/python2.7/site-packages/fabric/main.py", line 757, in main
    *args, **kwargs
  File "/tmp/venv/lib/python2.7/site-packages/fabric/tasks.py", line 386, in execute
    multiprocessing
  File "/tmp/venv/lib/python2.7/site-packages/fabric/tasks.py", line 276, in _execute
    return task.run(*args, **kwargs)
  File "/tmp/venv/lib/python2.7/site-packages/fabric/tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)
  File "/tmp/fabfile.py", line 10, in exit_2
    run('exit 2')
  File "/tmp/venv/lib/python2.7/site-packages/fabric/network.py", line 687, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/tmp/venv/lib/python2.7/site-packages/fabric/operations.py", line 1090, in run
    shell_escape=shell_escape, capture_buffer_size=capture_buffer_size,
  File "/tmp/venv/lib/python2.7/site-packages/fabric/operations.py", line 943, in _run_command
    if status not in env.ok_ret_codes:
TypeError: 'in <string>' requires string as left operand, not int

# below variant showed same error
./venv/bin/fab ... --set 'ok_ret_codes=[0,2]' exit_2
```

```bash
./venv/bin/fab  --version 
Fabric 1.14.0
Paramiko 2.4.1
```

Is there something I am overlooking or is passing non-string values unsupported?

**Comment by marthjod** [comment]
Update: Looking at https://github.com/fabric/fabric/blob/master/fabric/main.py#L623, this seems to be the case indeed.

**Comment by bitprophet** [comment]
Correct, this feature never got up to the "also do type-casting" stage :( but thanks for the report!

Version 2 (out by PyCon) has a significantly more fleshed out config setup and does include some limited type-casting via eg env vars (mostly driven by the current/default values of the config key being modified). See e.g. http://docs.pyinvoke.org/en/latest/concepts/configuration.html#type-casting
