### ISSUE TITLE
Error when tasks use type hints

### ISSUE THREAD

**Issue by alorence** [fabric/fabric#1746]
Hi, I play with the new fabric for a few days now. When I develop, I like to have some type hints (see [PEP 483](https://www.python.org/dev/peps/pep-0483/) and [PEP 484](https://www.python.org/dev/peps/pep-0484/)), that helps my IDE to give me information on what I can do with my task argument. In that case, it's interesting to indicate that task first argument is a `Connection` instance, so I can quickly deep into the new fabric API.

Consider this simple example:

```python
from fabric import Connection
from invoke import task

@task
def info(c: Connection):
    c.run("uname -a")
```

When I try to run this task, or try to list available tasks, I fall into this exception:

```
Traceback (most recent call last):
  File "C:\Users\john_doe\.virtualenvs\fabric2_tests-W0xbygSg\Scripts\fab-script.py", line 11, in <module>
    load_entry_point('fabric==2.0.0', 'console_scripts', 'fab')()
  File "c:\users\john_doe\.virtualenvs\fabric2_tests-w0xbygsg\lib\site-packages\invoke\program.py", line 321, in run
    self.parse_collection()
  File "c:\users\john_doe\.virtualenvs\fabric2_tests-w0xbygsg\lib\site-packages\invoke\program.py", line 399, in parse_collection
    self.load_collection()
  File "c:\users\john_doe\.virtualenvs\fabric2_tests-w0xbygsg\lib\site-packages\fabric\main.py", line 74, in load_collection
    super(Fab, self).load_collection()
  File "c:\users\john_doe\.virtualenvs\fabric2_tests-w0xbygsg\lib\site-packages\invoke\program.py", line 588, in load_collection
    module, parent = loader.load(coll_name)
  File "c:\users\john_doe\.virtualenvs\fabric2_tests-w0xbygsg\lib\site-packages\invoke\loader.py", line 75, in load
    module = imp.load_module(name, fd, path, desc)
  File "c:\users\john_doe\.virtualenvs\fabric2_tests-w0xbygsg\lib\imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "c:\users\john_doe\.virtualenvs\fabric2_tests-w0xbygsg\lib\imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\dev\playgrounds\fabric2_tests\fabfile.py", line 6, in <module>
    def info(c: Connection):
  File "c:\users\john_doe\.virtualenvs\fabric2_tests-w0xbygsg\lib\site-packages\invoke\tasks.py", line 308, in task
    return Task(args[0], **kwargs)
  File "c:\users\john_doe\.virtualenvs\fabric2_tests-w0xbygsg\lib\site-packages\invoke\tasks.py", line 75, in __init__
    self.positional = self.fill_implicit_positionals(positional)
  File "c:\users\john_doe\.virtualenvs\fabric2_tests-w0xbygsg\lib\site-packages\invoke\tasks.py", line 167, in fill_implicit_positionals
    args, spec_dict = self.argspec(self.body)
  File "c:\users\john_doe\.virtualenvs\fabric2_tests-w0xbygsg\lib\site-packages\invoke\tasks.py", line 153, in argspec
    spec = inspect.getargspec(func)
  File "C:\Python36-64\Lib\inspect.py", line 1075, in getargspec
    raise ValueError("Function has keyword-only parameters or annotations"
ValueError: Function has keyword-only parameters or annotations, use getfullargspec() API which can support them
```

Do you think it would be possible to support tasks with type hints in arguments ?

**Comment by alorence** [comment]
After digging a few more, I understand the issue should be addressed in pyinvoke/invoke. Similar issues and pull requests already exists

- pyinvoke/invoke#248
- pyinvoke/invoke#357
- pyinvoke/invoke#372
- pyinvoke/invoke#373
- pyinvoke/invoke#458
- pyinvoke/invoke#512

Hope one will be accepted soon

**Comment by TheAssassin** [comment]
Any updates on this? A year later I run into the same issue again. Removing the type hints fixes the issue, but it's just an annoying workaround...
