### ISSUE TITLE
local function is not found in config for Fabric 2.1

### ISSUE THREAD

**Issue by Mokubyow** [fabric/fabric#1789]
I recently upgraded to Fabric 2.1 and followed the [guide](http://docs.fabfile.org/en/latest/upgrading.html#the-whole-thing) to covert my fabfile over. 

I have a test task which fails when I try to use `c.local()`:

```
from invoke import task

@task
def test(c, html=False, types=False):
    test_cmd = 'pytest --cov-config .coveragerc '
    if html:
        c.local(test_cmd + ' --cov-report=html')
        c.local('open htmlcov/index.html')
    else:
        c.local(test_cmd)

    if types:
        c.local('mypy --config-file mypy.ini')
```

However the following error is always thrown:

```
Traceback (most recent call last):
  File "/Users/k/.local/share/virtualenvs/ds-jobs-VR5Cn9mm/lib/python3.6/site-packages/invoke/config.py", line 98, in __getattr__
    return self._get(key)
  File "/Users/k/.local/share/virtualenvs/ds-jobs-VR5Cn9mm/lib/python3.6/site-packages/invoke/config.py", line 165, in _get
    value = self._config[key]
  File "/Users/k/.local/share/virtualenvs/ds-jobs-VR5Cn9mm/lib/python3.6/site-packages/invoke/config.py", line 154, in __getitem__
    return self._get(key)
  File "/Users/k/.local/share/virtualenvs/ds-jobs-VR5Cn9mm/lib/python3.6/site-packages/invoke/config.py", line 165, in _get
    value = self._config[key]
KeyError: 'local'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/k/.local/share/virtualenvs/ds-jobs-VR5Cn9mm/bin/fab", line 11, in <module>
    sys.exit(program.run())
  File "/Users/k/.local/share/virtualenvs/ds-jobs-VR5Cn9mm/lib/python3.6/site-packages/invoke/program.py", line 332, in run
    self.execute()
  File "/Users/k/.local/share/virtualenvs/ds-jobs-VR5Cn9mm/lib/python3.6/site-packages/invoke/program.py", line 480, in execute
    executor.execute(*self.tasks)
  File "/Users/k/.local/share/virtualenvs/ds-jobs-VR5Cn9mm/lib/python3.6/site-packages/invoke/executor.py", line 133, in execute
    result = call.task(*args, **call.kwargs)
  File "/Users/k/.local/share/virtualenvs/ds-jobs-VR5Cn9mm/lib/python3.6/site-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/Users/k/dev/ds-jobs/fabfile.py", line 46, in test
    c.local('python scripts/bootstrap_db.py')
  File "/Users/k/.local/share/virtualenvs/ds-jobs-VR5Cn9mm/lib/python3.6/site-packages/invoke/config.py", line 110, in __getattr__
    raise AttributeError(err)
AttributeError: No attribute or config key found for 'local'

Valid keys: ['connect_kwargs', 'forward_agent', 'gateway', 'load_ssh_configs', 'port', 'run', 'runners', 'ssh_config_path', 'sudo', 'tasks', 'timeouts', 'user']

Valid real attributes: ['cd', 'clear', 'config', 'cwd', 'from_data', 'pop', 'popitem', 'prefix', 'run', 'setdefault', 'sudo', 'update']
```

Anyone know what is going on here are the docs wrong, is my code wrong?

**Comment by elmcrest** [comment]
same for me, easy reproduceble:

```
  from fabric import Connection
  from invoke import task

  c = Connection("localhost")


  @task
  def reproduce_error(c):
      c.local("ls")
```
resulting in the same `KeyError: 'local'` and btw it doesn't matter if I initiate the Conection object with a real connection.

**Comment by mirobeka** [comment]
Hi, I can replicate this as well.

my `fabfile.py`
```python
from invoke import task

@task
def local_task(c):
  c.local("touch test_file.txt")
```

Command `fab local-task` produced:
```Traceback (most recent call last):
  File "/home/vagrant/foo/lib/python3.6/site-packages/invoke/config.py", line 98, in __getattr__
    return self._get(key)
  File "/home/vagrant/foo/lib/python3.6/site-packages/invoke/config.py", line 165, in _get
    value = self._config[key]
  File "/home/vagrant/foo/lib/python3.6/site-packages/invoke/config.py", line 154, in __getitem__
    return self._get(key)
  File "/home/vagrant/foo/lib/python3.6/site-packages/invoke/config.py", line 165, in _get
    value = self._config[key]
KeyError: 'local'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/foo/bin/fab", line 11, in <module>
    sys.exit(program.run())
  File "/home/vagrant/foo/lib/python3.6/site-packages/invoke/program.py", line 332, in run
    self.execute()
  File "/home/vagrant/foo/lib/python3.6/site-packages/invoke/program.py", line 480, in execute
    executor.execute(*self.tasks)
  File "/home/vagrant/foo/lib/python3.6/site-packages/invoke/executor.py", line 133, in execute
    result = call.task(*args, **call.kwargs)
  File "/home/vagrant/foo/lib/python3.6/site-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/home/vagrant/fabfile.py", line 5, in local_task
    c.local("touch test_file.txt")
  File "/home/vagrant/foo/lib/python3.6/site-packages/invoke/config.py", line 110, in __getattr__
    raise AttributeError(err)
AttributeError: No attribute or config key found for 'local'

Valid keys: ['connect_kwargs', 'forward_agent', 'gateway', 'load_ssh_configs', 'port', 'run', 'runners', 'ssh_config_path', 'sudo', 'tasks', 'timeouts', 'user']

Valid real attributes: ['cd', 'clear', 'config', 'cwd', 'from_data', 'pop', 'popitem', 'prefix', 'run', 'setdefault', 'sudo', 'update']
```

Libraries:
```
asn1crypto==0.24.0
bcrypt==3.1.4
cffi==1.11.5
cryptography==2.2.2
fabric==2.1.3
idna==2.6
invoke==1.0.0
paramiko==2.4.1
pyasn1==0.4.3
pycparser==2.18
PyNaCl==1.2.1
six==1.11.0
```
my **OS** is `Linux ubuntu-xenial 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

Cheers,
Miro

**Comment by ploxiln** [comment]
If you do not specify a host to run the task against, then it runs like a plain `invoke` task, which only has `run()` to run commands locally. You need to do `fab -H somehost task` for the task context to be a Connection with a `.local()` method.

@elmcrest the line `c = Connection("localhost")` at the top level of the fabfile does not work to make it the argument to the tasks

**Comment by elmcrest** [comment]
ok, thx for the clarification. ticket could be closed from my perspecitve...

**Comment by tankeryang** [comment]
if you want to `fab` on local machine, may be you just have to code in fabfile like this:
```python fabfile.py
from fabric import Connection
from invoke import task

@task
def execute(conn):
    conn.run("uname -s")
```
then `fab execute`

else if you want to `fab` to remote machine, you can code your fabfile like this:
```python
from fabric import Connection
from invoke import task

# you have to add your id_rsa.pub into your remote machine's ${path to .ssh dir}/authorized_keys file
conn_rmt = Connection("${remote host}", user='${remote user}', connect_kwargs={'key_filename': '${path to local .ssh dir}/${your id_rsa file}'})

# or you can provide password on connect_kwargs
conn_rmt_pw = Connection("${remote host}", user='${remote user}', connect_kwargs={'password': 'remote user's password'})

@task
def execute(conn):
    # ignore conn
    conn_rmt.run("uname -s")
    conn_rmt_pw.run("uname -s")
```
then `fab execute`

**Comment by rryan** [comment]
Hm, can I request that you revisit this decision?

IMHO this leads to flaky fabfiles, because they depend on whether an optional command-line argument was specified. A common use case for my projects is to do a blend of local automation (invoke-style work) and remote work (fabric style work) in one fabfile. 

For the local automation tasks, a remote host may not be specified, but if it is specified via command-line flag, I don't want those local automation tasks to run on the remote host. This means my users are going to complain the script is broken when they forget to specify a remote host, but they are only doing local automation tasks. In this situation, I want to use `Connection.local` to be sure the local tasks always run locally. But this makes the fabfile not work when no host is specified.

From the example of [my project's](https://mixxx.org) user manual:
https://github.com/mixxxdj/manual/blob/manual-2.2.x/fabfile.py
```
# Build the manual locally. User inspects the build and makes changes as needed. 
fab clean html pdf
# Clean/re-build, and deploy. Only project maintainers and CI/CD jobs do this.
fab publish
```

Am I going about this the wrong way?

**Comment by MRigal** [comment]
The biggest problem I see here is that the upgrading tutorial brings you to this problem: http://www.fabfile.org/upgrading.html#the-whole-thing

Maybe it should be rewritten to use `c.run()` instead of `c.local()`
