### ISSUE TITLE
paramiko.ssh_exception.AuthenticationException: Authentication failed.

### ISSUE THREAD

**Issue by sugizo** [fabric/fabric#1796]
```
$ pip install fabric
$ uname && python -V | fab --version 
Darwin
Python 2.7.15 :: Anaconda, Inc.
Fabric 2.1.3
Paramiko 2.4.1
Invoke 1.0.0
$ cat fabfile.py 
from fabric import Connection
from invoke import task
c = Connection(host='127.0.0.1')
@task
def test(c):
    c.run('uname')
$ fab -f ./fabfile.py -H 127.0.0.1 test
Traceback (most recent call last):
  File "/Users/MacBookPro/miniconda3/envs/python2_test/bin/fab", line 11, in <module>
    sys.exit(program.run())
  File "/Users/MacBookPro/miniconda3/envs/python2_test/lib/python2.7/site-packages/invoke/program.py", line 332, in run
    self.execute()
  File "/Users/MacBookPro/miniconda3/envs/python2_test/lib/python2.7/site-packages/invoke/program.py", line 480, in execute
    executor.execute(*self.tasks)
  File "/Users/MacBookPro/miniconda3/envs/python2_test/lib/python2.7/site-packages/invoke/executor.py", line 133, in execute
    result = call.task(*args, **call.kwargs)
  File "/Users/MacBookPro/miniconda3/envs/python2_test/lib/python2.7/site-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/Users/MacBookPro/Downloads/learn/fabric/fabfile.py", line 6, in test
    c.run('uname')
  File "<decorator-gen-3>", line 2, in run
  File "/Users/MacBookPro/miniconda3/envs/python2_test/lib/python2.7/site-packages/fabric/connection.py", line 29, in opens
    self.open()
  File "/Users/MacBookPro/miniconda3/envs/python2_test/lib/python2.7/site-packages/fabric/connection.py", line 501, in open
    self.client.connect(**kwargs)
  File "/Users/MacBookPro/miniconda3/envs/python2_test/lib/python2.7/site-packages/paramiko/client.py", line 424, in connect
    passphrase,
  File "/Users/MacBookPro/miniconda3/envs/python2_test/lib/python2.7/site-packages/paramiko/client.py", line 714, in _auth
    raise saved_exception
paramiko.ssh_exception.AuthenticationException: Authentication failed.
```
any idea? thx

**Comment by ploxiln** [comment]
by the way, the line `c = Connection(host='127.0.0.1')` does not do anything in that context

what happens if you run `ssh 127.0.0.1 uname` ?

**Comment by ploxiln** [comment]
(is password needed?)

**Comment by sugizo** [comment]
yes password needed, tested in terminal
```
$ ssh 127.0.0.1 uname
Password:
Darwin
```
so what is the correct way? 
btw, i had fabfile that running well using fabric 1 that still use `fabric.api`, tested fabric 2, then face this problem
any hints? thx

**Comment by ploxiln** [comment]
You'll want to do `fab --prompt-for-login-password -H 127.0.0.1 test`
http://docs.fabfile.org/en/latest/cli.html#cmdoption-prompt-for-login-password

**Comment by sugizo** [comment]
```
$ cat fabfile.py 
from fabric import SerialGroup as Group
def upload_and_unpack(c):
    if c.run('test -f /opt/mydata/myfile', warn=True).failed:
        c.put('myfiles.tgz', '/opt/mydata')
        c.run('tar -C /opt/mydata -xzvf /opt/mydata/myfiles.tgz')
for connection in Group('localhost'):
    upload_and_unpack(connection)
$ fab -f ./fabfile.py --prompt-for-login-password -H 127.0.0.1
Traceback (most recent call last):
  File "/Users/MacBookPro/miniconda3/envs/python2_test/bin/fab", line 11, in <module>
    sys.exit(program.run())
  File "/Users/MacBookPro/miniconda3/envs/python2_test/lib/python2.7/site-packages/invoke/program.py", line 321, in run
    self.parse_collection()
  File "/Users/MacBookPro/miniconda3/envs/python2_test/lib/python2.7/site-packages/invoke/program.py", line 399, in parse_collection
    self.load_collection()
  File "/Users/MacBookPro/miniconda3/envs/python2_test/lib/python2.7/site-packages/fabric/main.py", line 75, in load_collection
    super(Fab, self).load_collection()
  File "/Users/MacBookPro/miniconda3/envs/python2_test/lib/python2.7/site-packages/invoke/program.py", line 588, in load_collection
    module, parent = loader.load(coll_name)
  File "/Users/MacBookPro/miniconda3/envs/python2_test/lib/python2.7/site-packages/invoke/loader.py", line 75, in load
    module = imp.load_module(name, fd, path, desc)
  File "/Users/MacBookPro/Downloads/learn/fabric/fabfile.py", line 7, in <module>
    upload_and_unpack(connection)
  File "/Users/MacBookPro/Downloads/learn/fabric/fabfile.py", line 3, in upload_and_unpack
    if c.run('test -f /opt/mydata/myfile', warn=True).failed:
  File "<decorator-gen-3>", line 2, in run
  File "/Users/MacBookPro/miniconda3/envs/python2_test/lib/python2.7/site-packages/fabric/connection.py", line 29, in opens
    self.open()
  File "/Users/MacBookPro/miniconda3/envs/python2_test/lib/python2.7/site-packages/fabric/connection.py", line 501, in open
    self.client.connect(**kwargs)
  File "/Users/MacBookPro/miniconda3/envs/python2_test/lib/python2.7/site-packages/paramiko/client.py", line 424, in connect
    passphrase,
  File "/Users/MacBookPro/miniconda3/envs/python2_test/lib/python2.7/site-packages/paramiko/client.py", line 714, in _auth
    raise saved_exception
paramiko.ssh_exception.AuthenticationException: Authentication failed.
```
previous code is work, thx
not sure how authentication work, test with the code provide in fabfile docs return the same error.
any idea? thx

**Comment by ploxiln** [comment]
That fabfile.py is more of a plain python script using fabric as a library - you could run it with just `python fabfile.py`. When you run `fab` it ends up running your function at import time, rather than intentionally as a task, so that fab command-line option does not really apply.

If you want to run as a script using a library, you could add the prompt yourself using https://docs.python.org/2.7/library/getpass.html and then when you create the fabric Connection or Group or whatever, specify `connect_kwargs={'password': yourpassvar}` or something like that.

**Comment by rajatrj16** [comment]
I have added the authorizes_keys file in guest server still it is not accessible and says this^^error.
My host machine can directly access to the server without any password but still it fails.
Help?
