### ISSUE TITLE
local command no longer exists

### ISSUE THREAD

**Issue by C01DER** [fabric/fabric#1867]
Following code is from upgrade 1.x document, but it can't be run.

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/invoke/config.py", line 113, in __getattr__
    return self._get(key)
  File "/usr/lib/python3.4/site-packages/invoke/config.py", line 178, in _get
    value = self._config[key]
  File "/usr/lib/python3.4/site-packages/invoke/config.py", line 169, in __getitem__
    return self._get(key)
  File "/usr/lib/python3.4/site-packages/invoke/config.py", line 178, in _get
    value = self._config[key]
KeyError: 'local'

```
from invoke import Exit
from invocations.console import confirm

from fabric import task

my_hosts = ["my-server"]

@task
def test(c):
    result = c.local("./manage.py test my_app", warn=True)
    if not result and not confirm("Tests failed. Continue anyway?"):
        raise Exit("Aborting at user request.")

@task
def commit(c):
    c.local("git add -p && git commit")

@task
def push(c):
    c.local("git push")

@task
def prepare_deploy(c):
    test(c)
    commit(c)
    push(c)

@task(hosts=my_hosts)
def deploy(c):
    code_dir = "/srv/django/myproject"
    if not c.run("test -d {}".format(code_dir), warn=True):
        cmd = "git clone user@vcshost:/path/to/repo/.git {}"
        c.run(cmd.format(code_dir))
    c.run("cd {} && git pull".format(code_dir))
    c.run("cd {} && touch app.wsgi".format(code_dir))
```

**Comment by C01DER** [comment]
I found that, you have to give "-H host" even you want to run task which only runs local command.

**Comment by C01DER** [comment]
More information:

If you don't give -H, the c is class Context(invoke.config.DataProxy).
After you give -H, the c is class Connection.

That's the root cause.

**Comment by rpkilby** [comment]
This has been discussed further in #1858
