### ISSUE TITLE
fabric2, error in sudo command with pipe and string "INFO"

### ISSUE THREAD

**Issue by youattd** [fabric/fabric#1873]
### 

When called from Connection.sudo like this:

```
rslt = myconnection.sudo(mycmd, pty=True, hide='both')
```

these commands all fail.  The presence of the string `INFO` in the pipe destination (literal or not) seems to cause the failure.

```
#mycmd = "bash -c '/bin/grep 2018-09-04 " + LOG_FILE + " | /bin/grep -E -i -v -e ERROR: -e info:'"  # fails (note -i)
#mycmd = "bash -c '/bin/grep 2018-09-04 " + LOG_FILE + " | /bin/grep -E -v -e INFO:'"  # fails
#mycmd = "bash -c '/bin/grep 2018-09-04 " + LOG_FILE + " | /bin/grep -v INFO:'"  # fails
mycmd = "bash -c '/bin/grep 2018-09-04 " + LOG_FILE + " | /bin/grep -v INFO'"  # fails
```

With this error and traceback:

```
Traceback (most recent call last):
  File "./fab-info-bug.py", line 29, in <module>
    rslt = c.sudo(mycmd, pty=True, hide='both')
  File "<decorator-gen-4>", line 2, in sudo
  File "/usr/local/lib/python2.7/site-packages/fabric/connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/fabric/connection.py", line 642, in sudo
    return self._sudo(self._remote_runner(), command, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/invoke/context.py", line 212, in _sudo
    return runner.run(cmd_str, watchers=watchers, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/invoke/runners.py", line 271, in run
    return self._run_body(command, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/invoke/runners.py", line 404, in _run_body
    raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: "sudo -S -p '[sudo] password: ' -H -u postgres bash -c '/bin/grep 2018-09-04 your-remote-log-file | /bin/grep -v INFO'"

Exit code: 1

Stdout:

[sudo] password: 

Stderr: n/a (PTYs have no stderr)
```

These (below) succeed.

```
#mycmd = "bash -c '/bin/grep -c INFO: " + LOG_FILE + "'"  # works
#mycmd = "bash -c '/bin/grep 2018-09-04 " + LOG_FILE + " | /bin/grep -E -v -e ERROR: -e info:'"  # works
#mycmd = "bash -c '/bin/grep 2018-09-04 " + LOG_FILE + " | /bin/grep -v WARN:'"  # works
```
Test program (using python 2.7 on Mac OS.  remote host is Amazon LInux):

```
#!/usr/bin/env python

from __future__ import print_function
import os
from fabric import Connection, Config


SUDO_PASS = 'yoursudopwd'
SUDO_USER = 'yoursudouser'
LOG_FILE = "log-file-on-remote-server"

config = Config(overrides={'sudo': {'password': SUDO_PASS, 'user': SUDO_USER}})

c = Connection('yourhostname', user="yoursshuser", config=config)
c.connect_kwargs["key_filename"] = os.path.expandvars("$HOME/.ssh/Support")
c.connect_kwargs["passphrase"] = "yoursshpassphrase"
c.load_ssh_configs = False

#mycmd = "bash -c '/bin/grep 2018-09-04 " + LOG_FILE + " | /bin/grep -E -i -v -e ERROR: -e info:'"  # fails (note -i)
#mycmd = "bash -c '/bin/grep 2018-09-04 " + LOG_FILE + " | /bin/grep -E -v -e INFO:'"  # fails
#mycmd = "bash -c '/bin/grep 2018-09-04 " + LOG_FILE + " | /bin/grep -v INFO:'"  # fails
mycmd = "bash -c '/bin/grep 2018-09-04 " + LOG_FILE + " | /bin/grep -v INFO'"  # fails

#mycmd = "bash -c '/bin/grep -c INFO: " + LOG_FILE + "'"  # works, no pipe

#mycmd = "bash -c '/bin/grep 2018-09-04 " + LOG_FILE + " | /bin/grep -E -v -e ERROR: -e info:'"  # works, lowercase "info" is ok.
#mycmd = "bash -c '/bin/grep 2018-09-04 " + LOG_FILE + " | /bin/grep -v WARN:'"  # works

rslt = c.sudo(mycmd, pty=True, hide='both')
```

**Comment by ploxiln** [comment]
The environment variables `LANG` and `LC_ALL` can affect how grep does case-insensitive matches. That's the only thing possibly fabric related that I can think of which might be affecting your grep commands.

Note that `grep -v` means "inverse" (not "verbose"). So if _all_ lines include "INFO:", then `grep -v INFO` will match _zero_ lines and will exit with an error code, while `grep -v -e ERROR: -e info:` will match all lines (because the expressions do not match, then `-v` inverts aka reverses that).

**Comment by youattd** [comment]
Thanks Pierce.
I'm aware that "-v" inverts the search and does not mean verbose.
Will RTFM for handling non-zero bash return codes.

**Comment by ploxiln** [comment]
Ah, I see. You can add "`|| true`" to the end of the shell command string to make sure it does not return error.

**Comment by youattd** [comment]
Thank you.  Will do that.

**Comment by youattd** [comment]
Appending "|| true" works.  Reminding myself of operator precedence in bash, but I think this works.

Please resolve/close this issue and thank you for the help.

**Comment by youattd** [comment]
Closing.
