### ISSUE TITLE
UnicodeEncodeError: 'gbk' codec can't encode character u'\ufffd' in position 395: illegal multibyte sequence

### ISSUE THREAD

**Issue by pedoc** [fabric/fabric#1941]
execute below statment
`conn.run('cat ~/.ssh/authorized_keys',hide="stderr")`
throw a new exception,detail:

```
Saw 1 exceptions within threads (UnicodeEncodeError):


Thread args: {'kwargs': {'buffer_': [],
            'hide': False,
            'output': <open file '<stdout>', mode 'w' at 0x000000000344B0C0>},
 'target': <bound method Remote.handle_stdout of <fabric.runners.Remote object at 0x0000000007BDBC18>>}

Traceback (most recent call last):

  File "D:\Env\conda\Miniconda2\lib\site-packages\invoke\util.py", line 233, in run
    super(ExceptionHandlingThread, self).run()

  File "D:\Env\conda\Miniconda2\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)

  File "D:\Env\conda\Miniconda2\lib\site-packages\invoke\runners.py", line 564, in handle_stdout
    buffer_, hide, output, reader=self.read_proc_stdout

  File "D:\Env\conda\Miniconda2\lib\site-packages\invoke\runners.py", line 537, in _handle_output
    self.write_our_output(stream=output, string=data)

  File "D:\Env\conda\Miniconda2\lib\site-packages\invoke\runners.py", line 525, in write_our_output
    stream.write(encode_output(string, self.encoding))

  File "D:\Env\conda\Miniconda2\lib\site-packages\invoke\util.py", line 159, in encode_output
    string = string.encode(encoding)

UnicodeEncodeError: 'gbk' codec can't encode character u'\ufffd' in position 395: illegal multibyte sequence
```

env:
windows 10 x64
python 2.7.15
fabric 2.4

**Comment by pedoc** [comment]
snapshot
![image](https://user-images.githubusercontent.com/6604230/51839575-8c4b3c80-2344-11e9-95bd-a6b4336e7410.png)

**Comment by honglei** [comment]
```
conn.run('cat ~/.ssh/authorized_keys',hide="stderr", encoding='utf-8')
```
