### ISSUE TITLE
Sudo su - user

### ISSUE THREAD

**Issue by jibhas** [fabric/fabric#1946]
This issue has been mentioned before but with no solution.

Is there a way to do something similar to the following?

`$ ssh myuser@remote-server 
password:

[myuser@remote-server ~]$ sudo su - dev_user
[dev_user@remote-server ~]$ whoami
dev_user`

I'd like to add that the user myuser has enough permission to do sudo su - dev_user, but it does not have permission to do a command like sudo su -c whoami dev_user.

Editing the sudoers file is not an option.

I tried so many different codes but one way or another they all ended up with the error

"user myuser is not allowed to execute '/bin/whoami' as dev_user on dev-server."

The remote server I'm using is Linux RH 7.6
fab -V
Fabric 2.4.0
Paramiko 2.4.2
Invoke 1.2.0

**Comment by ploxiln** [comment]
Try this:

```
c.run("echo whoami | sudo su - dev_user")
```

**Comment by jibhas** [comment]
That one is limited, I can't use it to execute a command that does more just show something. Try changing directory with that, or execute a shell script with it.

**Comment by ploxiln** [comment]
It is merely the kernel of a rather un-limited idea :)
Try something like this:

```
c.run("echo 'cd ~/.ssh && ls -la' | sudo su - dev_user")
```

or maybe like this:

```
c.run("cat myscript.sh | sudo su - dev_user")
```

**Comment by jibhas** [comment]
I take my words back sir. This actually works.

Thank you.

**Comment by jibhas** [comment]
How would I execute c.get and c.put call?

**Comment by ploxiln** [comment]
There is no way for `c.get()` and `c.put()` to be used conveniently with your particular sudo limitations.

For `put()` you would have to first put to a directory that "myuser" can write to and "dev_user" can read from, then copy that temp file to the final destination with the "dev_user" shell trick, then delete  the temp file as "myuser".

For `get()` you would have to copy to a directory that "myuser" can read from and "dev_user" can write to, using the "dev_user" shell trick, then `get()` that temp file and then delete it as "myuser".

**Comment by dbsxdbsx** [comment]
@ploxiln ,I got  a similar question.  I need to  login as oracle  and then go to a directory use specific cmd:`expdp` with fabric2.  But the below code failed, do you know how to fix?
```
   c = Connection(host[0], port=host[3], user=host[1],
                   #    connect_timeout=300,
                   connect_kwargs={'password': host[2]})# root 
    print(f"connect {machine_short_name} ok")
    # c.run("sudo su - oracle")
    # c.sudo("su - oracle")
    remote_path = '/home/u01/expdp/'  
    with c.cd(remote_path):
        c.run('mkdir test')
        # print(c.run("sudo su - oracle"))
        print(f"enter {remote_path}")
        # c.run('ls')
        # c.run('rm -rf *')c.run()
        print(c.run('ls | sudo su - oracle')) # as it already failed,  I didn't test other cmd
```

**Comment by ploxiln** [comment]
I think that with fabric2, `with c.cd()` does not mix with `c.sudo()` or other more complicated `c.run()` commands (see #1862 )

I think this is the simplest way to do what you want:

```
c.run("echo 'cd /home/u01/expdb/ && ls' | sudo su - oracle")
```

or maybe in your case something like this would work:

```
with_su_cd = "sudo su - oracle -c 'cd /home/u01/expdp/ && %s'"
c.run(with_su_cd % 'ls')
c.run(with_su_cd % 'rm -rf *')
```

**Comment by dbsxdbsx** [comment]
The  first way is not workable when writing like: `c.run("echo 'cd /home/u01/expdb/ && ls && impdp' | sudo su - oracle")` with error :"Stdout: already printed". 
But  the 2ed way like this
```
 with_su_cd = "sudo su - oracle -c 'cd /home/u01/expdp/ && %s'"
 c.run(with_su_cd % 'ls')
 c.run(with_su_cd % 'impdp')
```
 is feasible. Thanks.

**Comment by dbsxdbsx** [comment]
Hi, @ploxiln , just one more question with oracle command. I would take oracle cmd like:
```
expdp userid=myname/password directory=my_dir parallel=40 include=TABLE_data:\" in \(select PARTITION_NAME from tpartition where to_date\(dbms_lob.substr\(high_value,11,11\),\'yyyy-mm-dd\'\) \> to_date\(\'2020-01-01\',\'yyyy-mm-dd\'\) \)\" query=\"where fdatetime\>to_date\(to_char\(sysdate-1,\'yyyymmdd\'\)\|\|\' 16\',\'yyyymmdd hh24\'\)\" dumpfile=all$(date +%Y%m%d)_%U.dmp version=11.2.0.4;   
```
in cmd, which works.   
But... when I input it with fabric in python, I am frustrated with correcting syntax of the command above.  I tried to remove all escape chars or use raw string like r"..." or add "\" somewhere,  just not working.  

Any idea?

**Comment by ploxiln** [comment]
That is going to be a bit tricky, because you have to consider the python string, going into the shell which parses `sudo sh -c '...'`, and then the shell which parses what is inside the '...' - but it probably possible :)

So when we substitute into this:

```
with_su_cd = "sudo su - oracle -c 'cd /home/u01/expdp/ && %s'"
```

the string we substitute in ends up inside single-quotes in the outer shell. By the way, for a single-quoted string in the shell, you can't escape a single-quote, because the backslash is literal, not escape. You can't put a single quote in a single-quote string in the shell. But you can do this with double quotes. So we'll use a "raw" python string that preserves backslash, to construct a command that uses only double quotes, and can use backslash which is only interpreted by the  innermost shell. (Also, do not escape the parentheses, because they are already inside a double-quote string in the shell).

```python
cmd = r'expdp userid=myname/password directory=my_dir parallel=40'
cmd += r' include=TABLE_data:" in (select PARTITION_NAME from tpartition where to_date(dbms_lob.substr(high_value,11,11), \"yyyy-mm-dd\") > to_date(\"2020-01-01\", \"yyyy-mm-dd\") )"'
cmd += r' query="where fdatetime > to_date(to_char(sysdate-1,\"yyyymmdd\") || \" 16\", \"yyyymmdd hh24\")"'
cmd += r' dumpfile=all$(date +%Y%m%d)_%U.dmp version=11.2.0.4;'
```

```python
c.run(with_su_cd % cmd)
```

good luck :)

**Comment by dbsxdbsx** [comment]
@ploxiln , thanks again, and just like what I said, " it is quite tricky~" After testing it the whole afternoon, I failed totally.
```
cmd = r'expdp userid=myname/password parallel=40 directory=my_dir '  # ok
    # cmd += r' include=TABLE_data:" in (select PARTITION_NAME from tpartition ) "'  # ok without \( and \"
    cmd += r""" include=TABLE_data:" in (select PARTITION_NAME from tpartition )" """  # ok with triple quotes and without \( and \"
    # cmd += r" include=TABLE_data:\" in \(select PARTITION_NAME from tpartition \) \""  # ok with \( and \"
    # cmd += r" include=TABLE_data:\" in \(select PARTITION_NAME from tpartition \)  where to_date\(dbms_lob.substr\(high_value,11,11\), \'yyyy-mm-dd\') \> to_date\(\'2020-01-01\', \'yyyy-mm-dd\'\) \)\"" # wrong
    # cmd += r' include=TABLE_data:" in (select PARTITION_NAME from tpartition where to_date(dbms_lob.substr(high_value,11,11), \'yyyy-mm-dd\') > to_date(\'2020-01-01\', \'yyyy-mm-dd\'))"'  #wrong
    # cmd += ' include=TABLE_data:" in (select PARTITION_NAME from tpartition where to_date(dbms_lob.substr(high_value,11,11), \'yyyy-mm-dd\') > to_date(\'2020-01-01\', \'yyyy-mm-dd\'))"' #still wrong

    # cmd += r""" query="where fdatetime > to_date(to_char(sysdate-1,'yyyymmdd') || ' 16', 'yyyymmdd hh24')" """ # wrong without escape char
    # cmd += r""" query=\"where fdatetime \> to_date\(to_char\(sysdate-1,\'yyyymmdd\'\) \|\| \' 16\', \'yyyymmdd hh24\'\)\" """#wrong with escape char
    # cmd += r""" query="where fdatetime \> to_date\(to_char\(sysdate-1,\'yyyymmdd\'\) \|\| \' 16\', \'yyyymmdd hh24\'\)" """  #wrong with escape char only inside double quotes
    # cmd += r""" query="where fdatetime > to_date(to_char(sysdate-1,\'yyyymmdd\') || \' 16\', \'yyyymmdd hh24\')" """  # wrong with some escape char only with \' inside
    # cmd += r""" query="where fdatetime > to_date(to_char(sysdate-1,\'yyyymmdd\') \|\| \' 16\', \'yyyymmdd hh24\')" """  # wrong with only \' and \|
    # cmd += r""" query="where fdatetime > to_date(to_char(sysdate-1,'yyyymmdd') \|\| ' 16', 'yyyymmdd hh24')" """  # wrong with only and \|
    # cmd += r""" query="where fdatetime \> to_date(to_char(sysdate-1,'yyyymmdd') \|\| ' 16', 'yyyymmdd hh24')" """  # wrong with only \> and \|
    # cmd += r""" query="where fdatetime \> to_date(to_char(sysdate-1,\'yyyymmdd\') \|\| \' 16\', \'yyyymmdd hh24\')" """  # wrong with only \> and \| and \'
    # cmd += r""" query="where fdatetime \> to_date(to_char(sysdate-1,\'yyyymmdd\') || \' 16\', \'yyyymmdd hh24\')" """ #wrong
    # cmd += r""" query="where fdatetime > to_date(to_char(sysdate-1,\'yyyymmdd\') || \' 16\', \'yyyymmdd hh24\')" """  #wrong
    # cmd += """ query="where fdatetime > to_date(20200101)" """  # ok
    # cmd += """ query="where fdatetime > to_date('20200101')" """  # ok
    # cmd += """ query="where fdatetime > to_date(to_char(sysdate-1,\'yyyymmdd\')" """ # wrong
    # cmd += """ query="where fdatetime > to_date(to_char(sysdate-1,'yyyymmdd')" """  # wrong
    # cmd += """ query="where fdatetime > to_date(to_char(sysdate-1,yyyymmdd)" """ #wrong
    # cmd += """ query="where fdatetime > to_date(to_char(sysdate-1,"yyyymmdd")" """ #wrong
    # cmd += """ query="where fdatetime > sysdate-1" """ # ok
    # cmd += """ query="where fdatetime > to_date(to_char(sysdate-1,\\'yyyymmdd\\')" """ #wrong
    # cmd += """ query="where fdatetime > to_date(to_char(sysdate-1,\\\'yyyymmdd\\\')" """ #wrong
    # cmd += r""" query="where fdatetime > to_date(to_char(sysdate-1,\'yyyymmdd\')" """ #wrong
    cmd += r""" query="where fdatetime > to_date(to_char(sysdate-1,'yyyymmdd')" """ # wrong

    cmd += r' dumpfile=all$(date +%Y%m%d)_%U.dmp version=11.2.0.4;'  # ok
```
I don't know whether this is a problem about python string or with fabric.  Anyway, I got a similiar issue this the below command when try deleteing everything except for a certain file, which maybe easier to solve:
```
# c.run(with_su_cd % "rm -rf *") # ok
    # c.run(with_su_cd % 'rm -rf alltday.zip') #ok
    # c.run(with_su_cd % 'rm -rf !alltday.zip')  #wrong
    # c.run(with_su_cd % 'rm -rf !(alltday.zip)')  # wrong
    # c.run(with_su_cd % 'rm -rf !(alltday.zip)', shell=False)  # wrong
    # c.run(with_su_cd % 'rm -rf !\(alltday.zip\)', shell=False)  # wrong
    # c.run(with_su_cd % 'rm -rf !\(alltday.zip\)')  # not wrong ,but no effect
    # c.run(with_su_cd % 'rm -rf !\\(alltday.zip\\)')  # not wrong ,but no effect
    c.run(with_su_cd % "ls")
```

**Comment by Tejasweeni** [comment]
Hi, @ploxiln ,
I used same code as explained by you ,but i am getting error.I am able to connect to server and run commands like 'pwd' or 'cp' or 'cd' . But i want to run few commands only by pin10 user , so tried below sample code but no luck.Can you please help me to understand what is going wrong with these commands.

Code:
with_su_cd = "sudo su - pin10 -c 'cd /tmp/test/ && %s'"
c.run(with_su_cd % 'pwd')

error- 
bash: sudo: command not found
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    c.run(with_su_cd % 'pwd')
  File "<decorator-gen-3>", line 2, in run
  File "C:\ProgramData\Anaconda3\lib\site-packages\fabric\connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\fabric\connection.py", line 721, in run
    return self._run(self._remote_runner(), command, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\invoke\context.py", line 101, in _run
    return runner.run(command, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\invoke\runners.py", line 363, in run
    return self._run_body(command, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\invoke\runners.py", line 422, in _run_body
    return self.make_promise() if self._asynchronous else self._finish()
  File "C:\ProgramData\Anaconda3\lib\site-packages\invoke\runners.py", line 489, in _finish
    raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: "sudo su - pin10 -c 'cd /tmp/test/ && pwd'"

Exit code: 127

Stdout: already printed

Stderr: already printed

**Comment by ploxiln** [comment]
```
cmd += r""" query="where fdatetime > to_date(to_char(sysdate-1,'yyyymmdd')" """ # wrong
```

Indeed, you cannot use single quotes inside the string, because we used them to delimit the overall command string in `with_su_cmd` (but you can use single quotes around the whole string). So you need to use double-quotes again, and escape them however is appropriate for your database client, maybe something like this:

```
cmd += r' query="where fdatetime > to_date(to_char(sysdate - 1, \"yyyymmdd\")" '
```

-------

> `c.run(with_su_cd % 'rm -rf !alltday.zip')  #wrong`

yeah, that's not a feature of `rm` nor of shell expansion. You could try something like:

```
c.run(with_su_cd % 'find . -depth 1 -not -name alltday.zip -exec rm -rf "{}" ";" ') 
```
-------

> Stdout: already printed
> Stdout: already printed

I don't know what causes that, it may be a different problem.
