### ISSUE TITLE
pre-task ingores hosts and executes on localhost

### ISSUE THREAD

**Issue by slippers** [fabric/fabric#1968]
tasks which use the pre-task ignore the -H and execute on local host.
`fab -H 'somehost' whoami2`

using pre-task @task(whoami1) fails when attempting to execute whoami1 
with local host context.

`fab -H 'somehost' whoami1`
task executes on remote host

`fab -H 'somehost' whoami3`
task whoami1 and whoami3 execute on remote host.
calling whoami1 inside function body.

declared sudo password in fabric.yaml

fabfile.py
```
from invoke import task

@task
def whoami1(ctx):
    print('task whoami1')
    ctx.run('hostname')
    ctx.run('whoami')
    ctx.sudo('whoami')

@task(whoami1)
def whoami2(ctx):
    print('task whoami2')
    ctx.run('hostname')
    ctx.run('whoami')
    ctx.sudo('whoami')

@task
def whoami3(ctx):
    print('task whoami3')
    whoami1(ctx)
    ctx.run('hostname')
    ctx.run('whoami')
    ctx.sudo('whoami')
```

**Comment by slippers** [comment]
this pull request fixes this issue

https://github.com/fabric/fabric/pull/1894

**Comment by micahjsmith** [comment]
this is still an issue with fabric 3.0.0, invoke 2.0.0, py 3.9

the pre-task is called with a normal invoke `Context` instead of a fabric `Connection`

fabfile.py
```
from fabric import task


@task
def two(c):
    c.local('echo two')


@task(pre=[two])
def one(c):
    c.local('echo one')
```

```
$ fab -H some-host one
Traceback (most recent call last):
  File "/Users/micahsmith/.pyenv/versions/3.9.13/envs/venv/lib/python3.9/site-packages/invoke/config.py", line 102, in __getattr__
    return self._get(key)
  File "/Users/micahsmith/.pyenv/versions/3.9.13/envs/venv/lib/python3.9/site-packages/invoke/config.py", line 162, in _get
    value = self._config[key]
  File "/Users/micahsmith/.pyenv/versions/3.9.13/envs/venv/lib/python3.9/site-packages/invoke/config.py", line 153, in __getitem__
    return self._get(key)
  File "/Users/micahsmith/.pyenv/versions/3.9.13/envs/venv/lib/python3.9/site-packages/invoke/config.py", line 162, in _get
    value = self._config[key]
KeyError: 'local'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/micahsmith/.pyenv/versions/venv/bin/fab", line 8, in <module>
    sys.exit(program.run())
  File "/Users/micahsmith/.pyenv/versions/3.9.13/envs/venv/lib/python3.9/site-packages/invoke/program.py", line 380, in run
    self.execute()
  File "/Users/micahsmith/.pyenv/versions/3.9.13/envs/venv/lib/python3.9/site-packages/invoke/program.py", line 565, in execute
    executor.execute(*self.tasks)
  File "/Users/micahsmith/.pyenv/versions/3.9.13/envs/venv/lib/python3.9/site-packages/invoke/executor.py", line 127, in execute
    result = call.task(*args, **call.kwargs)
  File "/Users/micahsmith/.pyenv/versions/3.9.13/envs/venv/lib/python3.9/site-packages/invoke/tasks.py", line 115, in __call__
    result = self.body(*args, **kwargs)
  File "/Users/micahsmith/workspace/fabfile.py", line 6, in two
    c.local('echo two')
  File "/Users/micahsmith/.pyenv/versions/3.9.13/envs/venv/lib/python3.9/site-packages/invoke/config.py", line 114, in __getattr__
    raise AttributeError(err)
AttributeError: No attribute or config key found for 'local'

Valid keys: ['connect_kwargs', 'forward_agent', 'gateway', 'inline_ssh_env', 'load_ssh_configs', 'port', 'run', 'runners', 'ssh_config_path', 'sudo', 'tasks', 'timeouts', 'user']

Valid real attributes: ['cd', 'clear', 'config', 'cwd', 'from_data', 'pop', 'popitem', 'prefix', 'run', 'setdefault', 'sudo', 'update']

```

**Comment by davidjmemmett** [comment]
Hi, there is no fabric v3, that (fabric3) was a fork which is no longer maintained. Please use the latest fabric v2.Cheers,DavidOn 7 Apr 2023, at 21:31, Micah Smith ***@***.***> wrote:﻿
this is still an issue with fabric 3.0.0, invoke 2.0.0, py 3.9
the pre-task is called with a normal invoke Context instead of a fabric Connection
fabfile.py
from fabric import task


@task
def two(c):
    c.local('echo two')


@task(pre=[two])
def one(c):
    c.local('echo one')

$ fab -H some-host one
Traceback (most recent call last):
  File "/Users/micahsmith/.pyenv/versions/3.9.13/envs/venv/lib/python3.9/site-packages/invoke/config.py", line 102, in __getattr__
    return self._get(key)
  File "/Users/micahsmith/.pyenv/versions/3.9.13/envs/venv/lib/python3.9/site-packages/invoke/config.py", line 162, in _get
    value = self._config[key]
  File "/Users/micahsmith/.pyenv/versions/3.9.13/envs/venv/lib/python3.9/site-packages/invoke/config.py", line 153, in __getitem__
    return self._get(key)
  File "/Users/micahsmith/.pyenv/versions/3.9.13/envs/venv/lib/python3.9/site-packages/invoke/config.py", line 162, in _get
    value = self._config[key]
KeyError: 'local'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/micahsmith/.pyenv/versions/venv/bin/fab", line 8, in <module>
    sys.exit(program.run())
  File "/Users/micahsmith/.pyenv/versions/3.9.13/envs/venv/lib/python3.9/site-packages/invoke/program.py", line 380, in run
    self.execute()
  File "/Users/micahsmith/.pyenv/versions/3.9.13/envs/venv/lib/python3.9/site-packages/invoke/program.py", line 565, in execute
    executor.execute(*self.tasks)
  File "/Users/micahsmith/.pyenv/versions/3.9.13/envs/venv/lib/python3.9/site-packages/invoke/executor.py", line 127, in execute
    result = call.task(*args, **call.kwargs)
  File "/Users/micahsmith/.pyenv/versions/3.9.13/envs/venv/lib/python3.9/site-packages/invoke/tasks.py", line 115, in __call__
    result = self.body(*args, **kwargs)
  File "/Users/micahsmith/workspace/fabfile.py", line 6, in two
    c.local('echo two')
  File "/Users/micahsmith/.pyenv/versions/3.9.13/envs/venv/lib/python3.9/site-packages/invoke/config.py", line 114, in __getattr__
    raise AttributeError(err)
AttributeError: No attribute or config key found for 'local'

Valid keys: ['connect_kwargs', 'forward_agent', 'gateway', 'inline_ssh_env', 'load_ssh_configs', 'port', 'run', 'runners', 'ssh_config_path', 'sudo', 'tasks', 'timeouts', 'user']

Valid real attributes: ['cd', 'clear', 'config', 'cwd', 'from_data', 'pop', 'popitem', 'prefix', 'run', 'setdefault', 'sudo', 'update']
