### ISSUE TITLE
fabric 1.14.1 and pytest

### ISSUE THREAD

**Issue by mungayree** [fabric/fabric#1979]
Surfacing this odd bug very frequently esp. when we tend to use execute() API of fabfile.py in pytest to run some test case. Any workarounds. I tried with capsys.disabled(), but surface the same.
pytest test_pytest_a.py -s works fine, but with it causing exceptions.

I am using fabric 1.14.1 and pytest 3.7.2

    #test_pytest_a.py
    import pytest
    from fabfile import *
    def test_atest():
        execute(runcmd, hosts=['root@192.168.1.1:22'])

    #fabfile.py
    from fabric.api import *
    env.passwords = { 'root@192.168.1.1:22' : 'xyz' }
    @task
    def runcmd(cmd='date'):
          run(cmd, shell=False)

logs of this show -

   
    ../py2venv/lib/python2.7/site-packages/fabric/thread_handling.py:12: in wrapper
        callable(*args, **kwargs)
    ../py2venv/lib/python2.7/site-packages/fabric/io.py:227: in input_loop
     r, w, x = select([sys.stdin], [], [], 0.0)
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    self = <_pytest.capture.DontReadFromInput object at 0x7fd9a463b750>

    def fileno(self):
    >       raise UnsupportedOperation("redirected stdin is pseudofile, " "has no fileno()")
    E       UnsupportedOperation: redirected stdin is pseudofile, has no fileno()

    ../py2venv/lib/python2.7/site-packages/_pytest/capture.py:599: UnsupportedOperation

**Comment by ploxiln** [comment]
pytest does not want you to use stdin, but there is no way to avoid fabric (1.x at least) from using stdin. Looks like you can either mock `sys.stdin` to replace it with something like `open("/dev/null")`, or you can disable pytest capturing entirely, or maybe you can just do `pytest --capture=sys`

https://stackoverflow.com/questions/38723140/i-want-to-use-stdin-in-a-pytest-test
https://stackoverflow.com/questions/43575274/how-to-add-stdin-interaction-with-pytest
https://docs.pytest.org/en/latest/capture.html#setting-capturing-methods-or-disabling-capturing

**Comment by mungayree** [comment]
The pytest -s option (—capture=no) seem to run fine but print a lot as per
the execute.
But all other capxxx seem to have expectations in fabric.io.
I also experimented with capsys.disabled() and didn’t work. Any simple
command in fabric from shell have any stdin ? when invoked solo ?
Understand if preceded with ‘|’ for pipes. Don’t why the
r,w,x is [sys.stdin],[],[] in backtrace.

Thanks.

**Comment by ploxiln** [comment]
Here's the mock.patch() based work-around. I tested it, seems good:

```python
from mock import patch
from fabric.api import task, run, execute

@task
def remote_command():
    run("date", shell=False)

@patch('sys.stdin', new=open("/dev/null"))
def test_remote_cmd():
    execute(remote_command, hosts=['ubuntu@devbox'])
```

**Comment by Delgan** [comment]
Hi @ploxiln.

I encounter a problem with the workaround provided: it raises an `OSError` while using with `sudo` as `root` user.

```python
import sys
import os
import fabric


if __name__ == "__main__":
    sys.stdin = open(os.devnull)
    
    fabric_config = fabric.Config(
        overrides={"sudo": {"password": "p4ssW0rd", "user": "root"}}
    )

    with fabric.Connection(
        host="127.0.0.1",
        user="delgan",
        connect_kwargs={"allow_agent": False, "password": "p4ssW0rd"},
        config=fabric_config,
        connect_timeout=5,
    ) as connection:
        connection.open()
        connection.sudo("ls")
```
```bash
$ python test.py 
[sudo] password: 
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    connection.sudo("ls")
  File "<decorator-gen-4>", line 2, in sudo
  File "/home/delgan/env/lib/python3.8/site-packages/fabric/connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "/home/delgan/env/lib/python3.8/site-packages/fabric/connection.py", line 735, in sudo
    return self._sudo(self._remote_runner(), command, **kwargs)
  File "/home/delgan/env/lib/python3.8/site-packages/invoke/context.py", line 212, in _sudo
    return runner.run(cmd_str, watchers=watchers, **kwargs)
  File "/home/delgan/env/lib/python3.8/site-packages/invoke/runners.py", line 363, in run
    return self._run_body(command, **kwargs)
  File "/home/delgan/env/lib/python3.8/site-packages/invoke/runners.py", line 422, in _run_body
    return self.make_promise() if self._asynchronous else self._finish()
  File "/home/delgan/env/lib/python3.8/site-packages/invoke/runners.py", line 474, in _finish
    raise ThreadException(thread_exceptions)
invoke.exceptions.ThreadException: 
Saw 1 exceptions within threads (OSError):


Thread args: {'kwargs': {'buffer_': ['[sudo] password: \n'],
            'hide': False,
            'output': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>},
 'target': <bound method Runner.handle_stderr of <fabric.runners.Remote object at 0x7f93dddaeb80>>}

Traceback (most recent call last):

  File "/home/delgan/env/lib/python3.8/site-packages/invoke/util.py", line 233, in run
    super(ExceptionHandlingThread, self).run()

  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)

  File "/home/delgan/env/lib/python3.8/site-packages/invoke/runners.py", line 749, in handle_stderr
    self._handle_output(

  File "/home/delgan/env/lib/python3.8/site-packages/invoke/runners.py", line 717, in _handle_output
    self.respond(buffer_)

  File "/home/delgan/env/lib/python3.8/site-packages/invoke/runners.py", line 884, in respond
    self.write_proc_stdin(response)

  File "/home/delgan/env/lib/python3.8/site-packages/invoke/runners.py", line 960, in write_proc_stdin
    self._write_proc_stdin(data.encode(self.encoding))

  File "/home/delgan/env/lib/python3.8/site-packages/fabric/runners.py", line 67, in _write_proc_stdin
    return self.channel.sendall(data)

  File "/home/delgan/env/lib/python3.8/site-packages/paramiko/channel.py", line 846, in sendall
    sent = self.send(s)

  File "/home/delgan/env/lib/python3.8/site-packages/paramiko/channel.py", line 801, in send
    return self._send(s, m)

  File "/home/delgan/env/lib/python3.8/site-packages/paramiko/channel.py", line 1198, in _send
    raise socket.error("Socket is closed")

OSError: Socket is closed
```

I also tried with `io.StringIO()` instead of `os.devnull` but got the same result. If I remove ` sys.stdin = open(os.devnull)` then it works fine (but it breaks `pytest` of course). I'm using `fabric==2.5.0` with Python 3.8.6 on Ubuntu 18.04.

Please, do you have any idea about how to circumvent the issue?

**Comment by ploxiln** [comment]
No idea, sorry ... previously this issue was about Fabric-1.x, while you are using Fabric-2.x which is a complete re-write.

**Comment by Delgan** [comment]
No problem, thanks for answering. :+1:
