### ISSUE TITLE
ValueError running Fabric 2 with Python 3 type hints

### ISSUE THREAD

**Issue by shatil** [fabric/fabric#1997]
## Summary
Running Fabric with type hints on a `@fabric.task`-decorated function (i.e., a `fab` command) produces `ValueError: Function has keyword-only parameters or annotations, use getfullargspec() API which can support them`.

This was never an issue with Fabric3 `1.14.post1`.

## Sample `fabfile.py`
For what it's worth, it doesn't matter whether the type-hinted parameter is required or optional.

```python
import fabric

@fabric.task
def hashint(c, yes: bool):
    """Was this function given a hint?"""
    print(yes)
```

## Versions

* Fabric: `2.4.0`
* Python 3: `3.7.4`
* macOS: `10.14.5` (`18F132`)

I tested in Docker on Amazon Linux 2's Python `python3-3.7.3-1.amzn2.0.2.x86_64` and got the same results.

## Traceback
What happens if I run `fab --list` (or really anything else with `fab`):

```
Traceback (most recent call last):
  File "/usr/local/bin/fab", line 10, in <module>
    sys.exit(program.run())
  File "/usr/local/lib/python3.7/site-packages/invoke/program.py", line 324, in run
    self.parse_collection()
  File "/usr/local/lib/python3.7/site-packages/invoke/program.py", line 408, in parse_collection
    self.load_collection()
  File "/usr/local/lib/python3.7/site-packages/fabric/main.py", line 82, in load_collection
    super(Fab, self).load_collection()
  File "/usr/local/lib/python3.7/site-packages/invoke/program.py", line 599, in load_collection
    module, parent = loader.load(coll_name)
  File "/usr/local/lib/python3.7/site-packages/invoke/loader.py", line 76, in load
    module = imp.load_module(name, fd, path, desc)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/shatil/workspace/ecs-cfn/services/fabfile.py", line 7, in <module>
    def hashint(c, yes: bool):
  File "/usr/local/lib/python3.7/site-packages/fabric/tasks.py", line 71, in task
    return invoke.task(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/invoke/tasks.py", line 313, in task
    return klass(args[0], **kwargs)
  File "/usr/local/lib/python3.7/site-packages/fabric/tasks.py", line 21, in __init__
    super(Task, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/invoke/tasks.py", line 77, in __init__
    self.positional = self.fill_implicit_positionals(positional)
  File "/usr/local/lib/python3.7/site-packages/invoke/tasks.py", line 168, in fill_implicit_positionals
    args, spec_dict = self.argspec(self.body)
  File "/usr/local/lib/python3.7/site-packages/invoke/tasks.py", line 154, in argspec
    spec = inspect.getargspec(func)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py", line 1082, in getargspec
    raise ValueError("Function has keyword-only parameters or annotations"
ValueError: Function has keyword-only parameters or annotations, use getfullargspec() API which can support them
```

**Comment by italomaia** [comment]
Just got this error myself. Using 3.7.3

**Comment by shatil** [comment]
@italomaia we might be out of luck here 😢 I see the same bug filed with `invoke` has been open since June 2016, and I'm discovering this in August of 2019: https://github.com/pyinvoke/invoke/issues/357

**Comment by kornicameister** [comment]
well 2020 and still making it hard. I am not sure what's the deal here but python closes on 3.9 and this library got stuck on 3.6 :/ according to classifiers in setup.py
