### ISSUE TITLE
pytest and fabric

### ISSUE THREAD

**Issue by kieronflynn** [fabric/fabric#2005]
Hi Folks,

I am a new user of python (extensive background in C#, okay background in Java), and i've hit a snag, hopefully through stupidity and there is a simple answer.

I am using Python 3.7.4 and the latest version I believe of fabric and pytest.

Having a background most of my career in the Microsoft stack means I am shabby on linux as well, but learning...

So anyway to the task at hand. I am attempting to write some smoke tests for a set of components in a enterprise micro services style environment.

One part of the application uses an application call DDF hosted in a VM. I am wanting to interrogate the DDF instance via SSH to make sure that it has build correctly as part of the smoke test. (NOT possible unfortunatrly via REST calls)

Usually of course with unit testing you are wanting to stub/mock out dependancies, but it is important to note that this is NOT what I am trying to do. Overnight the DDF VM gets built using a CI server, and the smoke test wants to then interrogate the box.

So I thought I would be able to use the following:
```
def runCommandOverSSH(self, host, username, port, password, sshCommand):

        result = None
        self.logger.info("Running the command %s on %s" % (sshCommand, host))

       # connectionArguments = {"password":[password]}
        config = Config(overrides={'user': username, 'connect_kwargs': {'password': password}})

        # with Connection(host, port=port, user=username) as connection:
        #     result = connection.run(sshCommand, hide=True, connect_kwargs=connectionArguments)

        with Connection(host, port=port, config=config) as connection:
            result = connection.run(sshCommand, hide=True)

        msg = "Ran %s on %s, got stdout:\n%s" % (result.command, result.connection.host, result.stdout)
        self.logger.debug(msg)

        return result
```

Unfortunately when I run this via pytest I get an error
 OSError('reading from stdin while output is captured')

Full stack trace below. Is there some kinda configuration setting I can use to get around this, when used from outside of pytest the code works fine.

Yours in hope of a simple answer!
Kieron

```
Traceback (most recent call last):

  File "C:\Work\Python\lib\site-packages\invoke\util.py", line 233, in run
    super(ExceptionHandlingThread, self).run()

  File "C:\Work\Python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)

  File "C:\Work\Python\lib\site-packages\invoke\runners.py", line 687, in handle_stdin
    data = self.read_our_stdin(input_)

  File "C:\Work\Python\lib\site-packages\invoke\runners.py", line 646, in read_our_stdin
    bytes_ = input_.read(bytes_to_read(input_))

  File "C:\Work\Python\lib\site-packages\_pytest\capture.py", line 702, in read
    raise IOError("reading from stdin while output is captured")

OSError: reading from stdin while output is captured

Traceback (most recent call last):
  File "C:\Work\Subsea7\Integration\Testing\src\main\python\sdp\RefreshSdpEnvironment.py", line 41, in refresh
    result = sshClient.runCommandOverSSH("myHost", "XXXX", 8101, "YYYY", "la")
  File "C:\Work\Subsea7\Integration\Testing\src\main\python\util\SSHClient.py", line 22, in runCommandOverSSH
    result = connection.run(sshCommand)
  File "<decorator-gen-3>", line 2, in run
  File "C:\Work\Python\lib\site-packages\fabric\connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "C:\Work\Python\lib\site-packages\fabric\connection.py", line 721, in run
    return self._run(self._remote_runner(), command, **kwargs)
  File "C:\Work\Python\lib\site-packages\invoke\context.py", line 101, in _run
    return runner.run(command, **kwargs)
  File "C:\Work\Python\lib\site-packages\invoke\runners.py", line 291, in run
    return self._run_body(command, **kwargs)
  File "C:\Work\Python\lib\site-packages\invoke\runners.py", line 399, in _run_body
    raise ThreadException(thread_exceptions)
invoke.exceptions.ThreadException: 
Saw 1 exceptions within threads (OSError):


Thread args: {'kwargs': {'echo': None,
            'input_': <_pytest.capture.DontReadFromInput object at 0x04C31690>,
            'output': <_pytest.capture.EncodedFile object at 0x04C31770>},
 'target': <bound method Runner.handle_stdin of <fabric.runners.Remote object at 0x0593BE50>>}

Traceback (most recent call last):

  File "C:\Work\Python\lib\site-packages\invoke\util.py", line 233, in run
    super(ExceptionHandlingThread, self).run()

  File "C:\Work\Python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)

  File "C:\Work\Python\lib\site-packages\invoke\runners.py", line 687, in handle_stdin
    data = self.read_our_stdin(input_)

  File "C:\Work\Python\lib\site-packages\invoke\runners.py", line 646, in read_our_stdin
    bytes_ = input_.read(bytes_to_read(input_))

  File "C:\Work\Python\lib\site-packages\_pytest\capture.py", line 702, in read
    raise IOError("reading from stdin while output is captured")

OSError: reading from stdin while output is captured


2019-08-27 11:37:13,736 - root - ERROR - test_1_smokeTest_InsFile - Error during test_1_smokeTest
Traceback (most recent call last):
  File "C:\Work\Subsea7\Integration\Testing\src\main\python\sdp\RefreshSdpEnvironment.py", line 41, in refresh
    result = sshClient.runCommandOverSSH("myHost", "XXXX", 8101, "YYYY", "la")
  File "C:\Work\Subsea7\Integration\Testing\src\main\python\util\SSHClient.py", line 22, in runCommandOverSSH
    result = connection.run(sshCommand)
  File "<decorator-gen-3>", line 2, in run
  File "C:\Work\Python\lib\site-packages\fabric\connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "C:\Work\Python\lib\site-packages\fabric\connection.py", line 721, in run
    return self._run(self._remote_runner(), command, **kwargs)
  File "C:\Work\Python\lib\site-packages\invoke\context.py", line 101, in _run
    return runner.run(command, **kwargs)
  File "C:\Work\Python\lib\site-packages\invoke\runners.py", line 291, in run
    return self._run_body(command, **kwargs)
  File "C:\Work\Python\lib\site-packages\invoke\runners.py", line 399, in _run_body
    raise ThreadException(thread_exceptions)
invoke.exceptions.ThreadException: 
Saw 1 exceptions within threads (OSError):


Thread args: {'kwargs': {'echo': None,
            'input_': <_pytest.capture.DontReadFromInput object at 0x04C31690>,
            'output': <_pytest.capture.EncodedFile object at 0x04C31770>},
 'target': <bound method Runner.handle_stdin of <fabric.runners.Remote object at 0x0593BE50>>}

Traceback (most recent call last):

  File "C:\Work\Python\lib\site-packages\invoke\util.py", line 233, in run
    super(ExceptionHandlingThread, self).run()

  File "C:\Work\Python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)

  File "C:\Work\Python\lib\site-packages\invoke\runners.py", line 687, in handle_stdin
    data = self.read_our_stdin(input_)

  File "C:\Work\Python\lib\site-packages\invoke\runners.py", line 646, in read_our_stdin
    bytes_ = input_.read(bytes_to_read(input_))

  File "C:\Work\Python\lib\site-packages\_pytest\capture.py", line 702, in read
    raise IOError("reading from stdin while output is captured")

OSError: reading from stdin while output is captured
```

**Comment by kieronflynn** [comment]
Hiya,

I've taken the approach of mocking stdin, i.e.
```
def test_disabling_capturing(monkeypatch):
    try:
        monkeypatch.setattr('sys.stdin', io.StringIO('my input'))
        sshClient = SSHClient()
        result = sshClient.runCommandOverSSH("localhost", "admin", 8101, "admin", "la")
        stop = 1
    except Exception as ex:
        stop = 1
    finally:
        stop = 1
```

So this seems to avoid the issues with Fabric throwing an exception when pytest uses stdin, and still preserves the stderr and std output so any exceptions filter back to pytest and then the CI server.

So it seems to be a valid approach...

Cheers
Kieron

**Comment by L1ghtman2k** [comment]
looks very similar to https://github.com/fabric/fabric/issues/2006

**Comment by thomasdeneux** [comment]
Hello, i have the exact same problem, and using @kieronflynn solution (`monkeypatch.setattr('sys.stdin', io.StringIO('my input'))`) worked out to eliminate error "OSError: reading from stdin while output is captured".

But now i run on another error "OSError: socket closed"

To be more specific, the following code works fine:

```
from fabric import Connection

RobotIP = '10.0.0.1'
RobotPort = 22
RobotID = 'pi'
RobotPW = 'raspberry'

c = Connection(host=RobotIP, user=RobotID, port=RobotPort,
               connect_kwargs={"password": RobotPW})
c.run('whoami')
```

However running the following test fails:

```
from fabric import Connection
import io

RobotIP = '10.0.0.1'
RobotPort = 22
RobotID = 'pi'
RobotPW = 'raspberry'


def test_connection(monkeypatch):
    monkeypatch.setattr('sys.stdin', io.StringIO('my input'))
    c = Connection(host=RobotIP, user=RobotID, port=RobotPort,
                   connect_kwargs={"password": RobotPW})
    c.run('whoami')
```

with error:

```
C:\Users\blabla\env\python.exe "E:/Program Files/JetBrains/PyCharm 2023.2.1/plugins/python/helpers/pycharm/_jb_pytest_runner.py" --target test.py::test_connection 
Testing started at 15:34 ...
Launching pytest with arguments test.py::test_connection --no-header --no-summary -q in E:\Users\Thomas\Python\alphai

============================= test session starts =============================
collecting ... collected 1 item

test.py::test_connection FAILED                                          [100%]pi

test.py:23 (test_connection)
monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x0000023F68AEDDC0>

    def test_connection(monkeypatch):
        monkeypatch.setattr('sys.stdin', io.StringIO('my input'))
        c = Connection(host=RobotIP, user=RobotID, port=RobotPort,
                       connect_kwargs={"password": RobotPW})
>       c.run('whoami')

test.py:28: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
<decorator-gen-3>:2: in run
    ???
C:\Users\blabla\env\lib\site-packages\fabric\connection.py:30: in opens
    return method(self, *args, **kwargs)
C:\Users\thomas\blabla\env\lib\site-packages\fabric\connection.py:725: in run
    return self._run(self._remote_runner(), command, **kwargs)
C:\Users\thomas\blabla\env\lib\site-packages\invoke\context.py:102: in _run
    return runner.run(command, **kwargs)
C:\Users\blabla\env\lib\site-packages\fabric\runners.py:72: in run
    return super(Remote, self).run(command, **kwargs)
C:\Users\blabla\env\lib\site-packages\invoke\runners.py:380: in run
    return self._run_body(command, **kwargs)
C:\Users\blabla\env\lib\site-packages\invoke\runners.py:442: in _run_body
    return self.make_promise() if self._asynchronous else self._finish()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <fabric.runners.Remote object at 0x0000023F68AEDF40>

    def _finish(self):
        # Wait for subprocess to run, forwarding signals as we get them.
        try:
            while True:
                try:
                    self.wait()
                    break  # done waiting!
                # Don't locally stop on ^C, only forward it:
                # - if remote end really stops, we'll naturally stop after
                # - if remote end does not stop (eg REPL, editor) we don't want
                # to stop prematurely
                except KeyboardInterrupt as e:
                    self.send_interrupt(e)
                # TODO: honor other signals sent to our own process and
                # transmit them to the subprocess before handling 'normally'.
        # Make sure we tie off our worker threads, even if something exploded.
        # Any exceptions that raised during self.wait() above will appear after
        # this block.
        finally:
            # Inform stdin-mirroring worker to stop its eternal looping
            self.program_finished.set()
            # Join threads, storing inner exceptions, & set a timeout if
            # necessary. (Segregate WatcherErrors as they are "anticipated
            # errors" that want to show up at the end during creation of
            # Failure objects.)
            watcher_errors = []
            thread_exceptions = []
            for target, thread in six.iteritems(self.threads):
                thread.join(self._thread_join_timeout(target))
                exception = thread.exception()
                if exception is not None:
                    real = exception.value
                    if isinstance(real, WatcherError):
                        watcher_errors.append(real)
                    else:
                        thread_exceptions.append(exception)
        # If any exceptions appeared inside the threads, raise them now as an
        # aggregate exception object.
        # NOTE: this is kept outside the 'finally' so that main-thread
        # exceptions are raised before worker-thread exceptions; they're more
        # likely to be Big Serious Problems.
        if thread_exceptions:
>           raise ThreadException(thread_exceptions)
E           invoke.exceptions.ThreadException: 
E           Saw 1 exceptions within threads (OSError):
E           
E           
E           Thread args: {'kwargs': {'echo': None,
E                       'input_': <_io.StringIO object at 0x0000023F684DC5E0>,
E                       'output': <_io.TextIOWrapper name='<tempfile._TemporaryFileWrapper object at 0x0000023F68122880>' mode='r+' encoding='utf-8'>},
E            'target': <bound method Runner.handle_stdin of <fabric.runners.Remote object at 0x0000023F68AEDF40>>}
E           
E           Traceback (most recent call last):
E           
E             File "C:\Users\blabla\env\lib\site-packages\invoke\util.py", line 237, in run
E               super(ExceptionHandlingThread, self).run()
E           
E             File "threading.py", line 917, in run
E           
E             File "C:\Users\blabla\env\lib\site-packages\invoke\runners.py", line 852, in handle_stdin
E               self.write_proc_stdin(data)
E           
E             File "C:\Users\blabla\env\lib\site-packages\invoke\runners.py", line 990, in write_proc_stdin
E               self._write_proc_stdin(data.encode(self.encoding))
E           
E             File "C:\Users\blabla\env\lib\site-packages\fabric\runners.py", line 81, in _write_proc_stdin
E               return self.channel.sendall(data)
E           
E             File "C:\Users\blabla\env\lib\site-packages\paramiko\channel.py", line 846, in sendall
E               sent = self.send(s)
E           
E             File "C:\Users\blabla\env\lib\site-packages\paramiko\channel.py", line 801, in send
E               return self._send(s, m)
E           
E             File "C:\Users\blabla\env\lib\site-packages\paramiko\channel.py", line 1198, in _send
E               raise socket.error("Socket is closed")
E           
E           OSError: Socket is closed

C:\Users\blabla\env\lib\site-packages\invoke\runners.py:494: ThreadException


======================== 1 failed, 1 warning in 0.94s =========================

Process finished with exit code 1
```

Any idea?

**Comment by thomasdeneux** [comment]
oh, i fixed it by providing no input to the mocked stdin (`io.StringIO('')` instead of `io.StringIO('my input')`)

**Comment by okken** [comment]
@thomasdeneux Thank you so much for posting your solution. This helped me today.

**Comment by jenisys** [comment]
A slightly more explicit solution/workaround by using the recipe from above.

```python
# -- FILE: test_fabric.py
from contextlib import context manager
import pytest

@pytest.fixture
def disable_stdin_capture(monkeypatch):
    # -- NEEDED-FOR: fabric.connection.Connection.run() in a test-function.
    monkeypatch.setattr("sys.stdin", StringIO(""))
    return monkeypatch


@contextmanager
def use_disabled_stdin_capture():
    with pytest.MonkeyPatch.context() as monkeypatch:
        monkeypatch.setattr("sys.stdin", StringIO(""))
        yield monkeypatch


# -----------------------------------------------------------------------------
# TEST SUITE
# -----------------------------------------------------------------------------
def test_fabric_1(host_config, disable_stdin_capture):
    hostname = host_config.hostname
    c = Connection(hostname)
    command_result = c.run("uname -n")
    output = command_result.stdout.strip()
    assert output == hostname


def test_fabric_2(host_config):  # ALTERNATIVE-TO: disable_stdin_capture):
    hostname = host_config.hostname
    c = Connection(hostname)
    with use_disabled_stdin_capture():  #  NEEDED-FOR: pytest to work.
        command_result = c.run("uname -n")
    
    output = command_result.stdout.strip()
    assert output == hostname
```

**Comment by airtower-luna** [comment]
If you add `in_stream=False` to the `Connection.run()` it won't try to open stdin. I agree this should be handled automatically, but it's a much nicer workaround than monkeypatching `sys.stdin`. 🙂
