### ISSUE TITLE
Try to plug fab command on gitlab-ci.yml

### ISSUE THREAD

**Issue by lucassimon** [fabric/fabric#2006]
Hello, I trying to run fab cli to run a deploy on gitlab-cy.yml but I received an execpetion on Invoke, but I don't know how to solve it.

```yaml
image: "python:3.6"

stages:
  - deploy

deploy_staging:
  stage: deploy
  environment:
    name: staging
    url: https://some-url
  script:
    - echo "ready"
    - fab -H user@xxx.xxx.xxx.xx uname
  only:
    - master

deploy_production:
  stage: deploy
  script:
    - echo "ready"
  only:
    - tags
```

Logs. It prints the stdout of the uname command but raises an exception on the next step

```txt
$ fab -H user@xxx.xxx.xxx.xxx uname
Linux mydomain 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u4 (2019-07-19) x86_64 GNU/Linux  

Traceback (most recent call last):
  File "/usr/local/bin/fab", line 10, in <module>
    sys.exit(program.run())
  File "/usr/local/lib/python3.6/site-packages/invoke/program.py", line 384, in run
    self.execute()
  File "/usr/local/lib/python3.6/site-packages/invoke/program.py", line 566, in execute
    executor.execute(*self.tasks)
  File "/usr/local/lib/python3.6/site-packages/invoke/executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "/usr/local/lib/python3.6/site-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/builds/project/mgt/api/fabfile.py", line 71, in uname
    return c.run("uname -a")
  File "<decorator-gen-3>", line 2, in run
  File "/usr/local/lib/python3.6/site-packages/fabric/connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/fabric/connection.py", line 702, in run
    return self._run(self._remote_runner(), command, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/invoke/context.py", line 101, in _run
    return runner.run(command, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/invoke/runners.py", line 291, in run
    return self._run_body(command, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/invoke/runners.py", line 399, in _run_body
    raise ThreadException(thread_exceptions)
invoke.exceptions.ThreadException: 
Saw 1 exceptions within threads (NotImplementedError):


Thread args: {'kwargs': {'echo': None,
            'input_': <_io.TextIOWrapper name='<stdin>' mode='r' encoding='UTF-8'>,
            'output': <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>},
 'target': <bound method Runner.handle_stdin of <fabric.runners.Remote object at 0x7fa6404edcc0>>}

Traceback (most recent call last):

  File "/usr/local/lib/python3.6/site-packages/invoke/util.py", line 233, in run
    super(ExceptionHandlingThread, self).run()

  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)

  File "/usr/local/lib/python3.6/site-packages/invoke/runners.py", line 706, in handle_stdin
    self.close_proc_stdin()

  File "/usr/local/lib/python3.6/site-packages/invoke/runners.py", line 939, in close_proc_stdin
    raise NotImplementedError

NotImplementedError
```

**Comment by L1ghtman2k** [comment]
I am getting the same error. Was using fabric 6 months ago, and it worked fine.

multriprocessing.Process still lets this work in windows

**Comment by L1ghtman2k** [comment]
Hey, it seems like the reason is in invoke library:
https://github.com/pyinvoke/invoke/issues/654
you should install invoke=1.2.0 instead of 1.3.0
