### ISSUE TITLE
archlinux  install fabric error

### ISSUE THREAD

**Issue by hkshawn** [fabric/fabric#2049]
Traceback (most recent call last):
  File "/usr/bin/fab", line 11, in <module>
    load_entry_point('fabric==2.5.0', 'console_scripts', 'fab')()
  File "/usr/lib/python3.8/site-packages/invoke/program.py", line 373, in run
    self.parse_collection()
  File "/usr/lib/python3.8/site-packages/invoke/program.py", line 465, in parse_collection
    self.load_collection()
  File "/usr/lib/python3.8/site-packages/fabric/main.py", line 87, in load_collection
    super(Fab, self).load_collection()
  File "/usr/lib/python3.8/site-packages/invoke/program.py", line 696, in load_collection
    module, parent = loader.load(coll_name)
  File "/usr/lib/python3.8/site-packages/invoke/loader.py", line 76, in load
    module = imp.load_module(name, fd, path, desc)
  File "/usr/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/rango/go/src/y5/fabfile.py", line 4, in <module>
    def hashint(c, yes: bool):
  File "/usr/lib/python3.8/site-packages/fabric/tasks.py", line 71, in task
    return invoke.task(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/invoke/tasks.py", line 312, in task
    return klass(args[0], **kwargs)
  File "/usr/lib/python3.8/site-packages/fabric/tasks.py", line 21, in __init__
    super(Task, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/invoke/tasks.py", line 76, in __init__
    self.positional = self.fill_implicit_positionals(positional)
  File "/usr/lib/python3.8/site-packages/invoke/tasks.py", line 167, in fill_implicit_positionals
    args, spec_dict = self.argspec(self.body)
  File "/usr/lib/python3.8/site-packages/invoke/tasks.py", line 153, in argspec
    spec = inspect.getargspec(func)
  File "/usr/lib/python3.8/inspect.py", line 1083, in getargspec
    raise ValueError("Function has keyword-only parameters or annotations"
ValueError: Function has keyword-only parameters or annotations, use inspect.signature() API which can support them

**Comment by aprilahijriyan** [comment]
experiencing the same thing, any progress here?

**Comment by ploxiln** [comment]
This particular error is because you can't use type hints in your fabfile task functions.

https://github.com/fabric/fabric/issues/1997
https://github.com/pyinvoke/invoke/issues/357
