### ISSUE TITLE
Issue running Django management commands

### ISSUE THREAD

**Issue by TheHamz** [fabric/fabric#2053]
Hello, I'm having issues running Django management commands while regular bash commands work.

```
hosts = ['worker@ip-adress']

@task(hosts=hosts)
def do_that(c):
    with c.prefix('source /data/worker/ve/bin/activate'):
        with c.cd('/home/worker/ve/app'):
            # c.run(f"{python} manage.py showmigrations") gettin error below here
            c.run('python -V') works fine
```

```
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
  File "/data/worker/ve/lib/python2.7/site-packages/django/core/management/__init__.py", line 10, in <module>
    from django.apps import apps
  File "/data/worker/ve/lib/python2.7/site-packages/django/apps/__init__.py", line 1, in <module>
    from .config import AppConfig
  File "/data/worker/ve/lib/python2.7/site-packages/django/apps/config.py", line 5, in <module>
    from django.utils._os import upath
  File "/data/worker/ve/lib/python2.7/site-packages/django/utils/_os.py", line 5, in <module>
    import tempfile
  File "/opt/rh/python27/root/usr/lib64/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/opt/rh/python27/root/usr/lib64/python2.7/io.py", line 51, in <module>
    import _io
ImportError: /data/worker/ve/lib64/python2.7/lib-dynload/_io.so: undefined symbol: _PyErr_ReplaceException

```

**Comment by davidjmemmett** [comment]
Hi TheHamz,

This appears to be a problem with your remote python installation and not with Fabric.

Cheers,
David
