### ISSUE TITLE
ThreadingGroup do not support gateway

### ISSUE THREAD

**Issue by nebmail** [fabric/fabric#2065]
2nd thread and above will cause exception as it is trying to use gateway Connection object on the first thread.

A simple fix to work around is just to use **deepcopy(kwargs) in Group when self.extend().

**Comment by taxtgg** [comment]
Steps to reproduce:
`from fabric import Connection, SerialGroup, ThreadingGroup
result = ThreadingGroup('host1', 'host2', 'host3', gateway=Connection(gatewayhost)).run('hostname')`

Output:
`ip-10-0-2-200.ec2.internal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "xxxxxxxxxx/lib/python3.7/site-packages/fabric/group.py", line 240, in run
    raise GroupException(results)
fabric.exceptions.GroupException: {<Connection host=10.0.2.200 gw=proxyjump>: <Result cmd='hostname' exited=0>, <Connection host=10.0.3.66 gw=proxyjump>: SSHException('No existing session'), <Connection host=10.0.0.79 gw=proxyjump>: SSHException('No existing session')}`

**Comment by brenmous** [comment]
I've found that if the connections are first used to perform a transfer or run (or `open` or `sftp` is otherwise called on them in some way) then deepcopying the gateway fails because it seems to contain a `_thread.lock` which can't be pickled. However calling `open` or `sftp` on each connection before creating the Group also solves the issue - I'm guessing because this inits and caches each connection including the gateway, giving the threads access. See #2139.

**Comment by davidjmemmett** [comment]
Hi @nebmail @taxtgg @brenmous,

Could you please provide [some additional information](http://www.contribution-guide.org/) to help us reproduce this issue? There's plenty to be getting on with, but I just want to make sure we've covered the basics.


**What to put in your bug report**

Make sure your report gets the attention it deserves: bug reports with missing information may be ignored or punted back to you, delaying a fix. The below constitutes a bare minimum; more info is almost always better:

- What version of the core programming language interpreter/compiler are you using? For example, if it’s a Python project, are you using Python 2.7.3? Python 3.3.1? PyPy 2.0?
- What operating system are you on? Windows? (Vista? 7? 32-bit? 64-bit?) Mac OS X? (10.7.4? 10.9.0?) Linux? (Which distro? Which version of that distro? 32 or 64 bits?) Again, more detail is better.
- Which version or versions of the software are you using? Ideally, you followed the advice above and have ruled out (or verified that the problem exists in) a few different versions.
- [x] ~How can the developers recreate the bug on their end? If possible, include a copy of your code, the command you used to invoke it, and the full output of your run (if applicable.)~

A common tactic is to pare down your code until a simple (but still bug-causing) “base case” remains. Not only can this help you identify problems which aren’t real bugs, but it means the developer can get to fixing the bug faster.
