### ISSUE TITLE
install fabric2.5 is not sucess,help!thanks

### ISSUE THREAD

**Issue by herotan** [fabric/fabric#2070]
git  clone https://github.com/fabric/fabric.git
cd fabric
pip3 setup.py install

#install failed,error list:

zip_safe flag not set; analyzing archive contents...
Traceback (most recent call last):
  File "setup.py", line 101, in <module>
    "Topic :: System :: Systems Administration",
  File "/usr/lib64/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.7/distutils/dist.py", line 985, in run_command

**Comment by ploxiln** [comment]
That pip command and error output do not make sense, sorry.

You should be able to use pip without cloning the git repo at all:

```
pip3 install Fabric==2.5.0
```

or, if installing from a local clone of the repo, do:

```
cd fabric
pip3 install .
```

**Comment by herotan** [comment]
It's ok,thanks for  @ploxiln
