### ISSUE TITLE
Documentation - key_filename example is incorrect in connection.py

### ISSUE THREAD

**Issue by riazjahangir** [fabric/fabric#2085]
Documentation error:

In the `Connection` API docstring (https://docs.fabfile.org/en/latest/api/connection.html#fabric.connection.Connection), the example code is:

```python
c = Connection(
    host="hostname",
    user="admin",
    connect_kwargs={
        "key_filename": "/home/myuser/.ssh/private.key",
    },
)
```

However running this throws an error:
```python
AttributeError: 'str' object has no attribute 'extend'
```

The `key_filename` expects a list, so the example should read:

```python
c = Connection(
    host="hostname",
    user="admin",
    connect_kwargs={
        "key_filename": ["/home/myuser/.ssh/private.key"],
    },
)
```

**Comment by DhawalKhapre** [comment]
Can I take up this issue. I'm a beginner.
I just have to change the example on the webpage right?

**Comment by davidjmemmett** [comment]
Hi @riazjahangir,

The example given is correct - `key_filename` can either be a string or a list - please [see the appropriate documentation for the connect_kwargs](http://docs.paramiko.org/en/stable/api/client.html#paramiko.client.SSHClient). If this is still an issue, please feel to answer the questions below to give us a better idea of what is happening.


**What to put in your bug report**

Make sure your report gets the attention it deserves: bug reports with missing information may be ignored or punted back to you, delaying a fix. The below constitutes a bare minimum; more info is almost always better:

- What version of the Python interpreter are you using? Are you using an alternative interpreter such as PyPy?
- What operating system are you using both client & server-side?
- Are you using OpenSSH server or something else?
- Which version or versions of the software are you using?
- How can the developers recreate the bug on their end? If possible, include a copy of your code, the command you used to invoke it, and the full output of your run (if applicable.)
A common tactic is to pare down your code until a simple (but still bug-causing) “base case” remains. Not only can this help you identify problems which aren’t real bugs, but it means the developer can get to fixing the bug faster.

Cheers,
David

**Comment by davidjmemmett** [comment]
Hah, please ignore my previous comment - I should have tested the issue before speaking!

Example fabfile:
```python
from fabric import Connection

c = Connection(
    host="localhost",
    user="blah",
    connect_kwargs={
        "key_filename": "/home/blah/.ssh/private.key",
    },
)
```

Traceback:
```
$ fab
Traceback (most recent call last):
  File "/home/david/Dropbox/Projects/fabtest/env/bin/fab", line 11, in <module>
    load_entry_point('fabric', 'console_scripts', 'fab')()
  File "/home/david/Dropbox/Projects/fabtest/env/local/lib/python2.7/site-packages/invoke/program.py", line 373, in run
    self.parse_collection()
  File "/home/david/Dropbox/Projects/fabtest/env/local/lib/python2.7/site-packages/invoke/program.py", line 465, in parse_collection
    self.load_collection()
  File "/home/david/Projects/fabric/fabric/main.py", line 87, in load_collection
    super(Fab, self).load_collection()
  File "/home/david/Dropbox/Projects/fabtest/env/local/lib/python2.7/site-packages/invoke/program.py", line 696, in load_collection
    module, parent = loader.load(coll_name)
  File "/home/david/Dropbox/Projects/fabtest/env/local/lib/python2.7/site-packages/invoke/loader.py", line 76, in load
    module = imp.load_module(name, fd, path, desc)
  File "/home/david/Dropbox/Projects/fabric/2085/fabfile.py", line 7, in <module>
    "key_filename": "/home/myuser/.ssh/private.key",
  File "/home/david/Projects/fabric/fabric/connection.py", line 452, in __init__
    self.connect_kwargs = self.resolve_connect_kwargs(connect_kwargs)
  File "/home/david/Projects/fabric/fabric/connection.py", line 492, in resolve_connect_kwargs
    connect_kwargs["key_filename"].extend(
AttributeError: 'str' object has no attribute 'extend'
```

It seems fabric is ignoring the fact that `key_filename` can be either a string or a list.
