### ISSUE TITLE
Simple and motivating code examples

### ISSUE THREAD

**Issue by nise** [fabric/fabric#2089]
I don't know that much about python, but I've used code from many projects before. The thing I am missing at fabric is a simple, but motivation code example. I was trying to connect to a remote server and print out a simple output of a command like `uname -s`. For testing it would be fine to use a password in clear text, but the whole authentication is a mess. 

If one is searching the web for help contradictory suggestions for different versions of fabric and python appear. All of them are not helpful.

If run the following code from the "getting started page" I run into the first question what "web1" would be. I replaced it by my local host name and also with "localhost" and the corresponding IP. 
```
>>> from fabric import Connection
>>> c = Connection('web')
>>> result = c.run('uname -s')
```

This is the result: 
```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<decorator-gen-3>", line 2, in run
  File ".../lib/python3.7/site-packages/fabric/connection.py", line 29, in opens
    self.open()
  File ".../python3.7/site-packages/fabric/connection.py", line 634, in open
    self.client.connect(**kwargs)
  File ".../python3.7/site-packages/paramiko/client.py", line 368, in connect
    raise NoValidConnectionsError(errors)
paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 127.0.0.1

```
The same happens for python 3.6 and I hope you don't want me to go back to version 2.

I would be really happy, if someone could provide some help. It will probably also other who woul like to join fabric.

**Comment by dhowes47** [comment]
`con_dict = {'host': '192.168.0.50',
            'user': 'username',
            'port': 22,
            'connect_kwargs': {'password': 'D.howes4444'}}

con = Connection(**con_dict)
con.run("uname -s", hide='stderr')`

You need to pass keyword args. Are you passing the above arguments?

Above is a dict that contains some of them. This is fabric 2, below is the docs page.

[https://docs.fabfile.org/en/2.5/api/connection.html](url)

**Comment by nise** [comment]
Thank you for the quick reply, my code looks as follow, but the error remains the same as mentioned above:
```

con_dict = {
	'host': 'some-remote-machine.net',
	'user': 'some-username',
	'port': 22,
	'connect_kwargs': {'password': 'some-pass'}
	}

con = Connection(**con_dict) 
con.run('uname -s', hide='stderr')
```

**Comment by dhowes47** [comment]
Can you ssh to the machine you're trying to connect to? Have to looked at dns resolution, tried using IP and not names.

**Comment by nise** [comment]
I tried a local IP, localhost name, remote IP, remote hostname of machines that are accessible through ssh at port 22.

**Comment by dhowes47** [comment]
> I tried a local IP, localhost name, remote IP, remote hostname of machines that are accessible through ssh at port 22.

I don't think you have a problem with your code. I think you have a connection problem to the machine. 

You say accessible and by that you mean, you have connected via ssh to the machine, via the cli?

**Comment by nise** [comment]
In the terminal I can connect to the machine using ssh.

This issue seems to be related: https://github.com/paramiko/paramiko/issues/1390

**Comment by nise** [comment]
I found the problem: The server was not yet added as a known hosts. 

`ssh-keyscan -H my-machine.net >> ~/.ssh/known_hosts`

I don't know if this exception could be prevented or if the error message could become more readable.

**Comment by nise** [comment]
It seems that paramiko is finding an ssh key file, but it is a public-key only. So if I specify look_for_keys=False and allow_agent=False to ssh.connect(), that prevents it from trying to find and use ssh key files, and maybe avoids problem.

So the trick is:


```
from fabric import Connection

con_dict = {
	'host': 'your-domain.com',
	'user': 'some-user',
	'port': 22,
	'connect_kwargs': {'password': '********', 'look_for_keys': False, 'allow_agent': False},	
	}

con = Connection(**con_dict)
con.run('uname -s', hide='stderr')

```

**Comment by mrmeszaros** [comment]
If examples are given, then either show examples for handling the `in_stream`.
In fabric Connection.run it is not documented that by default it connects to the `sys.stdin` - so either an example, or a link to invoke's documentation on it.
Like [this section in the FAQ](https://www.pyinvoke.org/faq.html?highlight=stdin#i-m-getting-ioerror-inappropriate-ioctl-for-device-when-i-run-commands) mentions it can be turned off:
```python
runner.run("cmd", in_stream=False)
```
