### ISSUE TITLE
Not adding NonExist key path to key_filename if IdentityFile = none in ssh_config

### ISSUE THREAD

**Issue by linweihs** [fabric/fabric#2090]
Hi Fabric owners,

Recently, we encountered a case where IdentityFile none defined in ssh_configs, and Fabric Connections class is trying to load the key into connect_kwargs["key_filename"]

  File "/Users/welin/gaas-client_trunk/build/gaas-client/environments/development-venv/lib/python3.7/site-packages/paramiko/pkey.py", line 278, in _read_private_key_file
    with open(filename, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'none'

The issue would not resolved by passing connect_kwargs = {"key_filename": ['path/to/your/key']} , because Fabric still would load IdentityFile into connect_kwargs["key_filename"] due to hierarchy

**Comment by linweihs** [comment]
Have to work around like this
` 
c = Connection(server)
if 'none' in c.connect_kwargs['key_filename']:
      c.connect_kwargs['key_filename'].remove('none')
`

**Comment by jaraco** [comment]
I have this issue also. I'm using a corporate-managed system that includes non-existent key files in the system ssh_config:

```
$ cat /etc/ssh_config | grep IdentityFile.*localhost
  IdentityFile ~/.ssh/localhost/id_rsa
```

Since that file doesn't exist, I encounter an error when attempting to use fabric:

```
$ fab update
Traceback (most recent call last):
  File "/Users/jaraco/.local/bin/fab", line 8, in <module>
    sys.exit(program.run())
  File "/Users/jaraco/.local/pipx/venvs/fabric/lib/python3.10/site-packages/invoke/program.py", line 384, in run
    self.execute()
  File "/Users/jaraco/.local/pipx/venvs/fabric/lib/python3.10/site-packages/invoke/program.py", line 566, in execute
    executor.execute(*self.tasks)
  File "/Users/jaraco/.local/pipx/venvs/fabric/lib/python3.10/site-packages/invoke/executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "/Users/jaraco/.local/pipx/venvs/fabric/lib/python3.10/site-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/Users/jaraco/code/main/recapturedocs/fabfile.py", line 90, in update
    install(c)
  File "/Users/jaraco/code/main/recapturedocs/fabfile.py", line 98, in install
    c.run(f'git clone https://github.com/jaraco/{project} || echo -n')
  File "<decorator-gen-3>", line 2, in run
  File "/Users/jaraco/.local/pipx/venvs/fabric/lib/python3.10/site-packages/fabric/connection.py", line 29, in opens
    self.open()
  File "/Users/jaraco/.local/pipx/venvs/fabric/lib/python3.10/site-packages/fabric/connection.py", line 636, in open
    self.client.connect(**kwargs)
  File "/Users/jaraco/.local/pipx/venvs/fabric/lib/python3.10/site-packages/paramiko/client.py", line 435, in connect
    self._auth(
  File "/Users/jaraco/.local/pipx/venvs/fabric/lib/python3.10/site-packages/paramiko/client.py", line 678, in _auth
    key = self._key_from_filepath(
  File "/Users/jaraco/.local/pipx/venvs/fabric/lib/python3.10/site-packages/paramiko/client.py", line 588, in _key_from_filepath
    key = klass.from_private_key_file(key_path, password)
  File "/Users/jaraco/.local/pipx/venvs/fabric/lib/python3.10/site-packages/paramiko/pkey.py", line 249, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/Users/jaraco/.local/pipx/venvs/fabric/lib/python3.10/site-packages/paramiko/rsakey.py", line 64, in __init__
    self._from_private_key_file(filename, password)
  File "/Users/jaraco/.local/pipx/venvs/fabric/lib/python3.10/site-packages/paramiko/rsakey.py", line 190, in _from_private_key_file
    data = self._read_private_key_file("RSA", filename, password)
  File "/Users/jaraco/.local/pipx/venvs/fabric/lib/python3.10/site-packages/paramiko/pkey.py", line 321, in _read_private_key_file
    with open(filename, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jaraco/.ssh/localhost/id_rsa'
```

**Comment by jaraco** [comment]
This issue still affects me, and the workaround is messy because of the way that there's no entry point for fabric tasks (each fabric task needs the workaround). What will it take to get a fix for this issue?
