### ISSUE TITLE
RHEL 7.8 using FIPS

### ISSUE THREAD

**Issue by thukk** [fabric/fabric#2092]
Since updating to RHEL 7.8, I cannot get fabric to connect to a host.  It looks like paramiko is using md5 to connect, which will not work with FIPS.  Is there a way to force no using md5?

I get the following error when connecting to a host -

> Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/fabric/main.py", line 763, in main
    *args, **kwargs
  File "/usr/local/lib64/python3.6/site-packages/fabric/tasks.py", line 387, in execute
    multiprocessing
  File "/usr/local/lib64/python3.6/site-packages/fabric/tasks.py", line 277, in _execute
    return task.run(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/home/backup_admin/Documents/fabfile.py", line 101, in update
    sudo("subscription-manager attach", pty=True)
  File "/usr/local/lib64/python3.6/site-packages/fabric/network.py", line 692, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/fabric/operations.py", line 1153, in sudo
    capture_buffer_size=capture_buffer_size,
  File "/usr/local/lib64/python3.6/site-packages/fabric/operations.py", line 935, in _run_command
    channel=default_channel(), command=wrapped_command, pty=pty,
  File "/usr/local/lib64/python3.6/site-packages/fabric/state.py", line 435, in default_channel
    chan = _open_session()
  File "/usr/local/lib64/python3.6/site-packages/fabric/state.py", line 416, in _open_session
    transport = connections[env.host_string].get_transport()
  File "/usr/local/lib64/python3.6/site-packages/fabric/network.py", line 156, in __getitem__
    self.connect(key)
  File "/usr/local/lib64/python3.6/site-packages/fabric/network.py", line 148, in connect
    user, host, port, cache=self, seek_gateway=seek_gateway)
  File "/usr/local/lib64/python3.6/site-packages/fabric/network.py", line 478, in connect
    client.connect(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 416, in connect
    self, server_hostkey_name, server_key
  File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 805, in missing_host_key
    key.get_name(), hostname, hexlify(key.get_fingerprint())
  File "/usr/local/lib/python3.6/site-packages/paramiko/pkey.py", line 180, in get_fingerprint
    return md5(self.asbytes()).digest()
ValueError: error:060800A3:digital envelope routines:EVP_DigestInit_ex:disabled for fips

**Comment by dfresh613** [comment]
The underlying root cause of this is the paramiko library does not yet support working with sha256/512 for hostkeys, only md5. md5 is no longer a fips compliant algorithm. There is a [PR open in the paramiko project](https://github.com/paramiko/paramiko/issues/396) which addresses this.

There does seem to be a possible workaround however, and that is to just disable the ssh host key auto add policy completely. Unfortunately, fabric makes[ this difficult as it always hardcodes the missing_host_key_policy on open()](https://github.com/fabric/fabric/blob/2.6.0/fabric/connection.py#L456), and there is no means of setting this through connect_kwargs.

Since we can not change the missing key policy before connecting, the only option that seems to work is to ignore the host key exception.

So running on a fips environment by disabling missing host key policy requires the user to do this:
```
from paramiko.client import MissingHostKeyPolicy
from fabric2 import Connection
c=Connection("ahost", user='auser', connect_kwargs=ckwargs)
try:
  c.open()
except ValueError as e:
  if "disabled for fips" in repr(e):
      c.client.set_missing_host_key_policy= MissingHostKeyPolicy()  # not really needed
  else:
    raise
# any subsequent calls should be successful 
c.run(command)
```
Not entirely sure why the host key add doesn't happen again after the first time it fails, but it seems to work.


Once paramiko updates the supported keys, [as well as their default auto_add policies to use sha instead of md5,](https://github.com/paramiko/paramiko/pull/1103) this problem should go away on its own.

However, I think it would be a good idea for fabric to support defining the missing host key policy before connecting to the remote host. [I've created an issue for that here ](https://github.com/fabric/fabric/issues/2138)
