### ISSUE TITLE
Error while trying to apply parallel execution in running python script using fab

### ISSUE THREAD

**Issue by Ekamaravind** [fabric/fabric#2099]
I am trying to run a fabric program to apply patching on multiple systems in parallel... It is by default working in picking up each host, but parallel is not working .

Tried options:
@parallel in the code before the function
-P while executing the python script

Both failed. The error is as below:

C:\Users\Administrator>fab -u <username> -P update
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-p
ackages\fabric\main.py", line 758, in main
    execute(
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-p
ackages\fabric\tasks.py", line 412, in execute
    ran_jobs = jobs.run()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-p
ackages\fabric\job_queue.py", line 138, in run
    _advance_the_queue()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-p
ackages\fabric\job_queue.py", line 123, in _advance_the_queue
    job.start()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\multip
rocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\multip
rocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\multip
rocessing\context.py", line 326, in _Popen
    return Popen(process_obj)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\multip
rocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\multip
rocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object '_execute.<locals>.inner'

C:\Users\Administrator>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\multip
rocessing\spawn.py", line 102, in spawn_main
    source_process = _winapi.OpenProcess(
OSError: [WinError 87] The parameter is incorrect

**Comment by graingert** [comment]
related: https://bugs.python.org/issue33725

```
  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object '_execute.<locals>.inner'
```

**Comment by graingert** [comment]
@Ekamaravind I believe this is an issue in "the other fabric": as this fabric doesn't have the job_queue file, that you see included in your traceback: https://github.com/mathiasertl/fabric/blob/master/fabric/job_queue.py#L94

**Comment by bitprophet** [comment]
This smells like a repeat of #489 which sounds like there's no great solution for 😞  besides checking out the 2.x line of Fabric and applying your own parallelism that works better under Windows (threads, etc).
