### ISSUE TITLE
I cant start Fabric Installer it shows following error

### ISSUE THREAD

**Issue by Namonato** [fabric/fabric#2116]
Hello, i`m trying to start fabric installer but i have an error, i`m not programmer, please help

Error code:

java.net.ConnectException: Connection refused: connect
    at java.net.DualStackPlainSocketImpl.connect0(Native Method)
    at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
    at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
    at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
    at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
    at java.net.PlainSocketImpl.connect(Unknown Source)
    at java.net.SocksSocketImpl.connect(Unknown Source)
    at java.net.Socket.connect(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
    at sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source)
    at sun.net.NetworkClient.doConnect(Unknown Source)
    at sun.net.www.http.HttpClient.openServer(Unknown Source)
    at sun.net.www.http.HttpClient.openServer(Unknown Source)
    at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
    at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
    at net.fabricmc.installer.util.MetaHandler.load(MetaHandler.java:45)
    at net.fabricmc.installer.InstallerGui.<init>(InstallerGui.java:43)
    at net.fabricmc.installer.InstallerGui.start(InstallerGui.java:62)
    at net.fabricmc.installer.Main.main(Main.java:83)

**Comment by paul-hammant** [comment]
Your're trying to connect to a domain:port. Can you **from the same source machine**, curl to the same destination domain:port ?

e.g.

```
$ curl github.com:443
curl: (52) Empty reply from server
$ curl github.com:22
curl: (52) Empty reply from server
$ curl github.com:23
curl: (7) Failed to connect to github.com port 1234: Operation timed out
```

Not your workstation or laptop, the same machine or VM as you're trying to do the fabric connection from.

**Comment by ploxiln** [comment]
wrong fabric, this repo is not related to https://github.com/FabricMC at all

**Comment by jamezrin** [comment]
This is amazing hahahaha

**Comment by davidjmemmett** [comment]
Hi, this does not appear to be related to Fabric (a Python package). Closing issue.
