### ISSUE TITLE
Refusing to be ambigous error

### ISSUE THREAD

**Issue by Dreamsorcerer** [fabric/fabric#2119]
Following the discussion at https://github.com/paramiko/paramiko/issues/1748?_pjax=%23js-repo-pjax-container
I'm trying to convert my code from Paramiko to Fabric. However, I am encountering errors which don't make any sense to me.

Previous code looks something like:
```
class SSHRemote():
    def __init__(self, config):
        self._ssh_client = ConfiguredSSHClient()
        self._connect_options = {}
        with suppress(KeyError):
            self._connect_options["key_filename"] = str(config["key"])

        host = config["host"]
        if "@" in host:
            user, host = host.split("@", maxsplit=1)
            self._connect_options["username"] = user
        self._connect_options["hostname"] = host
        self._ssh_client.connect(**self._connect_options)

    def _run(self, cmd, check=False, stream=False, stdin=None):
        if check or stdin:
            channel = self._ssh_client.get_transport().open_session()
            channel.exec_command(cmd)
            if stdin:
                p_in = channel.makefile_stdin("wb")
                copyfileobj(stdin, p_in, 2**20)
                p_in.close()
            return channel.recv_exit_status() == 0

        stdin, stdout, stderr = self._ssh_client.exec_command(cmd)
        return stdout if stream else stdout.read()
```

My attempt to convert this code looks something like:
```
class SSHRemote:
    def __init__(self, config):
        self._connect_options = {}
        with suppress(KeyError):
            self._connect_options["key_filename"] = str(config["key"])

        host = config["host"]
        if "@" in host:
            user, host = host.split("@", maxsplit=1)
            self._connect_options["username"] = user
        self._ssh_client = Connection(host, connect_kwargs=self._connect_options)

    def _run(self, cmd, check=False, stream=False, stdin=None):
        args = {}
        if stdin:
            args["in_stream"] = stdin
        if stream:
            stdout = io.StringIO()
            args["asynchronous"] = True
            args["out_stream"] = stdout

        result = self._ssh_client.run(cmd, **args)

        if check or stdin:
            return result.ok

        return stdout if stream else result.stdout
```

When running, this gives an error:
`ValueError: Refusing to be ambiguous: connect() kwarg 'username' was given both via regular arg and via connect_kwargs!`

This seems weird to me, as username is only mentioned in one place, in the connect_kwargs.

**Comment by Dreamsorcerer** [comment]
OK, I'm assuming the first problem is just that Fabric doesn't support passing username in the connect_kwargs at all, and it needs to be used in the positional parameters.

I'm now having an issue when including a stream with in_stream, which gives an error like:
```
Traceback (most recent call last):
  File "./btrfs_backup.py", line 263, in <module>
    r = args.func(args)
  File "./btrfs_backup.py", line 111, in sync
    _sync_backups_for_remote(remote)
  File "./btrfs_backup.py", line 143, in _sync_backups_for_remote
    _sync_backup(local, remote, backup)
  File "./btrfs_backup.py", line 194, in _sync_backup
    if not dest.receive(backup, stream):
  File "/home/s/Hacking/btrfs-backup/trunk/remotes.py", line 88, in receive
    return self._run(cmd, stdin=stream)
  File "/home/s/Hacking/btrfs-backup/trunk/remotes.py", line 202, in _run
    result = result.join()
  File "/usr/local/lib/python3.8/dist-packages/invoke/runners.py", line 1558, in join
    return self.runner._finish()
  File "/usr/local/lib/python3.8/dist-packages/invoke/runners.py", line 474, in _finish
    raise ThreadException(thread_exceptions)
invoke.exceptions.ThreadException: 
Saw 1 exceptions within threads (OSError):


Thread args: {'kwargs': {'echo': None,
            'input_': <_io.BufferedReader name=9>,
            'output': <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>},
 'target': <bound method Runner.handle_stdin of <fabric.runners.Remote object at 0x7f81c3fd6580>>}

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/dist-packages/invoke/util.py", line 233, in run
    super(ExceptionHandlingThread, self).run()

  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)

  File "/usr/local/lib/python3.8/dist-packages/invoke/runners.py", line 822, in handle_stdin
    self.write_proc_stdin(data)

  File "/usr/local/lib/python3.8/dist-packages/invoke/runners.py", line 960, in write_proc_stdin
    self._write_proc_stdin(data.encode(self.encoding))

  File "/usr/local/lib/python3.8/dist-packages/fabric/runners.py", line 67, in _write_proc_stdin
    return self.channel.sendall(data)

  File "/usr/local/lib/python3.8/dist-packages/paramiko/channel.py", line 846, in sendall
    sent = self.send(s)

  File "/usr/local/lib/python3.8/dist-packages/paramiko/channel.py", line 801, in send
    return self._send(s, m)

  File "/usr/local/lib/python3.8/dist-packages/paramiko/channel.py", line 1198, in _send
    raise socket.error("Socket is closed")

OSError: Socket is closed
```
