### ISSUE TITLE
invoke.exceptions.ThreadException / OSError: [Errno 25] Inappropriate ioctl for device

### ISSUE THREAD

**Issue by ilmoi** [fabric/fabric#2129]
I have a really weird situation where sometimes (ie its not determenistic behavior) I get this error from a piece of code using `fabric`:
```
Traceback (most recent call last):
  File "/Users/ilja/Dropbox/web_fe/GPULAND/code/backend/redis_/redis_utils.py", line 25, in task_runner
    return func(*args, **kwargs)
  File "/Users/ilja/Dropbox/web_fe/GPULAND/code/backend/aws2model/machine/machine_create.py", line 46, in async_create_machine
    prep_machine_for_jupyter(machine_id)
  File "/Users/ilja/Dropbox/web_fe/GPULAND/code/backend/aws2model/host/host.py", line 26, in prep_machine_for_jupyter
    check_package_installed(host, 'nginx', key_name)
  File "/Users/ilja/Dropbox/web_fe/GPULAND/code/backend/aws2model/host/host_utils.py", line 15, in check_package_installed
    res = exec_cmds_ec2(host, [f'systemctl status --no-pager {package}'], key_name)[0]
  File "/Users/ilja/Dropbox/web_fe/GPULAND/code/backend/host_management/host_utils.py", line 106, in exec_cmds_ec2
    response = exec_single_cmd(c, host, cmd)
  File "/Users/ilja/Dropbox/web_fe/GPULAND/code/backend/host_management/host_utils.py", line 90, in exec_single_cmd
    response = c.run(cmd, warn=True).stdout.strip()
  File "<decorator-gen-3>", line 2, in run
  File "/Users/ilja/.local/share/virtualenvs/backend-NlI2n20q/lib/python3.8/site-packages/fabric/connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "/Users/ilja/.local/share/virtualenvs/backend-NlI2n20q/lib/python3.8/site-packages/fabric/connection.py", line 721, in run
    return self._run(self._remote_runner(), command, **kwargs)
  File "/Users/ilja/.local/share/virtualenvs/backend-NlI2n20q/lib/python3.8/site-packages/invoke/context.py", line 101, in _run
    return runner.run(command, **kwargs)
  File "/Users/ilja/.local/share/virtualenvs/backend-NlI2n20q/lib/python3.8/site-packages/invoke/runners.py", line 363, in run
    return self._run_body(command, **kwargs)
  File "/Users/ilja/.local/share/virtualenvs/backend-NlI2n20q/lib/python3.8/site-packages/invoke/runners.py", line 422, in _run_body
    return self.make_promise() if self._asynchronous else self._finish()
  File "/Users/ilja/.local/share/virtualenvs/backend-NlI2n20q/lib/python3.8/site-packages/invoke/runners.py", line 474, in _finish
    raise ThreadException(thread_exceptions)
invoke.exceptions.ThreadException:
Saw 1 exceptions within threads (OSError):


Thread args: {'kwargs': {'echo': None,
            'input_': <_io.TextIOWrapper name='<stdin>' mode='r' encoding='utf-8'>,
            'output': <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>},
 'target': <bound method Runner.handle_stdin of <fabric.runners.Remote object at 0x10e107b20>>}

Traceback (most recent call last):

  File "/Users/ilja/.local/share/virtualenvs/backend-NlI2n20q/lib/python3.8/site-packages/invoke/util.py", line 233, in run
    super(ExceptionHandlingThread, self).run()

  File "/Users/ilja/.pyenv/versions/3.8.5/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)

  File "/Users/ilja/.local/share/virtualenvs/backend-NlI2n20q/lib/python3.8/site-packages/invoke/runners.py", line 813, in handle_stdin
    with character_buffered(input_):

  File "/Users/ilja/.pyenv/versions/3.8.5/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)

  File "/Users/ilja/.local/share/virtualenvs/backend-NlI2n20q/lib/python3.8/site-packages/invoke/terminals.py", line 176, in character_buffered
    or not stdin_is_foregrounded_tty(stream)

  File "/Users/ilja/.local/share/virtualenvs/backend-NlI2n20q/lib/python3.8/site-packages/invoke/terminals.py", line 139, in stdin_is_foregrounded_tty
    return os.getpgrp() == os.tcgetpgrp(stream.fileno())

OSError: [Errno 25] Inappropriate ioctl for device
```

I'm struggling to debug it on my own. What could possibly be causing this? 

If it matters, fabric is used inside of a job that's running inside of `redis-queue`. I don't believe RQ uses any sort of multithreading itself, so I'm not sure it's relevent.

**Comment by pegazik80** [comment]
Hi, I have the same problem, did you manage to solve yours?

**Comment by pegazik80** [comment]
For anyone else having this issue, it goes away when added option in_stream=False to run command:
`result = connection.run(cmd, in_stream=False)`

**Comment by ilmoi** [comment]
@pegazik80 I did, using the tip [here](http://www.pyinvoke.org/faq.html#i-m-getting-ioerror-inappropriate-ioctl-for-device-when-i-run-commands). But it looks like you discovered it independently:)

**Comment by davidjmemmett** [comment]
Perfect, thanks for looking into this, closing issue.
