### ISSUE TITLE
Pipe one connection into another

### ISSUE THREAD

**Issue by Dreamsorcerer** [fabric/fabric#2135]
Following the discussion at https://github.com/paramiko/paramiko/issues/1748?_pjax=%23js-repo-pjax-container
I've been trying to convert my code from Paramiko to Fabric. Currently I'm still struggling to pipe output from one connection to another in order to complete the transition.

Previous code looks something like:
```
class SSHRemote():
    def __init__(self, config):
        self._ssh_client = ConfiguredSSHClient()
        self._connect_options = {}
        with suppress(KeyError):
            self._connect_options["key_filename"] = str(config["key"])

        host = config["host"]
        if "@" in host:
            user, host = host.split("@", maxsplit=1)
            self._connect_options["username"] = user
        self._connect_options["hostname"] = host
        self._ssh_client.connect(**self._connect_options)

    def _run(self, cmd, check=False, stream=False, stdin=None):
        if check or stdin:
            channel = self._ssh_client.get_transport().open_session()
            channel.exec_command(cmd)
            if stdin:
                p_in = channel.makefile_stdin("wb")
                copyfileobj(stdin, p_in, 2**20)
                p_in.close()
            return channel.recv_exit_status() == 0

        stdin, stdout, stderr = self._ssh_client.exec_command(cmd)
        return stdout if stream else stdout.read()
```

My attempt to convert this code looks something like:
```
class SSHRemote:
    def __init__(self, config):
        self._connect_options = {}
        with suppress(KeyError):
            self._connect_options["key_filename"] = str(config["key"])

        host = config["host"]
        user = None
        if "@" in host:
            user, host = host.split("@", maxsplit=1)
        self._ssh_client = Connection(host, user, connect_kwargs=self._connect_options)

    def _run(self, cmd, check=False, stream=False, stdin=None):
        args = {"hide": "out"}
        if stdin:
            args["asynchronous"] = True
            args["in_stream"] = stdin
        if stream:
            stdout = io.BytesIO()
            args["asynchronous"] = True
            args["out_stream"] = stdout

        result = self._ssh_client.run(cmd, **args)

        if check or stdin:
            if stdin:
                result = result.join()
            return result.ok

        return stdout if stream else result.stdout.encode()
```

This ends up being used something like:
```
stream = src._run(cmd, stream=True)
dest._run(cmd, stdin=stream)
```

When running, this gives an error:
```
Traceback (most recent call last):
  File "./btrfs_backup.py", line 263, in <module>
    r = args.func(args)
  File "./btrfs_backup.py", line 111, in sync
    _sync_backups_for_remote(remote)
  File "./btrfs_backup.py", line 143, in _sync_backups_for_remote
    _sync_backup(local, remote, backup)
  File "./btrfs_backup.py", line 194, in _sync_backup
    if not dest.receive(backup, stream):
  File "/home/s/Hacking/btrfs-backup/trunk/remotes.py", line 88, in receive
    return self._run(cmd, stdin=stream)
  File "/home/s/Hacking/btrfs-backup/trunk/remotes.py", line 203, in _run
    result = result.join()
  File "/usr/local/lib/python3.8/dist-packages/invoke/runners.py", line 1558, in join
    return self.runner._finish()
  File "/usr/local/lib/python3.8/dist-packages/invoke/runners.py", line 489, in _finish
    raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: 'btrfs receive /home/backup-laptop/root'

Exit code: 1

Stdout:



Stderr:

ERROR: empty stream is not considered valid
```

I've played around and tried a few different things, but have not found any way to make this work correctly.

**Comment by Dreamsorcerer** [comment]
Just thinking this over, the main way I'm using this at the moment is actually streaming a local process into the server connection.

So, in `stream = src._run(cmd, stream=True)`, stream is the result of:
```
proc = subprocess.Popen(cmd, bufsize=2**20, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
if stream:
    return proc.stdout
```

**Comment by Dreamsorcerer** [comment]
I've cloned all three of fabric, paramiko and invoke and done a bunch of debugging. I've finally found the major issue. invoke encodes and then decodes the binary data, which screws everything up as I'm streaming binary data that should not have any meaning attached to it.

https://github.com/pyinvoke/invoke/issues/818
