### ISSUE TITLE
Fabric fails to connect over SSH where paramiko succeeds

### ISSUE THREAD

**Issue by sleepygarden** [fabric/fabric#2140]
I'm trying to understand why only I on my team can't using Fabric's Connection to connect to a remote server. I can SSH into it, and use paramiko to access it with no issues. The only difference I can see is that Fabric is using a different `HostKey` from paramiko, and based on paramiko's logs both appear to be ignoring my `look_for_keys=False` and `allows_agent=False`. Is there a way to force Fabric to use the different HostKey? Am I misunderstanding what `look_for_keys` and `allows_agent` do? I assume they aren't working because paramiko logs report that it's attempting to use keys to connect.

Instead of connecting, I receive an exception: 
`Unknown exception: q must be exactly 160, 224, or 256 bits long`

Below is error reproduction code:
```
@task
def reproduce_error(c):
    paramiko.util.log_to_file("paramiko_log", level = "DEBUG")

    username = "hello"
    password = "world"
    hostname = "the.secret.host.name"
    port = "not 22"

    # works
    client = paramiko.client.SSHClient()
    client.load_system_host_keys()
    client.connect(hostname, port = port, username=username, password=password)
    stdin, stdout, stderr = client.exec_command("scutil --get LocalHostName")
    print(stdout.read())
    
    # does not work
    connect_kwargs={"password": password, "look_for_keys": False, "allow_agent": False}
    config = Config(overrides={'sudo': {'password': password}})
    connection = Connection(hostname, port=port, user=username, forward_agent=False, connect_kwargs=connect_kwargs, config=config)
    connection.load_ssh_configs=False
    print(connection.run('scutil --get LocalHostName'))
```

Logs from paramiko:

```
///// Working connection with plain paramiko
DEB [20210211-15:56:59.781] thr=1   paramiko.transport: starting thread (client mode): 0x1cd6bc70
DEB [20210211-15:56:59.781] thr=1   paramiko.transport: Local version/idstring: SSH-2.0-paramiko_2.7.2
DEB [20210211-15:56:59.855] thr=1   paramiko.transport: Remote version/idstring: SSH-2.0-OpenSSH_8.1
INF [20210211-15:56:59.855] thr=1   paramiko.transport: Connected (version 2.0, client OpenSSH_8.1)
DEB [20210211-15:56:59.916] thr=1   paramiko.transport: kex algos:['curve25519-sha256', 'curve25519-sha256@libssh.org', 'ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp521', 'diffie-hellman-group-exchange-sha256', 'diffie-hellman-group16-sha512', 'diffie-hellman-group18-sha512', 'diffie-hellman-group14-sha256', 'diffie-hellman-group14-sha1'] server key:['rsa-sha2-512', 'rsa-sha2-256', 'ssh-rsa', 'ecdsa-sha2-nistp256', 'ssh-ed25519'] client encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] server encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] client mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] server mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] client compress:['none', 'zlib@openssh.com'] server compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
DEB [20210211-15:56:59.916] thr=1   paramiko.transport: Kex agreed: curve25519-sha256@libssh.org

///// this is different
DEB [20210211-15:56:59.916] thr=1   paramiko.transport: HostKey agreed: ecdsa-sha2-nistp256
/////

DEB [20210211-15:56:59.916] thr=1   paramiko.transport: Cipher agreed: aes128-ctr
DEB [20210211-15:56:59.917] thr=1   paramiko.transport: MAC agreed: hmac-sha2-256
DEB [20210211-15:56:59.917] thr=1   paramiko.transport: Compression agreed: none
DEB [20210211-15:56:59.962] thr=1   paramiko.transport: kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
DEB [20210211-15:56:59.962] thr=1   paramiko.transport: Switch to new keys ...
DEB [20210211-15:56:59.988] thr=2   paramiko.transport: Trying discovered key b'082077......' in /Users/me/.ssh/id_rsa
DEB [20210211-15:57:00.032] thr=1   paramiko.transport: userauth is OK
INF [20210211-15:57:00.114] thr=1   paramiko.transport: Authentication (publickey) failed.
DEB [20210211-15:57:00.150] thr=1   paramiko.transport: userauth is OK
INF [20210211-15:57:03.351] thr=1   paramiko.transport: Authentication (password) successful!
DEB [20210211-15:57:03.352] thr=2   paramiko.transport: [chan 0] Max packet in: 32768 bytes
DEB [20210211-15:57:03.352] thr=1   paramiko.transport: Received global request "hostkeys-00@openssh.com"
DEB [20210211-15:57:03.352] thr=1   paramiko.transport: Rejecting "hostkeys-00@openssh.com" global request from server.
DEB [20210211-15:57:03.411] thr=1   paramiko.transport: [chan 0] Max packet out: 32768 bytes
DEB [20210211-15:57:03.411] thr=1   paramiko.transport: Secsh channel 0 opened.
DEB [20210211-15:57:03.479] thr=1   paramiko.transport: [chan 0] Sesch channel 0 request ok
DEB [20210211-15:57:03.572] thr=1   paramiko.transport: [chan 0] EOF received (0)
DEB [20210211-15:57:03.572] thr=1   paramiko.transport: [chan 0] EOF sent (0)
```

```
///// failing Fabric Connection
DEB [20210211-15:57:03.609] thr=3   paramiko.transport: starting thread (client mode): 0x1edc1490
DEB [20210211-15:57:03.609] thr=3   paramiko.transport: Local version/idstring: SSH-2.0-paramiko_2.7.2
DEB [20210211-15:57:03.705] thr=3   paramiko.transport: Remote version/idstring: SSH-2.0-OpenSSH_8.1
INF [20210211-15:57:03.705] thr=3   paramiko.transport: Connected (version 2.0, client OpenSSH_8.1)
DEB [20210211-15:57:03.752] thr=3   paramiko.transport: kex algos:['curve25519-sha256', 'curve25519-sha256@libssh.org', 'ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp521', 'diffie-hellman-group-exchange-sha256', 'diffie-hellman-group16-sha512', 'diffie-hellman-group18-sha512', 'diffie-hellman-group14-sha256', 'diffie-hellman-group14-sha1'] server key:['rsa-sha2-512', 'rsa-sha2-256', 'ssh-rsa', 'ecdsa-sha2-nistp256', 'ssh-ed25519'] client encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] server encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] client mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] server mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] client compress:['none', 'zlib@openssh.com'] server compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
DEB [20210211-15:57:03.752] thr=3   paramiko.transport: Kex agreed: curve25519-sha256@libssh.org

///// this is different
DEB [20210211-15:57:03.752] thr=3   paramiko.transport: HostKey agreed: ssh-ed25519
/////

DEB [20210211-15:57:03.752] thr=3   paramiko.transport: Cipher agreed: aes128-ctr
DEB [20210211-15:57:03.752] thr=3   paramiko.transport: MAC agreed: hmac-sha2-256
DEB [20210211-15:57:03.752] thr=3   paramiko.transport: Compression agreed: none
DEB [20210211-15:57:03.800] thr=3   paramiko.transport: kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
DEB [20210211-15:57:03.801] thr=3   paramiko.transport: Switch to new keys ...

///// this is different
DEB [20210211-15:57:03.801] thr=2   paramiko.transport: Adding ssh-ed25519 host key for [hidden_host_name]:<hide_port>: b'f1ed7.......'
/////

DEB [20210211-15:57:03.826] thr=2   paramiko.transport: Trying discovered key b'082077.......' in /Users/me/.ssh/id_rsa
DEB [20210211-15:57:03.864] thr=3   paramiko.transport: userauth is OK
INF [20210211-15:57:03.947] thr=3   paramiko.transport: Authentication (publickey) failed.

///// this is different
DEB [20210211-15:57:03.947] thr=2   paramiko.transport: Trying discovered key b'8afe......' in /Users/me/.ssh/id_rsa
DEB [20210211-15:57:03.984] thr=3   paramiko.transport: userauth is OK
ERR [20210211-15:57:03.984] thr=3   paramiko.transport: Unknown exception: q must be exactly 160, 224, or 256 bits long
ERR [20210211-15:57:03.990] thr=3   paramiko.transport: Traceback (most recent call last):
ERR [20210211-15:57:03.990] thr=3   paramiko.transport:   File "/usr/local/lib/python3.9/site-packages/paramiko/transport.py", line 2109, in run
ERR [20210211-15:57:03.990] thr=3   paramiko.transport:     handler(self.auth_handler, m)
ERR [20210211-15:57:03.990] thr=3   paramiko.transport:   File "/usr/local/lib/python3.9/site-packages/paramiko/auth_handler.py", line 298, in _parse_service_accept
ERR [20210211-15:57:03.990] thr=3   paramiko.transport:     sig = self.private_key.sign_ssh_data(blob)
ERR [20210211-15:57:03.990] thr=3   paramiko.transport:   File "/usr/local/lib/python3.9/site-packages/paramiko/dsskey.py", line 108, in sign_ssh_data
ERR [20210211-15:57:03.990] thr=3   paramiko.transport:     key = dsa.DSAPrivateNumbers(
ERR [20210211-15:57:03.990] thr=3   paramiko.transport:   File "/usr/local/lib/python3.9/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 244, in private_key
ERR [20210211-15:57:03.990] thr=3   paramiko.transport:     return backend.load_dsa_private_numbers(self)
ERR [20210211-15:57:03.990] thr=3   paramiko.transport:   File "/usr/local/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 826, in load_dsa_private_numbers
ERR [20210211-15:57:03.990] thr=3   paramiko.transport:     dsa._check_dsa_private_numbers(numbers)
ERR [20210211-15:57:03.990] thr=3   paramiko.transport:   File "/usr/local/lib/python3.9/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 282, in _check_dsa_private_numbers
ERR [20210211-15:57:03.990] thr=3   paramiko.transport:     _check_dsa_parameters(parameters)
ERR [20210211-15:57:03.990] thr=3   paramiko.transport:   File "/usr/local/lib/python3.9/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 274, in _check_dsa_parameters
ERR [20210211-15:57:03.990] thr=3   paramiko.transport:     raise ValueError("q must be exactly 160, 224, or 256 bits long")
ERR [20210211-15:57:03.990] thr=3   paramiko.transport: ValueError: q must be exactly 160, 224, or 256 bits long
ERR [20210211-15:57:03.990] thr=3   paramiko.transport: 
```

Versions: 
```
$ pip freeze
attrs==20.3.0
bcrypt==3.2.0
cffi==1.14.4
cryptography==3.4.4
fabric==2.6.0
iniconfig==1.1.1
invoke==1.5.0
numpy==1.20.1
packaging==20.9
paramiko==2.7.2
pathlib2==2.3.5
pluggy==0.13.1
py==1.10.0
pycparser==2.20
PyNaCl==1.4.0
pyparsing==2.4.7
pytest==6.2.2
six==1.15.0
toml==0.10.2
```

**Comment by sleepygarden** [comment]
I eventually fixed this, I needed to pass in an empty `SSHConfig` to force Fabric to ignore my `IdentityFile` in ~/.ssh/config. I would have expected `looks_for_keys=False` to prevent Fabric/paramiko from using keys, but evidently the IdentityFile overrides that. What I still find puzzling is when both paramiko and Fabric were using the IdentityFile, paramiko didn't attempt an invalid connection and Fabric did.
