### ISSUE TITLE
Stuck connections can cause busy waits

### ISSUE THREAD

**Issue by bjourne** [fabric/fabric#2146]
I'm using fabric to control long-running processes over ssh. The connection sometimes fails for various reasons and this can cause fabric to get stuck in a busy wait loop with the following traceback:
```^CTraceback (most recent call last):
  File "/home/bjourne/.local/lib/python3.9/site-packages/invoke/runners.py", line 363, in run
    return self._run_body(command, **kwargs)
  File "/home/bjourne/.local/lib/python3.9/site-packages/invoke/runners.py", line 422, in _run_body
    return self.make_promise() if self._asynchronous else self._finish()
  File "/home/bjourne/.local/lib/python3.9/site-packages/invoke/runners.py", line 460, in _finish
    thread.join(self._thread_join_timeout(target))
  File "/usr/lib/python3.9/threading.py", line 1033, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.9/threading.py", line 1049, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bjourne/.local/lib/python3.9/site-packages/paramiko/proxy.py", line 79, in send
    self.process.stdin.write(content)
BrokenPipeError: [Errno 32] Broken pipe
```
That the connection is stuck is fine of course, but it also consumes 100% cpu which is a bug.

**Comment by davidjmemmett** [comment]
Hi @bjourne, could you please provide [some additional information](http://www.contribution-guide.org/) to help us reproduce your issue?


**What to put in your bug report**

Make sure your report gets the attention it deserves: bug reports with missing information may be ignored or punted back to you, delaying a fix. The below constitutes a bare minimum; more info is almost always better:

- What version of the core programming language interpreter/compiler are you using? For example, if it’s a Python project, are you using Python 2.7.3? Python 3.3.1? PyPy 2.0?
- What operating system are you on? Windows? (Vista? 7? 32-bit? 64-bit?) Mac OS X? (10.7.4? 10.9.0?) Linux? (Which distro? Which version of that distro? 32 or 64 bits?) Again, more detail is better.
- Which version or versions of the software are you using? Ideally, you followed the advice above and have ruled out (or verified that the problem exists in) a few different versions.
- How can the developers recreate the bug on their end? If possible, include a copy of your code, the command you used to invoke it, and the full output of your run (if applicable.)
A common tactic is to pare down your code until a simple (but still bug-causing) “base case” remains. Not only can this help you identify problems which aren’t real bugs, but it means the developer can get to fixing the bug faster.

**Comment by bjourne** [comment]
Python 3.91 on Arch Linux, Fabric 2.5.0, and Invoke 1.5.0. I cannot provide an mwe since the bug happens infrequently and only on Google colab. Something gets stuck in a busy wait.

**Comment by davidjmemmett** [comment]
This is going to make it very difficult to track down. Can you provide the snippet of the fabfile which is failing?

**Comment by bjourne** [comment]
I'm not using a fabfile. Only
```
conn = Connection(host, 'root', port, connect_kwargs = connect_kwargs)
conn.run(script, pty = True)
```
where script is just a Python script. If Fabric has some debug mode I can try turning that on to collect debugging output.

**Comment by davidjmemmett** [comment]
What is it you're running? A service control manager such as `systemctl` or `supervisorctl`? I say this as I wouldn't recommend relying on SSH whatsoever for any sort of long-running processes, and don't want to assume you are.

**Comment by bjourne** [comment]
Python script for machine learning. It's the only way to do it on Google Colab.

**Comment by davidjmemmett** [comment]
I can try `sleep`ing and disabling the network interface - see if that reproduces it.

**Comment by davidjmemmett** [comment]
No luck so far I'm afraid. Every attempt I've tried can be killed easily with a SIGINT. I even tried it with an EC2 instance and terminated it. Running with strace, I can see endless socket selects (as expected), but this doesn't cause my CPU to go crazy. Joining a thread should never cause the CPU to spin; can you show me where you're seeing this (in `htop`, `top`, `ps aux` etc)?

**Comment by bjourne** [comment]
I'm seeing it in top and htop. Here is a strace of the hung (busy waiting) python process:
```
pselect6(0, NULL, NULL, NULL, {tv_sec=0, tv_nsec=10000000}, NULL) = 0 (Timeout)
futex(0x7fec3e179f6c, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7fec3e179f70, FUTEX_WAKE_PRIVATE, 1) = 1
pselect6(0, NULL, NULL, NULL, {tv_sec=0, tv_nsec=10000000}, NULL) = 0 (Timeout)
futex(0x7fec3e179f6c, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7fec3e179f70, FUTEX_WAKE_PRIVATE, 1) = 1
pselect6(0, NULL, NULL, NULL, {tv_sec=0, tv_nsec=10000000}, NULL) = 0 (Timeout)
futex(0x7fec3e179f6c, FUTEX_WAIT_BITSET_PRIVATE, 0, {tv_sec=186017, tv_nsec=124201120}, FUTEX_BITSET_MATCH_ANY) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x7fec3e179f70, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7fec3e179f70, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7fec3e179f70, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7fec3e179f70, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7fec3e179f6c, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7fec3e179f70, FUTEX_WAKE_PRIVATE, 1) = 1
pselect6(0, NULL, NULL, NULL, {tv_sec=0, tv_nsec=10000000}, NULL) = 0 (Timeout)
futex(0x7fec3e179f68, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7fec3e179f70, FUTEX_WAKE_PRIVATE, 1) = 1
pselect6(0, NULL, NULL, NULL, {tv_sec=0, tv_nsec=10000000}, NULL) = 0 (Timeout)
futex(0x7fec3e179f68, FUTEX_WAIT_BITSET_PRIVATE, 0, {tv_sec=186017, tv_nsec=145550142}, FUTEX_BITSET_MATCH_ANY) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x7fec3e179f70, FUTEX_WAIT_PRIVATE, 2, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x7fec3e179f70, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7fec3e179f70, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7fec3e179f68, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7fec3e179f70, FUTEX_WAKE_PRIVATE, 1) = 1
pselect6(0, NULL, NULL, NULL, {tv_sec=0, tv_nsec=10000000}, NULL) = 0 (Timeout)
```
It repeats over and over.

**Comment by davidjmemmett** [comment]
Hi @bjourne,

Did you get anywhere with this?

Cheers,
David

**Comment by bjourne** [comment]
No, but it is still happening all the time. Here is parts of the traceback I got this morning:
```
    maybe_arr = self._numpy()  # pylint: disable=protected-access
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 1039, in _numpy
    six.raise_from(core._status_to_exception(e.code, e.message), None)  # pylint: disable=protected-access
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnavailableError: Socket closed
^CTraceback (most recent call last):
  File "/home/bjourne/.local/lib/python3.9/site-packages/invoke/runners.py", line 437, in _finish
    self.wait()
  File "/home/bjourne/.local/lib/python3.9/site-packages/invoke/runners.py", line 946, in wait
    time.sleep(self.input_sleep)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bjourne/.local/lib/python3.9/site-packages/paramiko/proxy.py", line 79, in send
    self.process.stdin.write(content)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bjourne/.local/lib/python3.9/site-packages/invoke/runners.py", line 444, in _finish
    self.send_interrupt(e)
  File "/home/bjourne/.local/lib/python3.9/site-packages/fabric/runners.py", line 88, in send_interrupt
    self.channel.send(u"\x03")
  File "/home/bjourne/.local/lib/python3.9/site-packages/paramiko/channel.py", line 801, in send
    return self._send(s, m)
  File "/home/bjourne/.local/lib/python3.9/site-packages/paramiko/channel.py", line 1208, in _send
    self.transport._send_user_message(m)
  File "/home/bjourne/.local/lib/python3.9/site-packages/paramiko/transport.py", line 1863, in _send_user_message
    self._send_message(data)
  File "/home/bjourne/.local/lib/python3.9/site-packages/paramiko/transport.py", line 1839, in _send_message
    self.packetizer.send_message(data)
  File "/home/bjourne/.local/lib/python3.9/site-packages/paramiko/packet.py", line 431, in send_message
    self.write_all(out)
  File "/home/bjourne/.local/lib/python3.9/site-packages/paramiko/packet.py", line 336, in write_all
    n = self.__socket.send(out)
  File "/home/bjourne/.local/lib/python3.9/site-packages/paramiko/proxy.py", line 85, in send
    raise ProxyCommandFailure(" ".join(self.cmd), e.strerror)
paramiko.ssh_exception.ProxyCommandFailure: ProxyCommand("/home/bjourne/tmp/cloudflared access ssh --hostname xi-while-thrown-ranging.trycloudflare.com") returned nonzero exit status: Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bjourne/.local/lib/python3.9/site-packages/invoke/runners.py", line 363, in run
    return self._run_body(command, **kwargs)
  File "/home/bjourne/.local/lib/python3.9/site-packages/invoke/runners.py", line 422, in _run_body
    return self.make_promise() if self._asynchronous else self._finish()
  File "/home/bjourne/.local/lib/python3.9/site-packages/invoke/runners.py", line 460, in _finish
    thread.join(self._thread_join_timeout(target))
  File "/usr/lib/python3.9/threading.py", line 1033, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.9/threading.py", line 1049, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bjourne/.local/lib/python3.9/site-packages/paramiko/proxy.py", line 79, in send
    self.process.stdin.write(content)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bjourne/pubwork/musicgen/tools/colab-tool.py", line 128, in <module>
    main()
  File "/home/bjourne/pubwork/musicgen/tools/colab-tool.py", line 121, in main
    run_python_file(conn, root_path, str(src), args['<args>'])
  File "/home/bjourne/pubwork/musicgen/tools/colab-tool.py", line 76, in run_python_file
    conn.run(script, pty = True)
  File "<decorator-gen-3>", line 2, in run
  File "/home/bjourne/.local/lib/python3.9/site-packages/fabric/connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "/home/bjourne/.local/lib/python3.9/site-packages/fabric/connection.py", line 721, in run
    return self._run(self._remote_runner(), command, **kwargs)
  File "/home/bjourne/.local/lib/python3.9/site-packages/invoke/context.py", line 102, in _run
    return runner.run(command, **kwargs)
  File "/home/bjourne/.local/lib/python3.9/site-packages/invoke/runners.py", line 366, in run
    self._stop_everything()
  File "/home/bjourne/.local/lib/python3.9/site-packages/invoke/runners.py", line 371, in _stop_everything
    self.stop()
  File "/home/bjourne/.local/lib/python3.9/site-packages/fabric/runners.py", line 101, in stop
    self.channel.close()
  File "/home/bjourne/.local/lib/python3.9/site-packages/paramiko/channel.py", line 671, in close
    self.transport._send_user_message(m)
  File "/home/bjourne/.local/lib/python3.9/site-packages/paramiko/transport.py", line 1863, in _send_user_message
    self._send_message(data)
  File "/home/bjourne/.local/lib/python3.9/site-packages/paramiko/transport.py", line 1839, in _send_message
    self.packetizer.send_message(data)
  File "/home/bjourne/.local/lib/python3.9/site-packages/paramiko/packet.py", line 431, in send_message
    self.write_all(out)
  File "/home/bjourne/.local/lib/python3.9/site-packages/paramiko/packet.py", line 336, in write_all
    n = self.__socket.send(out)
  File "/home/bjourne/.local/lib/python3.9/site-packages/paramiko/proxy.py", line 85, in send
    raise ProxyCommandFailure(" ".join(self.cmd), e.strerror)
paramiko.ssh_exception.ProxyCommandFailure: ProxyCommand("/home/bjourne/tmp/cloudflared access ssh --hostname xi-while-thrown-ranging.trycloudflare.com") returned nonzero exit status: Broken pipe
```

`time.sleep(self.input_sleep)` in `runners.py` could be part of the busy loop.

**Comment by davidjmemmett** [comment]
How long does it take for this to happen?

**Comment by bjourne** [comment]
It varies. 2-6 hours.

**Comment by davidjmemmett** [comment]
Okay, I'm of the mind that whilst this _could_ be handled better - without an easy way for us to reproduce this and add tests to ensure this issue is fixed, it's probably going to have to go into the "won't fix" pile unfortunately. It looks like you're using a non-standard platform and using fabric in a way that it isn't really intended for (taking care of rather long-running tasks).

On second thoughts, I've just noticed that you're passing some args to Paramiko via `connect_kwargs` which may be pertinent to this issue, namely the ProxyCommand jumps out.

Cheers,
David
