### ISSUE TITLE
Mysterious Crash

### ISSUE THREAD

**Issue by DanielGolan-mc** [fabric/fabric#2150]
Happened during the creation of the boson mod. what is going on? link to [my mod during the crash](https://github.com/DanielGolan-mc/boson/tree/Crash_15.3)
```
---- Minecraft Crash Report ----
// My bad.

Time: 15.3.2021, 10:24
Description: Initializing game

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:550)
	at net.minecraft.client.main.Main.main(Main.java:178)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method afterTerrainSolid(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in fabric-rendering-v1.mixins.json:MixinWorldRenderer failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap fabric-rendering-v1-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 16 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:550)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:178)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- System Details --
Details:
	Minecraft Version: 21w10a
	Minecraft Version ID: 21w10a
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 15.0.2, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 615073504 bytes (586 MB) / 1734344704 bytes (1654 MB) up to 4257218560 bytes (4060 MB)
	CPUs: 8
	JVM Flags: 0 total; 
	Fabric Mods: 
		boson: Boson 1.0.0
		fabric: Fabric API 0.31.2+1.17
		fabric-api-base: Fabric API Base 0.2.1+524a2e8559
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.4+1eb2670e59
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+92519afa59
		fabric-command-api-v1: Fabric Command API (v1) 1.1.0+f9d6353a59
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa59
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+524a2e8559
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+92519afa59
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+92519afa59
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+524a2e8559
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+92519afa59
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.6+0d6fddee59
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa59
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+92519afa59
		fabric-item-api-v1: Fabric Item API (v1) 1.2.3+36b77c3e59
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+92519afa59
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+524a2e8559
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e59
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.3+40e100eb59
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+92519afa59
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa59
		fabric-models-v0: Fabric Models (v0) 0.2.1+92519afa59
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.5+7268309e59
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.9+40e100eb59
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa59
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.5+40e100eb59
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+92519afa59
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+92519afa59
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.5+92519afa59
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+92519afa59
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.6+92519afa59
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.1.0+2a1dabb659
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+92519afa59
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+92519afa59
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa59
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+92519afa59
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.4+1eb2670e59
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+e568618059
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.6+40e100eb59
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.6+7268309e59
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.2+92519afa59
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+92519afa59
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.9+36b77c3e59
		fabricloader: Fabric Loader 0.11.3
		java: OpenJDK 64-Bit Server VM 15
		minecraft: Minecraft 1.17-alpha.21.10.a
	Launched Version: Fabric
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) UHD Graphics 620 GL version 3.2.0 - Build 27.20.100.8681, Intel
	GL Caps: Using framebuffer using OpenGL 3.2
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 8x Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
```

**Comment by davidjmemmett** [comment]
You have the wrong project I'm afraid. Closing issue.

**Comment by DanielGolan-mc** [comment]
> You have the wrong project I'm afraid. Closing issue.

What do you mean I got the wrong project?

**Comment by davidjmemmett** [comment]
This is a Python library for automating SSH connectivity, nothing to do with Java or MineCraft.
