### ISSUE TITLE
Error reading SSH protocol banner

### ISSUE THREAD

**Issue by Gary-Armstrong** [fabric/fabric#2157]
I'm hoping someone here can guide me in the right direction to solve a looping error.

I have some python:
```python
for name in instanceNames:
    print(f'\nChecking {name} ...')
    c = Connection(name)
        try:
            print('Exec hostname')
            r = c.run('hostname', warn=True)
            print(f'{r}')
        except:
            print('SSH session error')
```
Runs along fine until it hits a particular system and then:
```
Exception: Error reading SSH protocol banner
Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/paramiko/transport.py", line 2211, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/root/.local/lib/python3.7/site-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/root/.local/lib/python3.7/site-packages/paramiko/packet.py", line 622, in _read_timeout
    raise socket.timeout()
_socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/paramiko/transport.py", line 2039, in run
    self._check_banner()
  File "/root/.local/lib/python3.7/site-packages/paramiko/transport.py", line 2216, in _check_banner
    "Error reading SSH protocol banner" + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

Exception: Error reading SSH protocol banner
Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/paramiko/transport.py", line 2211, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/root/.local/lib/python3.7/site-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/root/.local/lib/python3.7/site-packages/paramiko/packet.py", line 622, in _read_timeout
    raise socket.timeout()
_socket.timeout

During handling of the above exception, another exception occurred:
...
```
This goes on until I CTRL-C, after which all other host items throw an exception.

I don't really care at the moment about the banner exception on that particular host (I will deal with that later) but for now I'd like to avoid the retries and subsequent failures. Any tips?

**Comment by davidjmemmett** [comment]
Hi @Gary-Armstrong,

It looks like you skipped the issue template, which asks some pertinent questions about your issue.

Could you please provide [some additional information](http://www.contribution-guide.org/) to help us reproduce your issue?


**What to put in your bug report**

Make sure your report gets the attention it deserves: bug reports with missing information may be ignored or punted back to you, delaying a fix. The below constitutes a bare minimum; more info is almost always better:

- What version of the Python interpreter are you using? Are you using an alternative interpreter such as PyPy?
- What operating system are you using both client & server-side?
- Are you using OpenSSH server or something else?
- Which version or versions of the software are you using?
- How can the developers recreate the bug on their end? If possible, include a copy of your code, the command you used to invoke it, and the full output of your run (if applicable.)
A common tactic is to pare down your code until a simple (but still bug-causing) “base case” remains. Not only can this help you identify problems which aren’t real bugs, but it means the developer can get to fixing the bug faster.

**Comment by Gary-Armstrong** [comment]
Ah, thanks for pointing that out. Not sure how I managed to skip the template, there is just the one green button when submitting.

**Due diligence**
I didn't see any issue that seemed relevant. I have spent a day or so searching the internet and squinting at the fabric docs, too. I could have missed something, though.

**Describe the bug**
Looping paramiko errors. Retries? Will repeat some above text for completeness.
Feed a list of hostnames into this:
```python
for name in instanceNames:
    print(f'\nChecking {name} ...')
    c = Connection(name)
        try:
            print('Exec hostname')
            r = c.run('hostname', warn=True)
            print(f'{r}')
        except:
            print('SSH session error')
```
Runs along fine until it hits a particular system and then:
```
Exception: Error reading SSH protocol banner
Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/paramiko/transport.py", line 2211, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/root/.local/lib/python3.7/site-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/root/.local/lib/python3.7/site-packages/paramiko/packet.py", line 622, in _read_timeout
    raise socket.timeout()
_socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/paramiko/transport.py", line 2039, in run
    self._check_banner()
  File "/root/.local/lib/python3.7/site-packages/paramiko/transport.py", line 2216, in _check_banner
    "Error reading SSH protocol banner" + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

Exception: Error reading SSH protocol banner
Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/paramiko/transport.py", line 2211, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/root/.local/lib/python3.7/site-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/root/.local/lib/python3.7/site-packages/paramiko/packet.py", line 622, in _read_timeout
    raise socket.timeout()
_socket.timeout

During handling of the above exception, another exception occurred:
...
```

**To Reproduce**
Feed a list of hostnames into the following:
```python
for name in instanceNames:
    print(f'\nChecking {name} ...')
    c = Connection(name)
        try:
            print('Exec hostname')
            r = c.run('hostname', warn=True)
            print(f'{r}')
        except:
            print('SSH session error')
```
I'm not sure what in the banner might trigger the failure but I'm not very concerned about that just now. I'd rather it continue on and provide a full report, after which I'll investigate individual systems.

That said, some smart person put ASCII color codes into the MOTD. Maybe that is a problem.

**Expected behaviour**
I expect that when there is a connection error, fabric will complain and the loop will move on to the next Connection(). I expect that later and concurrent Connection()s will succeed.

**Environment**

- What version of the Python interpreter are you using? Are you using an
alternative interpreter such as PyPy?
Docker image pypy:3.7-buster

- What operating system are you using both client & server-side?
Client: Docker Engine Community v20.10.5 on macos 11.2.3
Server: Various, mostly CentOS 7 and Amazon 2

- Are you using OpenSSH server or something else?
OpenSSH server of various vintages. Whatever comes with the OS.

- Which version or versions of the software are you using?
bcrypt==3.2.0
boto3==1.17.36
botocore==1.20.36
cryptography==3.4.6
fabric==2.6.0
invoke==1.5.0
jmespath==0.10.0
paramiko==2.7.2
pathlib2==2.3.5
PyNaCl==1.4.0
python-dateutil==2.8.1
s3transfer==0.3.6
six==1.15.0
urllib3==1.26.4
  - Have you already tried the latest release?
 Yes ... ?

  - Have you, or can you, try some older releases to pin down where the bug
  appeared?
I have not.

- How can the developers recreate the bug on their end? If possible, include a
  copy of your code, the command you used to invoke it, and the full output of
  your run (if applicable.)
Hopefully the above snips will suffice. I didn't do anything other than import fabric and open a Connection() as shown. Using a ~/.ssh/config if that matters, which works great up until it doesn't.

  - A common tactic is to pare down your code until a simple (but still
  bug-causing) “base case” remains. Not only can this help you identify
  problems which aren’t real bugs, but it means the developer can get to fixing
  the bug faster.
I agree completely. It really is just a list of hostnames passed to a for loop that calls Connection() once per hostname.

**Additional context**
Unsure. Ask questions!

**Comment by Gary-Armstrong** [comment]
I'll put the files in here just for fun.

Dockerfile:
```dockerfile
ARG runtag=3.7-buster
FROM pypy:$runtag
ARG runtag
LABEL baseimage=pypy:$runtag

WORKDIR /app
COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install --user -r requirements.txt

COPY list-instances.py .

ENTRYPOINT [ "pypy", "list-instances.py" ]
```

The python, with important part at bottom:
```python

import sys

import boto3
from botocore.config import Config as botoConfig
from botocore.exceptions import ClientError as botoClientErr
from botocore.exceptions import NoCredentialsError as botoNoCredErr

from fabric import Connection


def getInstances():
    '''Returns a list of instance data objects
        tagged Billing: FOD
        running state
    '''
    try:
        response = ec2client.describe_instances(
            Filters=[
                {
                    'Name': 'tag:Billing',
                    'Values': ['FOD']
                },
                {
                    'Name': 'instance-state-name',
                    'Values': ['running']
                }
            ]
        )
    except (botoNoCredErr, botoClientErr) as e:
        sys.exit(e)

    instances = []
    for r in response['Reservations']:
        instances.extend(r['Instances'])

    return instances


if __name__ == '__main__':
    useast1_config = botoConfig(
        region_name = 'us-east-1'
    )
    uswest2_config = botoConfig(
        region_name = 'us-west-2'
    )
    apsoutheast1_config = botoConfig(
        region_name = 'ap-southeast-1'
    )
    euwest1_config = botoConfig(
        region_name = 'eu-west-1'
    )

    for profile in ['sundev', 'sunqa', 'sunprod']:
        session = boto3.Session(profile_name=profile)
        print(f'\nAWS-Account={profile}')

        for region in [useast1_config, uswest2_config, apsoutheast1_config, euwest1_config]:

            ec2client = session.client('ec2', config=region)
            print(f'\nRegion={region.region_name}:')

            '''Get list of EC2 instances tagged Billing: FOD'''
            instances = getInstances()

            instanceNames = []

            for i in instances:
                for t in i['Tags']:
                    if t['Key'] == 'Name':
                        iname = t['Value']
                        instanceNames.append(iname)

            for name in instanceNames:
                print(name)
                print(f'\nChecking {name} ...')
                c = Connection(name)
                try:
                    print('Exec hostname')
                    r = c.run('hostname', warn=True)
                    print(f'{r}')
                except:
                    print('SSH session error')
```

**Comment by davidjmemmett** [comment]
Hi @Gary-Armstrong,

It looks like it might be worth passing [banner_timeout](http://docs.paramiko.org/en/stable/api/client.html#paramiko.client.SSHClient) to [Connection.connect_kwargs](https://docs.fabfile.org/en/2.5/api/connection.html#connect-kwargs-arg) and seeing if that helps.

A quick example (untested):
```python
c = Connection(
    host="hostname",
    user="username",
    connect_kwargs={
        "banner_timeout": 60,
    },
)
```

A couple of people appear to have had a [similar issue](https://stackoverflow.com/questions/41705519/correctly-using-banner-timeout-in-paramiko) to yours before, and adding a reasonable `banner_timeout` appears to have helped. Let me know how you get on!

Cheers,
David

**Comment by theojepsen** [comment]
The solution for me was to increase the number of connection attempts:
```
env.connection_attempts = 5
```
I don't know whether this is a reasonable number of attempts, but it worked!

**Comment by xxtaoqi** [comment]
> 

@davidjmemmett , I have encountered @Gary-Armstrong 's same problem, and the following test can't solve the problem.What is the good solution now?
c = Connection(
    host="hostname",
    user="username",
    connect_kwargs={
        "banner_timeout": 60,
    },
)

**Comment by xxtaoqi** [comment]
> The solution for me was to increase the number of connection attempts:
> 
> ```
> env.connection_attempts = 5
> ```
> 
> I don't know whether this is a reasonable number of attempts, but it worked!

@theojepsen , thanks for your reply. 
what version are you using? and where should `connection_attempts` be set up in fabric2.6?
```
connection_options = {
    'connect_kwargs': {
        "key_filename": "/Users/shansxu/.ssh/id_rsa",
        # "banner_timeout": 60,
        "connection_attempts": 5
    }
}
```
`: SSHClient.connect() got an unexpected keyword argument 'connection_attempts'`
@davidjmemmett        @theojepsen 
I got an error response as set up above. If you know how to solve it, please reply to me. thank you very much.

**Comment by minestick** [comment]
I am having the same issue/error. Iterating over a loop of ips and trying to grab system information. Interestingly, the command returns data but throws the same exception

```
Exception (client): Error reading SSH protocol banner
Traceback (most recent call last):
  File "venv\lib\site-packages\paramiko\transport.py", line 2271, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "venv\lib\site-packages\paramiko\packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "venv\lib\site-packages\paramiko\packet.py", line 609, in _read_timeout
    raise EOFError()
EOFError

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "venv\lib\site-packages\paramiko\transport.py", line 2094, in run
    self._check_banner()
  File "venv\lib\site-packages\paramiko\transport.py", line 2275, in _check_banner
    raise SSHException(
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
```

Here is a very stripped down version that causes the same issue (attempted some of the suggestions above):

```python
ips = ["192.168.1.10", "192.168.1.11", "192.168.1.12", "192.168.1.13"]

for ip in ips:
    test = Connection(host=f"deploy-qa@{ip}", port=22,
              connect_kwargs={"password": "qatest", "timeout": 5, "banner_timeout": 60, })
    try:
        test.open()

        try:
            test.run("hostname")
        except:
            print(f"Unable to run command for {ip}")

    except:
        print(f"Unable to open session for {ip}")
```

It also seems to only have problems with two specific hosts but ssh -vvv indicates no differences when connecting to them for testing.

**Comment by npfoss** [comment]
In case this helps anyone: you can create a `fabric.yml` with a bunch of config settings including `banner_timeout`, and put it in the dir you're calling `fab` from, e.g.
```yml
connect_kwargs:
    banner_timeout: 60
```

and you can confirm that the settings are being used by adding this in your imports to turn on paramiko debug logging:
```py
import logging
logging.basicConfig(level=logging.DEBUG)
```
