### ISSUE TITLE
AuthenticationException when trying to access multiple servers

### ISSUE THREAD

**Issue by JanssensKobe** [fabric/fabric#2163]
I'm trying to run a single command on multiple servers, my server provider is [vultr](https://www.vultr.com/). But I get a AuthenticationException.

Code:
```python
from fabric.connection import Connection
from fabric.group import SerialGroup

config = {'host1': {'password': 'pw1'}, 'host2': {'password': 'pw2'}}

connections = []
for hostname, parameters in config.items():
    conn = Connection(host=hostname, connect_kwargs=parameters)
    connections.append(conn)

with SerialGroup.from_connections(connections) as group:
    result = group.run('uname -a')

for conn, conn_result in result.items():
    print(conn, conn_result)
```

Error:
```
Traceback (most recent call last):
  File "/run/media/kobej/D/trabro2/test/testFabric.py", line 23, in <module>
    result = group.run('uname -a')
  File "/home/kobej/.local/lib/python3.9/site-packages/fabric/group.py", line 119, in run
    return self._do("run", *args, **kwargs)
  File "/home/kobej/.local/lib/python3.9/site-packages/fabric/group.py", line 225, in _do
    raise GroupException(results)
fabric.exceptions.GroupException: {<Connection host=198.13.47.107>: AuthenticationException('Authentication failed.'), <Connection host=45.76.101.214>: AuthenticationException('Authentication failed.'), <Connection host=139.180.199.182>: AuthenticationException('Authentication failed.'), <Connection host=167.179.92.178>: AuthenticationException('Authentication failed.')}
```

System:
- Linux (Manjaro KDE)
- Python 3.9
- fabric version 2.6.0

**Comment by jbreitman** [comment]
Were you able to resolve this issue?
