### ISSUE TITLE
paramiko.ssh_exception.PasswordRequiredException: private key file is encrypted

### ISSUE THREAD

**Issue by ndrake** [fabric/fabric#2184]
**Due diligence**
Similar issue: #2077

**Describe the bug**

Whenever I try to connect to run a command with Fabric on a remote machine, it's erroring with private key file is encrypted.  Using --prompt-for-passphrase doesn't help.

**To Reproduce**

My test script:

```
from fabric import Connection, task

@task
def print_dir(c):
    con = Connection('192.168.1.41', user='ndrake')
    con.run('dir')
```
Run it like: `fab print-dir`

This results in this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/fab", line 8, in <module>
    sys.exit(program.run())
  File "/usr/local/lib/python3.9/site-packages/invoke/program.py", line 384, in run
    self.execute()
  File "/usr/local/lib/python3.9/site-packages/invoke/program.py", line 566, in execute
    executor.execute(*self.tasks)
  File "/usr/local/lib/python3.9/site-packages/invoke/executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "/usr/local/lib/python3.9/site-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/Users/ndrake/src/webapp/fabfile.py", line 6, in print_dir
    con.run('dir')
  File "<decorator-gen-3>", line 2, in run
  File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 29, in opens
    self.open()
  File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 636, in open
    self.client.connect(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/paramiko/client.py", line 435, in connect
    self._auth(
  File "/usr/local/lib/python3.9/site-packages/paramiko/client.py", line 764, in _auth
    raise saved_exception
  File "/usr/local/lib/python3.9/site-packages/paramiko/client.py", line 734, in _auth
    key = self._key_from_filepath(
  File "/usr/local/lib/python3.9/site-packages/paramiko/client.py", line 586, in _key_from_filepath
    key = klass.from_private_key_file(key_path, password)
  File "/usr/local/lib/python3.9/site-packages/paramiko/pkey.py", line 235, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/usr/local/lib/python3.9/site-packages/paramiko/rsakey.py", line 55, in __init__
    self._from_private_key_file(filename, password)
  File "/usr/local/lib/python3.9/site-packages/paramiko/rsakey.py", line 175, in _from_private_key_file
    data = self._read_private_key_file("RSA", filename, password)
  File "/usr/local/lib/python3.9/site-packages/paramiko/pkey.py", line 308, in _read_private_key_file
    data = self._read_private_key(tag, f, password)
  File "/usr/local/lib/python3.9/site-packages/paramiko/pkey.py", line 337, in _read_private_key
    data = self._read_private_key_openssh(lines[start:end], password)
  File "/usr/local/lib/python3.9/site-packages/paramiko/pkey.py", line 438, in _read_private_key_openssh
    raise PasswordRequiredException(
paramiko.ssh_exception.PasswordRequiredException: private key file is encrypted
```
Note: this happens when connecting to both Windows and Linux remote hosts.

**Expected behaviour**

It connects and runs the specified command

**Environment**

Client Env:

* Mac OS 11.6.1
* Python 3.9.6
* Fabric 2.6.0
* Paramiko 2.8.0
* Invoke 1.6.0
* RSA SSH Key

Remote Env:
* Windows 10
* Linux

**Additional context**

Running `ssh 192.168.1.41 "dir"` connects using my key without issue.

**Comment by davidjmemmett** [comment]
Hi,

I'm assuming you're running into [a known paramiko issue](https://github.com/paramiko/paramiko/issues/387) where it throws this exception when it reaches a certain point (because it might not know what failed).

It might be something daft like the wrong username etc.

**Comment by ndrake** [comment]
🤷‍♂️ Maybe?  I switched from Fabric to gradle-ssh-plugin, so I guess I'll close this ticket. Thanks!
