### ISSUE TITLE
 `c.sudo("cd /tmp")` gives "'sudo: cd: command not found '" on debian with bash

### ISSUE THREAD

**Issue by SamuelMarks** [fabric/fabric#2218]
**Due diligence**
Ok

**Describe the bug**
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "offscale/offregister/offregister/drivers/OffFabric.py", line 58, in sudo
    res = super(Connection, self).sudo(command, **kwargs)
  File "<decorator-gen-4>", line 2, in sudo
  File "venv-3-10/lib/python3.10/site-packages/fabric/connection.py", line 30, in opens
    return method(self, *args, **kwargs)
  File "venv-3-10/lib/python3.10/site-packages/fabric/connection.py", line 739, in sudo
    return self._sudo(self._remote_runner(), command, **kwargs)
  File "venv-3-10/lib/python3.10/site-packages/invoke/context.py", line 219, in _sudo
    return runner.run(cmd_str, watchers=watchers, **kwargs)
  File "venv-3-10/lib/python3.10/site-packages/fabric/runners.py", line 72, in run
    return super(Remote, self).run(command, **kwargs)
  File "venv-3-10/lib/python3.10/site-packages/invoke/runners.py", line 380, in run
    return self._run_body(command, **kwargs)
  File "venv-3-10/lib/python3.10/site-packages/invoke/runners.py", line 442, in _run_body
    return self.make_promise() if self._asynchronous else self._finish()
  File "venv-3-10/lib/python3.10/site-packages/invoke/runners.py", line 509, in _finish
    raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!
```

**To Reproduce**

```py
with c.cd("/tmp"):
  c.sudo("true")
```

**Expected behaviour**
Should work without error

**Environment**
- What version of the Python interpreter are you using? Are you using an
alternative interpreter such as PyPy?
Python (CPython) 3.10.5
- What operating system are you using both client & server-side?
macOS 12.4 (21F79) on my machine, machine SSHing into is Debian GNU/Linux 11
- Are you using OpenSSH server or something else?
OpenSSH_8.4p1 Debian-5+deb11u1, OpenSSL 1.1.1n  15 Mar 2022
- Which version or versions of the software are you using?
fabric 2.7.0

**Additional context**

**Comment by SamuelMarks** [comment]
Actually it's this bug: https://github.com/pyinvoke/invoke/issues/687
