### ISSUE TITLE
"OSError: Failure" when transferring a file from Linux to Windows

### ISSUE THREAD

**Issue by JackelynOliveira** [fabric/fabric#2230]
Related issue: #1860 

**Describe the bug**
I'm unable to transfer a file from a Linux host to a Windows host when specifying full remote path.

**To Reproduce**
As stated on my comment to issue #1860, I was having `OSError: Failure` error whenever I tried to transfer a file as below:
```
conn.put("/folder/filename.extension", "c:/users/myuser/filename.extension")
```
These are the logs:
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/root/.local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/root/.local/lib/python3.10/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/root/.local/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/root/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/root/.local/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/root/.local/lib/python3.10/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/root/.local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/root/.local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/root/.local/lib/python3.10/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/root/.local/lib/python3.10/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/root/.local/lib/python3.10/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/root/.local/lib/python3.10/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/root/.local/lib/python3.10/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/workspace/./app/routers/vdis.py", line 15, in create_vdi
    return vdis.add_vdi(db, vdi)
  File "/workspace/./app/services/vdis.py", line 50, in add_vdi
    vdis.set_up(vdi, vdi_conn, entry)
  File "/workspace/./app/services/vpn/vdis.py", line 50, in set_up
    vdi_certificate_name = _generate_certificate(vdi, vdi_conn)
  File "/workspace/./app/services/vpn/vdis.py", line 37, in _generate_certificate
    vdi_conn.put(cert_path, a)
  File "/root/.local/lib/python3.10/site-packages/fabric/connection.py", line 870, in put
    return Transfer(self).put(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/fabric/transfer.py", line 311, in put
    self.sftp.put(localpath=local, remotepath=remote)
  File "/root/.local/lib/python3.10/site-packages/paramiko/sftp_client.py", line 759, in put
    return self.putfo(fl, remotepath, file_size, callback, confirm)
  File "/root/.local/lib/python3.10/site-packages/paramiko/sftp_client.py", line 714, in putfo
    with self.file(remotepath, "wb") as fr:
  File "/root/.local/lib/python3.10/site-packages/paramiko/sftp_client.py", line 372, in open
    t, msg = self._request(CMD_OPEN, filename, imode, attrblock)
  File "/root/.local/lib/python3.10/site-packages/paramiko/sftp_client.py", line 822, in _request
    return self._read_response(num)
  File "/root/.local/lib/python3.10/site-packages/paramiko/sftp_client.py", line 874, in _read_response
    self._convert_status(msg)
  File "/root/.local/lib/python3.10/site-packages/paramiko/sftp_client.py", line 907, in _convert_status
    raise IOError(text)
OSError: Failure
```
After enabling debug logging level, I found this:
```
DEBUG:fabric:Massaged relative remote path 'c:/users/myuser/filename.extension' into '/C:/Users/myuser/c:/users/myuser/filename.extension'
 ```
 After changing the copy command to omit the remote path, the issue was gone.
 ```
 conn.put("/folder/filename.extension")
 ```

**Expected behaviour**
File to be successfully transferred without having to omit remote path.

**Environment**
- Python version: `3.10.6`
- Fabric version: `2.7.0`
- Using Fabric on an Ubuntu host to transfer a file to a Windows remote host.

**Comment by elainajones** [comment]
I reproduced the behavior reported by @JackelynOliveira in the following environments. It looks like at one point this would have raised a generic `OSError: Failure` but now seems to raise `FileNotFoundError`.

## Environment 1 (reported versions)
- Python 3.10.20
- Fabric 2.7.0
- Paramiko 3.5.1
- Invoke 1.7.3
- Client: Gentoo Linux version 2.18
- Remote: Windows 11 version 21H2 (OS Build 22000.1281)
```
>>> conn.put('/tmp/tmp.vElYmNHtN2/filename.extension', 'C:/Users/dev/filename.extension')
DEBUG:paramiko.transport.sftp:[chan 0] stat(b'C:/Users/dev/filename.extension')
DEBUG:paramiko.transport.sftp:[chan 0] normalize(b'.')
DEBUG:fabric:Massaged relative remote path 'C:/Users/dev/filename.extension' into '/C:/Users/dev/C:/Users/dev/filename.extension'
DEBUG:fabric:Uploading '/tmp/tmp.vElYmNHtN2/filename.extension' to '/C:/Users/dev/C:/Users/dev/filename.extension'
DEBUG:paramiko.transport.sftp:[chan 0] open(b'/C:/Users/dev/C:/Users/dev/filename.extension', 'wb')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/tmp.vElYmNHtN2/.venv/lib/python3.10/site-packages/fabric/connection.py", line 870, in put
    return Transfer(self).put(*args, **kwargs)
  File "/tmp/tmp.vElYmNHtN2/.venv/lib/python3.10/site-packages/fabric/transfer.py", line 311, in put
    self.sftp.put(localpath=local, remotepath=remote)
  File "/tmp/tmp.vElYmNHtN2/.venv/lib/python3.10/site-packages/paramiko/sftp_client.py", line 759, in put
    return self.putfo(fl, remotepath, file_size, callback, confirm)
  File "/tmp/tmp.vElYmNHtN2/.venv/lib/python3.10/site-packages/paramiko/sftp_client.py", line 714, in putfo
    with self.file(remotepath, "wb") as fr:
  File "/tmp/tmp.vElYmNHtN2/.venv/lib/python3.10/site-packages/paramiko/sftp_client.py", line 372, in open
    t, msg = self._request(CMD_OPEN, filename, imode, attrblock)
  File "/tmp/tmp.vElYmNHtN2/.venv/lib/python3.10/site-packages/paramiko/sftp_client.py", line 857, in _request
    return self._read_response(num)
  File "/tmp/tmp.vElYmNHtN2/.venv/lib/python3.10/site-packages/paramiko/sftp_client.py", line 909, in _read_response
    self._convert_status(msg)
  File "/tmp/tmp.vElYmNHtN2/.venv/lib/python3.10/site-packages/paramiko/sftp_client.py", line 938, in _convert_status
    raise IOError(errno.ENOENT, text)
FileNotFoundError: [Errno 2] No such file
```

## Environment 2 (latest version)
- Python 3.13.14
- Fabric 3.2.3
- Paramiko 5.0.0
- Invoke 2.2.1
- Client: Gentoo Linux version 2.18
- Remote: Windows 11 version 21H2 (OS Build 22000.1281)
```
>>> conn.put('/tmp/tmp.vElYmNHtN2/filename.extension', 'C:/Users/dev/filename.extension')
DEBUG:paramiko.transport.sftp:[chan 0] stat(b'C:/Users/dev/filename.extension')
DEBUG:paramiko.transport.sftp:[chan 0] normalize(b'.')
DEBUG:fabric:Massaged relative remote path 'C:/Users/dev/filename.extension' into '/C:/Users/dev/C:/Users/dev/filename.extension'
DEBUG:fabric:Uploading '/tmp/tmp.vElYmNHtN2/filename.extension' to '/C:/Users/dev/C:/Users/dev/filename.extension'
DEBUG:paramiko.transport.sftp:[chan 0] open(b'/C:/Users/dev/C:/Users/dev/filename.extension', 'wb')
Traceback (most recent call last):
  File "<python-input-8>", line 1, in <module>
    conn.put('/tmp/tmp.vElYmNHtN2/filename.extension', 'C:/Users/dev/filename.extension')
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp.vElYmNHtN2/.venv/lib/python3.13/site-packages/fabric/connection.py", line 908, in put
    return Transfer(self).put(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/tmp/tmp.vElYmNHtN2/.venv/lib/python3.13/site-packages/fabric/transfer.py", line 308, in put
    self.sftp.put(localpath=local, remotepath=remote)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp.vElYmNHtN2/.venv/lib/python3.13/site-packages/paramiko/sftp_client.py", line 759, in put
    return self.putfo(fl, remotepath, file_size, callback, confirm)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp.vElYmNHtN2/.venv/lib/python3.13/site-packages/paramiko/sftp_client.py", line 714, in putfo
    with self.file(remotepath, "wb") as fr:
         ~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp.vElYmNHtN2/.venv/lib/python3.13/site-packages/paramiko/sftp_client.py", line 372, in open
    t, msg = self._request(CMD_OPEN, filename, imode, attrblock)
             ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp.vElYmNHtN2/.venv/lib/python3.13/site-packages/paramiko/sftp_client.py", line 857, in _request
    return self._read_response(num)
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/tmp/tmp.vElYmNHtN2/.venv/lib/python3.13/site-packages/paramiko/sftp_client.py", line 909, in _read_response
    self._convert_status(msg)
    ~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/tmp/tmp.vElYmNHtN2/.venv/lib/python3.13/site-packages/paramiko/sftp_client.py", line 938, in _convert_status
    raise IOError(errno.ENOENT, text)
FileNotFoundError: [Errno 2] No such file
```

This smells like issue #2335 and seems to be resolved by the same fix from #2333
```
>>> conn.put('/tmp/tmp.vElYmNHtN2/filename.extension', 'C:/Users/dev/filename.extension')
DEBUG:paramiko.transport.sftp:[chan 0] stat(b'C:/Users/dev/filename.extension')
DEBUG:paramiko.transport.sftp:[chan 0] normalize(b'.')
DEBUG:paramiko.transport.sftp:[chan 0] normalize(b'C:/Users/dev/filename.extension')
DEBUG:fabric:Massaged relative remote path 'C:/Users/dev/filename.extension' into '/C:/Users/dev/filename.extension'
DEBUG:fabric:Uploading '/tmp/tmp.vElYmNHtN2/filename.extension' to '/C:/Users/dev/filename.extension'
DEBUG:paramiko.transport.sftp:[chan 0] open(b'/C:/Users/dev/filename.extension', 'wb')
DEBUG:paramiko.transport.sftp:[chan 0] open(b'/C:/Users/dev/filename.extension', 'wb') -> 00000000
DEBUG:paramiko.transport.sftp:[chan 0] close(00000000)
DEBUG:paramiko.transport.sftp:[chan 0] stat(b'/C:/Users/dev/filename.extension')
DEBUG:paramiko.transport.sftp:[chan 0] chmod(b'/C:/Users/dev/filename.extension', 420)
<fabric.transfer.Result object at 0x7f9be6462d50>
```

Adding for context in case it helps!
