### ISSUE TITLE
AttributeError when running with Python 3.11

### ISSUE THREAD

**Issue by Uninen** [fabric/fabric#2231]
**Describe the bug**

Running `fab` with Python 3.11.0 results in following stacktrace:

```
Traceback (most recent call last):
  File "/proj/venv311/bin/fab", line 8, in <module>
    sys.exit(program.run())
             ^^^^^^^^^^^^^
  File "/proj/venv311/lib/python3.11/site-packages/invoke/program.py", line 373, in run
    self.parse_collection()
  File "/proj/venv311/lib/python3.11/site-packages/invoke/program.py", line 465, in parse_collection
    self.load_collection()
  File "/proj/venv311/lib/python3.11/site-packages/fabric/main.py", line 87, in load_collection
    super(Fab, self).load_collection()
  File "/proj/venv311/lib/python3.11/site-packages/invoke/program.py", line 699, in load_collection
    module, parent = loader.load(coll_name)
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/proj/venv311/lib/python3.11/site-packages/invoke/loader.py", line 76, in load
    module = imp.load_module(name, fd, path, desc)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uninen/.pyenv/versions/3.11.0/lib/python3.11/imp.py", line 235, in load_module
    return load_source(name, filename, file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uninen/.pyenv/versions/3.11.0/lib/python3.11/imp.py", line 172, in load_source
    module = _load(spec)
             ^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 721, in _load
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/proj/fabfile.py", line 13, in <module>
    @task(hosts=[HOST])
     ^^^^^^^^^^^^^^^^^^
  File "/proj/venv311/lib/python3.11/site-packages/invoke/tasks.py", line 357, in inner
    obj = klass(
          ^^^^^^
  File "/proj/venv311/lib/python3.11/site-packages/fabric/tasks.py", line 21, in __init__
    super(Task, self).__init__(*args, **kwargs)
  File "/proj/venv311/lib/python3.11/site-packages/invoke/tasks.py", line 76, in __init__
    self.positional = self.fill_implicit_positionals(positional)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/proj/venv311/lib/python3.11/site-packages/invoke/tasks.py", line 167, in fill_implicit_positionals
    args, spec_dict = self.argspec(self.body)
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/proj/venv311/lib/python3.11/site-packages/invoke/tasks.py", line 153, in argspec
    spec = inspect.getargspec(func)
           ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?
```

**To Reproduce**

1. run `fab`

**Expected behaviour**

Get output from Fabric without crashing.

**Environment**

- macOS 12.6.1 (x64)
- Python 3.11.0
- fabric==2.7.1

**Additional context**

Running w/ 3.10 works normally, breaks when running w/ 3.11.0.

**Comment by exslim** [comment]
`getargspec` was removed in 3.11

https://docs.python.org/3/whatsnew/3.11.html#:~:text=Removed%20from%20the%20inspect%20module

The issue is in 3rd-party package `invoke`, see https://github.com/pyinvoke/invoke/issues/833

**Comment by davidjmemmett** [comment]
Looks like this was resolved upstream
