### ISSUE TITLE
AttributeError 'inspect.getargspec' on Python 3.11

### ISSUE THREAD

**Issue by jaraco** [fabric/fabric#2235]
Simply declaring a fabric.task on Python 3.11 crashes with an AttributeError:

```
$ py -3.11 -m pip-run fabric -- -c 'from fabric import task; task(lambda c: None)'
Collecting fabric
  Using cached fabric-2.7.1-py2.py3-none-any.whl (53 kB)
Collecting invoke<2.0,>=1.3
  Using cached invoke-1.7.3-py3-none-any.whl (216 kB)
Collecting paramiko>=2.4
  Using cached paramiko-2.12.0-py2.py3-none-any.whl (213 kB)
Collecting pathlib2
  Using cached pathlib2-2.3.7.post1-py2.py3-none-any.whl (18 kB)
Collecting bcrypt>=3.1.3
  Using cached bcrypt-4.0.1-cp36-abi3-macosx_10_10_universal2.whl (473 kB)
Collecting cryptography>=2.5
  Using cached cryptography-38.0.4-cp36-abi3-macosx_10_10_universal2.whl (5.4 MB)
Collecting pynacl>=1.0.1
  Using cached PyNaCl-1.5.0-cp36-abi3-macosx_10_10_universal2.whl (349 kB)
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting cffi>=1.12
  Using cached cffi-1.15.1-cp311-cp311-macosx_11_0_arm64.whl (174 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Installing collected packages: invoke, six, pycparser, bcrypt, pathlib2, cffi, pynacl, cryptography, paramiko, fabric
Successfully installed bcrypt-4.0.1 cffi-1.15.1 cryptography-38.0.4 fabric-2.7.1 invoke-1.7.3 paramiko-2.12.0 pathlib2-2.3.7.post1 pycparser-2.21 pynacl-1.5.0 six-1.16.0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/var/folders/sx/n5gkrgfx6zd91ymxr2sr9wvw00n8zm/T/pip-run-88oqhs31/fabric/tasks.py", line 71, in task
    return invoke.task(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/folders/sx/n5gkrgfx6zd91ymxr2sr9wvw00n8zm/T/pip-run-88oqhs31/invoke/tasks.py", line 331, in task
    return klass(args[0], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/folders/sx/n5gkrgfx6zd91ymxr2sr9wvw00n8zm/T/pip-run-88oqhs31/fabric/tasks.py", line 21, in __init__
    super(Task, self).__init__(*args, **kwargs)
  File "/var/folders/sx/n5gkrgfx6zd91ymxr2sr9wvw00n8zm/T/pip-run-88oqhs31/invoke/tasks.py", line 76, in __init__
    self.positional = self.fill_implicit_positionals(positional)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/folders/sx/n5gkrgfx6zd91ymxr2sr9wvw00n8zm/T/pip-run-88oqhs31/invoke/tasks.py", line 167, in fill_implicit_positionals
    args, spec_dict = self.argspec(self.body)
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/folders/sx/n5gkrgfx6zd91ymxr2sr9wvw00n8zm/T/pip-run-88oqhs31/invoke/tasks.py", line 153, in argspec
    spec = inspect.getargspec(func)
           ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?
```

The issue may or may not have been fixed in invoke, but if so, it's broken on the released versions of invoke required by fabric.

**Comment by jaraco** [comment]
Looks like it's been a reported issue for some time (https://github.com/pyinvoke/invoke/issues/891, https://github.com/pyinvoke/invoke/issues/833).

**Comment by davidjmemmett** [comment]
As this is an issue in `invoke` rather than `fabric` & issues already exist in the `invoke` project, I'll close this issue.
