### ISSUE TITLE
Unable to run fabric from inside of a docker container

### ISSUE THREAD

**Issue by lbalusek** [fabric/fabric#2257]
Hello, when i try to run fabric from inside of a docker container it fails on `OSError: Socket is closed`

Dockerfile:
```Dockerfile
FROM python:3.11

RUN pip install fabric

WORKDIR /src
COPY ./test.py .

CMD python test.py
```

test.py:
```python
from fabric import Connection, Config

hostname = "***"
user = "***"
pwd = "***"

con = Connection(
    hostname,
    user=user,
    connect_kwargs={"password": pwd},
    config=Config(overrides={"sudo": {"password": pwd}}),
)

con.sudo("docker image ls")
```

```
[sudo] password:
sudo: no password was provided
Traceback (most recent call last):
  File "/src/test.py", line 14, in <module>
    con.sudo(f"docker image ls")
  File "<decorator-gen-4>", line 2, in sudo
  File "/usr/local/lib/python3.11/site-packages/fabric/connection.py", line 27, in opens
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fabric/connection.py", line 753, in sudo
    return self._sudo(self._remote_runner(), command, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/invoke/context.py", line 215, in _sudo
    return runner.run(cmd_str, watchers=watchers, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fabric/runners.py", line 75, in run
    return super().run(command, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/invoke/runners.py", line 376, in run
    return self._run_body(command, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/invoke/runners.py", line 432, in _run_body
    return self.make_promise() if self._asynchronous else self._finish()
                                                          ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/invoke/runners.py", line 484, in _finish
    raise ThreadException(thread_exceptions)
invoke.exceptions.ThreadException:
Saw 1 exceptions within threads (OSError):


Thread args: {'kwargs': {'buffer_': ['[sudo] password: \nsudo: no password was provided\n'],
            'hide': False,
            'output': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>},
 'target': <bound method Runner.handle_stderr of <fabric.runners.Remote object at 0x7f6bb8d786d0>>}

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/invoke/util.py", line 203, in run
    super().run()

  File "/usr/local/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)

  File "/usr/local/lib/python3.11/site-packages/invoke/runners.py", line 758, in handle_stderr
    self._handle_output(

  File "/usr/local/lib/python3.11/site-packages/invoke/runners.py", line 726, in _handle_output
    self.respond(buffer_)

  File "/usr/local/lib/python3.11/site-packages/invoke/runners.py", line 902, in respond
    self.write_proc_stdin(response)

  File "/usr/local/lib/python3.11/site-packages/invoke/runners.py", line 978, in write_proc_stdin
    self._write_proc_stdin(data.encode(self.encoding))

  File "/usr/local/lib/python3.11/site-packages/fabric/runners.py", line 84, in _write_proc_stdin
    return self.channel.sendall(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/paramiko/channel.py", line 844, in sendall
    sent = self.send(s)
           ^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/paramiko/channel.py", line 799, in send
    return self._send(s, m)
           ^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/paramiko/channel.py", line 1196, in _send
    raise socket.error("Socket is closed")

OSError: Socket is closed
```

I am on Windows, docker runs on WSL2.

Any ideas what i am doing wrong? Thanks!

**Comment by davidjmemmett** [comment]
This could be a plethora of issues, relating to Docker's networking, bad configuration etc. Can you connect using the same details via OpenSSH?

**Comment by lbalusek** [comment]
Yes i can, it also works with paramiko.

```python
ssh = paramiko.client.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect(args.hostname, username=args.user, password=args.pwd)
```

**Comment by vvxhid** [comment]
Hello @lbalusek , I was wondering if there's been any progress on this issue ?

**Comment by rtolsma** [comment]
+1 @lbalusek @vvxhid If either of you found any workarounds

I'm hitting this only when operating in a prod dockerized context

**Comment by lbalusek** [comment]
Hello, sorry for the late response, unfortunately i haven't found any workaround and i have moved away from fabric to paramiko.

**Comment by vvxhid** [comment]
Hello, i migrated to asyncssh too.

**Comment by a-musing-moose** [comment]
Just to raise that I too have hit the same issue. 

Running the task directly in a normal shell works just fine. But this is a task that is normally called as part of a CI deployment step. I am using bitbucket pipelines which run inside docker containers. The connection itself appears to work fine but the first use of sudo on that connection fails with `sudo: no password was provided`

```python
config = fabric.Config(overrides={"sudo": {"password": host_pass}})
conn = fabric.Connection(
    host=HOST, user=host_user, connect_kwargs={"password": host_pass}, config=config
)

# Creating necessary folders
conn.sudo("mkdir -p /opt/transfer/jobs")
```

I have verified that all the variables used are set correctly.

**Comment by aluchuk4c** [comment]
I'm running into the same issue here just running from GitHub Actions, not inside docker but rather from a self-hosted runner.
After the Action completes I run the same code and it will work. 
My config:
```
config = Config(
        overrides={
            'port': ssh_port,
            'user': ssh_user,
            'connect_kwargs': {
                'password': ssh_pass
                },
            'sudo': {
                'password': ssh_pass
                },
            'load_ssh_configs': False,
            'inline_ssh_env': True,
            'debug': True
            }
        )
    try:
        ssh = Connection(
            host=ip,
            config=config
            )
```
then the sudo (all I want is docker status):
```
resp = ssh.sudo('docker ps', hide=False)
```

the difference in output looks like this:

Actions |  Manual
---|---
[chan 0] Max packet out: 32768 bytes <br>Secsh channel 0 opened.<br>[chan 0] Sesch channel 0 request ok<br>[chan 0] EOF sent (0)<br>[chan 0] EOF received (0)<br>[sudo] password: <br>Encountered exception OSError('Socket is closed') in thread for 'handle_stderr' | [chan 0] Max packet out: 32768 bytes<br>Secsh channel 0 opened.<br>[chan 0] Sesch channel 0 request ok<br>[sudo] password: [chan 0] EOF received (0)<br>[chan 0] EOF sent (0)

**Comment by andrew8325** [comment]
Make sure you enable the pseudo-TTY in docker when start the container.
For me, it fix by add `-t` in `docker exec` command.
Make this
`docker exec container_name run.py`
to this
`docker exec -t container_name run.py`
