### ISSUE TITLE
Using a ThreadingGroup via a ssh-gateway leads to "Oops, unhandled type 3 ('unimplemented')"

### ISSUE THREAD

**Issue by neerwright** [fabric/fabric#2262]
**Due diligence**
Please try searching the issue tracker for your problem if you haven't already!
If you find related issues that aren't an exact match, feel free to continue
making a report, and link to those issues.

**Describe the bug**
First, I try to connect to my gateway, if I then use a ThreadingGroup instead of a SerialGroup, the run command will only work  for one host, the rest will raise an AuthenticationException('Authentication timeout.'). The problem can be solved by running a random command on the gateway connection before using the gateway for the ThreadingGroup.

**This works fine:**
gatewayConnection = Connect(...)

group =  _SerialGroup_('192.168.1.1', '192.168.1.2', '192.168.1.3', user=user_name,
                gateway=gatewayConnection,
                connect_kwargs={"key_filename": private_key_path, "look_for_keys" : False , "allow_agent" : False})
group.run("hostname")

**and This works also:**
gatewayConnection = Connect(...)
result = _gatewayConnection.run('ping 192.168.1.1 -c 1')_
        
group = _ThreadingGroup_('192.168.1.1', '192.168.1.2', '192.168.1.3', user=testbed_user_name,
                gateway=gatewayConnection,
                connect_kwargs={"key_filename": private_key_path, "look_for_keys" : False , "allow_agent" : False})
        
group.run("hostname")

**To Reproduce**
**without the random command on the gateway, the ThreadingGroup does not work properly:**
gatewayConnection = Connect(...)
        
group = _ThreadingGroup_('192.168.1.1', '192.168.1.2', '192.168.1.3', user=testbed_user_name,
                gateway=gatewayConnection,
                connect_kwargs={"key_filename": private_key_path, "look_for_keys" : False , "allow_agent" : False})
        
group.run("hostname")

**Expected behaviour**
The 3 given hosts in the group will execute the command, but only one will do it properly the rest raises an exception

**Environment**
Make sure your report gets the attention it deserves: bug reports with missing
information may be ignored or punted back to you, delaying a fix. The below
constitutes a bare minimum; more info is almost always better:

- Python 3.10.1
- Client Windows, gateway + servers on Linux
- OpenSSH
- fabric 3.0.0, paramiko 3.1.0

**Additional context**
**The paramiko debug report:**

DEBUG:paramiko.transport:=== Key exchange possibilities ===
DEBUG:paramiko.transport:kex algos: curve25519-sha256, curve25519-sha256@libssh.org, ecdh-sha2-nistp256, ecdh-sha2-nistp384, ecdh-sha2-nistp521, diffie-hellman-group-exchange-sha256, diffie-hellman-group16-sha512, diffie-hellman-group18-sha512, diffie-hellman-group14-sha256
DEBUG:paramiko.transport:server key: rsa-sha2-512, rsa-sha2-256, ssh-rsa
DEBUG:paramiko.transport:client encrypt: chacha20-poly1305@openssh.com, aes128-ctr, aes192-ctr, aes256-ctr, aes128-gcm@openssh.com, aes256-gcm@openssh.com        
DEBUG:paramiko.transport:server encrypt: chacha20-poly1305@openssh.com, aes128-ctr, aes192-ctr, aes256-ctr, aes128-gcm@openssh.com, aes256-gcm@openssh.com        
DEBUG:paramiko.transport:client mac: umac-64-etm@openssh.com, umac-128-etm@openssh.com, hmac-sha2-256-etm@openssh.com, hmac-sha2-512-etm@openssh.com, hmac-sha1-etm@openssh.com, umac-64@openssh.com, umac-128@openssh.com, hmac-sha2-256, hmac-sha2-512, hmac-sha1
DEBUG:paramiko.transport:server mac: umac-64-etm@openssh.com, umac-128-etm@openssh.com, hmac-sha2-256-etm@openssh.com, hmac-sha2-512-etm@openssh.com, hmac-sha1-etm@openssh.com, umac-64@openssh.com, umac-128@openssh.com, hmac-sha2-256, hmac-sha2-512, hmac-sha1
DEBUG:paramiko.transport:client compress: none, zlib@openssh.com
DEBUG:paramiko.transport:server compress: none, zlib@openssh.com
DEBUG:paramiko.transport:client lang: <none>
DEBUG:paramiko.transport:server lang: <none>
DEBUG:paramiko.transport:kex follows: False

DEBUG:paramiko.transport:=== Key exchange agreements ===
DEBUG:paramiko.transport:Kex: curve25519-sha256@libssh.org
DEBUG:paramiko.transport:HostKey: rsa-sha2-512
DEBUG:paramiko.transport:Cipher: aes128-ctr
DEBUG:paramiko.transport:MAC: hmac-sha2-256
DEBUG:paramiko.transport:Compression: none
DEBUG:paramiko.transport:=== End of kex handshake ===
DEBUG:paramiko.transport:kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Got EXT_INFO: {'server-sig-algs': b'ssh-ed25519,sk-ssh-ed25519@openssh.com,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com'}
DEBUG:paramiko.transport:Adding ssh-rsa host key for 192.168.1.1: b'e1637f9a691bfaaaa8325bd3278eeca9'

DEBUG:paramiko.transport:Trying SSH key b'd6b19edcbaeb739760619c6520feae86'
DEBUG:paramiko.transport:userauth is OK
DEBUG:paramiko.transport:Finalizing pubkey algorithm for key of type 'ssh-rsa'
DEBUG:paramiko.transport:Our pubkey algorithm list: ['rsa-sha2-512', 'rsa-sha2-256', 'ssh-rsa']
DEBUG:paramiko.transport:Server-side algorithm list: ['ssh-ed25519', 'sk-ssh-ed25519@openssh.com', 'ssh-rsa', 'rsa-sha2-256', 'rsa-sha2-512', 'ssh-dss', 'ecdsa-sha2-nistp256', 'ecdsa-sha2-nistp384', 'ecdsa-sha2-nistp521', 'sk-ecdsa-sha2-nistp256@openssh.com']
DEBUG:paramiko.transport:Agreed upon 'rsa-sha2-512' pubkey algorithm
INFO:paramiko.transport:Authentication (publickey) successful!

DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:Received global request "hostkeys-00@openssh.com"
DEBUG:paramiko.transport:Rejecting "hostkeys-00@openssh.com" global request from server.
DEBUG:paramiko.transport:Debug msg: b'/home/plattner/.ssh/authorized_keys:1: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding'
DEBUG:paramiko.transport:[chan 0] Max packet out: 32768 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok

Linux

DEBUG:paramiko.transport:[chan 0] EOF received (0)
DEBUG:paramiko.transport:[chan 0] EOF sent (0)

DEBUG:paramiko.transport:Trying discovered key b'd6b19edcbaeb739760619c6520feae86' in C:\Users\NeerW/.ssh/id_rsa
WARNING:paramiko.transport:Oops, unhandled type 3 ('unimplemented')

Traceback (most recent call last):
  File "m:\BachelorArbeit\bsc_plattner_ip_testbed_status\testbed_status_app\dashboard\connection_manager.py", line 101, in <module>
    group = conM.open_connections({"PC1": "192.168.1.1","PC2": "192.168.1.2", "PC3":"192.168.1.3"})
  File "m:\BachelorArbeit\bsc_plattner_ip_testbed_status\testbed_status_app\dashboard\connection_manager.py", line 78, in open_connections
    group.run('uname -s')
  File "M:\BachelorArbeit\bsc_plattner_ip_testbed_status\venv\lib\site-packages\fabric\group.py", line 116, in run
    return self._do("run", *args, **kwargs)
  File "M:\BachelorArbeit\bsc_plattner_ip_testbed_status\venv\lib\site-packages\fabric\group.py", line 282, in _do
    raise GroupException(results)
fabric.exceptions.GroupException: {<Connection host=192.168.1.1 user=plattner gw=proxyjump>: <Result cmd='uname -s' exited=0>, <Connection host=192.168.1.2 user=plattner gw=proxyjump>: AuthenticationException('Authentication timeout.')}

DEBUG:paramiko.transport:EOF in transport thread
DEBUG:paramiko.transport:EOF in transport thread
DEBUG:paramiko.transport:[chan 0] EOF sent (0)
DEBUG:paramiko.transport:Dropping user packet because connection is dead.
DEBUG:paramiko.transport:EOF in transport thread
DEBUG:paramiko.transport:Dropping user packet because connection is dead.

**Comment by senshi-x** [comment]
Can confirm this exact issue still exists as well as the described workaround (running any  single cmd on gateway beforehand).

Python 3.12.0
Client Windows, gateway + servers on Linux
OpenSSH
fabric 3.2.2, paramiko 3.4.0
