### ISSUE TITLE
ModuleNotFoundError: no module named 'connexion.decorators.validation'

### ISSUE THREAD

**Issue by WKirejew** [fabric/fabric#2288]
**Due diligence**
  [Not exactly the same, but i guess related](https://github.com/spec-first/connexion/issues/1340)

**Describe the bug**
I dont undrerstand what it is, but while trying to create new user in apache-airflow the log (shown below) says there is no module, despite I installled newest versions of everything

**To Reproduce**
Steps to reproduce the behaviour (please attach a minimal example):
1. Create ne subsystem Linux for Windows -ubuntu
2. Install python and apache-airflow (by pip, firstly updating the version of ubuntu)
3.  Launch airflow_env and initialize airflow db in a folder /home/<username>/airflow
4.  Try creating new airflow user

**Expected behaviour**
Create an user

**Environment**

I am trying to prepare airflow env in newly installed ubuntu in windows, have newest python: 3.10.12

**Additional context**
**Logs:**
(airflow_env) commodus@DESKTOP-81TELTV:~$ airflow users create -u admin -p legolas112 -f wojtek -l kirejew -r Admin -e wojtasss99@gmail.com
Traceback (most recent call last):
  File "/home/commodus/airflow_env/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/commodus/airflow_env/lib/python3.10/site-packages/airflow/__main__.py", line 59, in main
    args.func(args)
  File "/home/commodus/airflow_env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/commodus/airflow_env/lib/python3.10/site-packages/airflow/utils/cli.py", line 111, in wrapper
    check_and_run_migrations()
  File "/home/commodus/airflow_env/lib/python3.10/site-packages/airflow/utils/db.py", line 829, in check_and_run_migrations
    source_heads = set(env.script.get_heads())
  File "/home/commodus/airflow_env/lib/python3.10/site-packages/alembic/script/base.py", line 407, in get_heads
    return list(self.revision_map.heads)
  File "/home/commodus/airflow_env/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 1113, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/commodus/airflow_env/lib/python3.10/site-packages/alembic/script/revision.py", line 143, in heads
    self._revision_map
  File "/home/commodus/airflow_env/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 1113, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/commodus/airflow_env/lib/python3.10/site-packages/alembic/script/revision.py", line 197, in _revision_map
    for revision in self._generator():
  File "/home/commodus/airflow_env/lib/python3.10/site-packages/alembic/script/base.py", line 149, in _load_revisions
    script = Script._from_filename(self, dir_name, filename)
  File "/home/commodus/airflow_env/lib/python3.10/site-packages/alembic/script/base.py", line 1035, in _from_filename
    module = util.load_python_file(dir_, filename)
  File "/home/commodus/airflow_env/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/commodus/airflow_env/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 109, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/commodus/airflow_env/lib/python3.10/site-packages/airflow/migrations/versions/0074_2_0_0_resource_based_permissions.py", line 30, in <module>
    from airflow.www.app import cached_app
  File "/home/commodus/airflow_env/lib/python3.10/site-packages/airflow/www/app.py", line 50, in <module>
    from airflow.www.extensions.init_views import (
  File "/home/commodus/airflow_env/lib/python3.10/site-packages/airflow/www/extensions/init_views.py", line 27, in <module>
    from connexion.decorators.validation import RequestBodyValidator
ModuleNotFoundError: No module named 'connexion.decorators.validation'

**Comment by davidjmemmett** [comment]
This doesn't appear to be anything to do with Fabric, please find the correct project to report this issue.
