### ISSUE TITLE
TimeoutError when running trivial fab command to disconnected host

### ISSUE THREAD

**Issue by kikoreis** [fabric/fabric#2313]
I'm using fab to connect to a number of machines in a lab, some of which may be offline. I'm on Ubuntu 24.04 LTS and as such python 3.12, but I've installed fabric and paramiko locally via pip3. I have a trivial fabfile set up with a task named 'uname' that runs 'uname -a'. 

When I run 

   fab  -t 1 -H <online-host> uname

I get the expected `Linux [...] GNU/Linux` output.

However, when I run

   fab -t 1 -H <offline-host> uname 

I get a traceback:

```
Traceback (most recent call last):
  File "/home/kiko/.local/bin/fab", line 8, in <module>
    sys.exit(program.run())
             ^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/invoke/program.py", line 380, in run
    self.execute()
  File "/usr/lib/python3/dist-packages/invoke/program.py", line 565, in execute
    executor.execute(*self.tasks)
  File "/usr/lib/python3/dist-packages/invoke/executor.py", line 127, in execute
    result = call.task(*args, **call.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/invoke/tasks.py", line 115, in __call__
    result = self.body(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kiko/devel/bambu-lab-sync/fabfile.py", line 5, in uname
    c.run("uname -a")
  File "/usr/lib/python3/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kiko/.local/lib/python3.12/site-packages/fabric/connection.py", line 22, in opens
    self.open()
  File "/home/kiko/.local/lib/python3.12/site-packages/fabric/connection.py", line 665, in open
    result = self.client.connect(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kiko/.local/lib/python3.12/site-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: [Errno 110] Connection timed out
```

I was expecting fabric to catch this and handle it; ISTR this is how my half-a-decade-old experience of using fabric worked. But looking at main.py and connection.py I can't figure out what code would actually catch this exception, so perhaps this is intentional?

**Comment by davidjmemmett** [comment]
Hi @kikoreis, I believe this is intentional. In order to catch the `TimeoutError` you would need to use `fabric` as a library rather than using the `fab` CLI helper.

Does this help?

Cheers,
David

**Comment by kikoreis** [comment]
I think that it makes fab a lot less useful, since transient network failures to some subset of hosts can (in normal operation) happen regularly. Wouldn't a command-line option, allowing us to ignore a host when the connection fails, address this without a lot of complexity?
