### ISSUE TITLE
Config: Cannot use SSHConfig object (fails in invoke Config)

### ISSUE THREAD

**Issue by jenisys** [fabric/fabric#2321]
**Describe the bug**

I cannot pass an `SSHConfig` object to `fabric.config.Config` class.
When I do that, the `Config` constructor calls its super-class ctor from `invoke` which fails because `SSHConfig` object is not dict-like.

**To Reproduce**

```python
#!/usr/bin/env python3
# -- FILE: explore_fabric.py
import os.path
import sys
from fabric import Connection
from fabric.config import Config, SSHConfig
# from paramiko.config import SSHConfig

HOME = os.path.expanduser("~")

def explore_fabric_ssh_config_syndrome():
    hostname = "localhost"
    ssh_config_file = f"{HOME}/.ssh/config"
    ssh_config = SSHConfig.from_path(ssh_config_file)
    config = Config(ssh_config)
    c = Connection(hostname, config=config)
    result = c.run("whoami")
    print(f"command.result: {result}")

if __name__ == '__main__':
    sys.exit(explore_fabric_ssh_config_syndrome())
```

If I run the file:

```bash
Traceback (most recent call last):
  File "/xxx/./explore_fabric.py", line 75, in <module>
    sys.exit(explore_fabric_ssh_config_syndrome())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/xxx/./explore_fabric.py", line 46, in explore_fabric_ssh_config_syndrome
    config = Config(ssh_config)
             ^^^^^^^^^^^^^^^^^^
  File "/xxx/.direnv/python-3.12/lib/python3.12/site-packages/fabric/config.py", line 159, in __init__
    super().__init__(*args, **kwargs)
  File "/xxx/.direnv/python-3.12/lib/python3.12/site-packages/invoke/config.py", line 655, in __init__
    self.merge()
  File "/xxx/.direnv/python-3.12/lib/python3.12/site-packages/invoke/config.py", line 960, in merge
    merge_dicts(self._config, self._overrides)
  File "/xxx/.direnv/python-3.12/lib/python3.12/site-packages/invoke/config.py", line 1193, in merge_dicts
    for key, value in (updates or {}).items():
                      ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SSHConfig' object has no attribute 'items'
```

**Expected behaviour**

The documentation states that an `SSHConfig` object can be passed to the `Config.__init__()` method as first argument.

* https://docs.fabfile.org/en/latest/api/config.html

**Environment**

- Python 3.12 (cpython)
- OS: macOS (client-side; server-side: not-relevant)

```bash
$ fab -V
Fabric 3.2.2
Paramiko 3.5.0
Invoke 2.2.0
```

**Comment by davidjmemmett** [comment]
Hi @jenisys,

As per the documentation, `ssh_config` is a kwarg, rather than a positional argument. Please try `Config(ssh_config=ssh_config)` instead.
Cheers.
