### ISSUE TITLE
run() after reboot() fails

### ISSUE THREAD

**Issue by bitprophet** [fabric/fabric#329]
### Description

Even after waiting long enough for the box to come up, the next command after reboot fails like:

```
[somehost.example.com] Waiting for reboot: ........................done.
[somehost.example.com] run: rm thatfile.txt
Traceback (most recent call last):
File "/Users/brainsik/.virtualenvs/sauce/lib/python2.7/site-packages/fabric/main.py", line 546, in main
commands[name](*args, **kwargs)
File "/Users/brainsik/src/sauce/admin/fabfile.py", line 571, in pre_install_node
run("rm pre-install-node.sh")
File "/Users/brainsik/.virtualenvs/sauce/lib/python2.7/site-packages/fabric/network.py", line 303, in host_prompting_wrapper
return func(*args, **kwargs)
File "/Users/brainsik/.virtualenvs/sauce/lib/python2.7/site-packages/fabric/operations.py", line 918, in run
return _run_command(command, shell, pty, combine_stderr)
File "/Users/brainsik/.virtualenvs/sauce/lib/python2.7/site-packages/fabric/operations.py", line 841, in _run_command
stdout, stderr, status = _execute(default_channel(), wrapped_command, pty,
File "/Users/brainsik/.virtualenvs/sauce/lib/python2.7/site-packages/fabric/state.py", line 274, in default_channel
return connections[env.host_string].get_transport().open_session()
AttributeError: 'NoneType' object has no attribute 'open_session'
Disconnecting from somehost.example.com... done.
```

---

Originally submitted by **jeremy avnet / @brainsik** ([brainsik](https://github.com/brainsik)) on **2011-03-28** at **04:49pm EDT**

---

Closed as _Done_ on **2011-06-23** at **09:19pm EDT**

**Comment by mungayree** [comment]
I am trying the below on latest fabric and it fails, the systems are super slow and take 500 seconds for ssh to come up.

      @task
      def rebootandwait():
            reboot(wait=500)
            run('date')
