### ISSUE TITLE
paramiko.SSHException: Channel closed. when pty disabled in authorized_keys

### ISSUE THREAD

**Issue by bitprophet** [fabric/fabric#358]
### Description

As a security measure some of our fab operate on servers with no-pty option set in the authorized_keys file. As from 1.0.x on run/sudo commands pty=True which causes a Traceback on our scripts. It might be good to handle the traceback and offer some help to the user:

```
$ fab hosts
[bcfg2-dev.ilrt.bris.ac.uk] run: /usr/sbin/bcfg2-admin query g=basic
Traceback (most recent call last):
File "/usr/lib/pymodules/python2.6/fabric/main.py", line 551, in main
commands[name](*args, **kwargs)
File "/usr/local/projects/cfgman/var/lib/bcfg2/cmxmb/tags/PROD_STABLE/fabfile.py", line 174, in hosts
out = run('/usr/sbin/bcfg2-admin query %s' % gargs)
File "/usr/lib/pymodules/python2.6/fabric/network.py", line 303, in host_prompting_wrapper
return func(*args, **kwargs)
File "/usr/lib/pymodules/python2.6/fabric/operations.py", line 918, in run
return _run_command(command, shell, pty, combine_stderr)
File "/usr/lib/pymodules/python2.6/fabric/operations.py", line 842, in _run_command
combine_stderr)
File "/usr/lib/pymodules/python2.6/fabric/operations.py", line 728, in _execute
channel.get_pty(width=cols, height=rows)
File "/usr/lib/pymodules/python2.6/paramiko/channel.py", line 158, in get_pty
self._wait_for_event()
File "/usr/lib/pymodules/python2.6/paramiko/channel.py", line 1084, in _wait_for_event
raise e
paramiko.SSHException: Channel closed.
Disconnecting from bcfg2-dev.ilrt.bris.ac.uk... done.
```

Attaching a quick patch suggestion of how this could be handled.

---

Originally submitted by **Matt Baker** (never147) on **2011-06-02** at **01:25pm EDT**
### Attachments
- [operations.py.patch](https://gist.github.com/99ecb078874ccf82a020)

**Comment by nhooey** [comment]
Is anyone going to fix this?
