### ISSUE TITLE
put() doesn't like FreeBSD as a target

### ISSUE THREAD

**Issue by shaftoe** [fabric/fabric#422]
I'm running Fabric 1.2.0 with both Debian-like and FreeBSD 8.2-RELEASE as target systems with no problems so far, now that I updated a fabfile to use put(), it throws a paramiko.SSHException only when using FreeBSD as a target:
# [debian target]

$ fab -H leguin send_file:test
[leguin] Executing task 'send_file'
[leguin] put: test -> /tmp/test
[leguin] run: rm /tmp/test

Done.
Disconnecting from leguin... done.
# [FreeBSD target]

$ fab -H freesbee send_file:test
[freesbee] Executing task 'send_file'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Fabric-1.2.0-py2.7.egg/fabric/main.py", line 770, in main
    _run_task(task, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Fabric-1.2.0-py2.7.egg/fabric/main.py", line 628, in _run_task
    return task(_args, *_kwargs)
  File "/tmp/test/fabfile.py", line 5, in send_file
    put(filename, "/tmp/test")
  File "/usr/local/lib/python2.7/dist-packages/Fabric-1.2.0-py2.7.egg/fabric/network.py", line 327, in host_prompting_wrapper
    return func(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Fabric-1.2.0-py2.7.egg/fabric/operations.py", line 393, in put
    ftp = SFTP(env.host_string)
  File "/usr/local/lib/python2.7/dist-packages/Fabric-1.2.0-py2.7.egg/fabric/sftp.py", line 18, in __init__
    self.ftp = connections[host_string].open_sftp()
  File "/usr/lib/pymodules/python2.7/paramiko/client.py", line 390, in open_sftp
    return self._transport.open_sftp_client()
  File "/usr/lib/pymodules/python2.7/paramiko/transport.py", line 833, in open_sftp_client
    return SFTPClient.from_transport(self)
  File "/usr/lib/pymodules/python2.7/paramiko/sftp_client.py", line 106, in from_transport
    return cls(chan)
  File "/usr/lib/pymodules/python2.7/paramiko/sftp_client.py", line 89, in __init__
    raise SSHException('EOF during negotiation')
paramiko.SSHException: EOF during negotiation
Disconnecting from freesbee... done.

**Comment by huwenchao** [comment]
I also got this problem, just for future notice, this is my situation:

1. use `sftp user@host` to see if sftp works. My result is 

    ```
    root@192.168.1.33's password:
    Connection closed 
    ```
2. Use debug file to see what is wrong:

    ```
    $ sftp -v root@192.168.1.33
    ...
    debug1: Exit status 126
    Connection closed
    ```
I googled around and got this: http://serverfault.com/questions/607475/exit-code-126-from-sftp
I checked the auth of sftp file and got:
    ```
    $ ls /usr/libexec/openssh/sftp-server -l
    ----------. 1 root root 63544 11月 23 2013 /usr/libexec/openssh/sftp-server
    ```
Tried to chmod but failed.

3. Then I found this: <http://unix.stackexchange.com/questions/93584/sftp-server-fails-to-start>.
And I changed the ssh_config from 
    ```
    subsystem sftp /usr/libexec/openssh/sftp-server
    ```
to 
    ```
    Subsystem sftp internal-sftp
    ```
and it worked.
