### ISSUE TITLE
Win32: Can't use @parallel: pickle.PicklingError:  it's not found as fabric.tasks.inner

### ISSUE THREAD

**Issue by mishail** [fabric/fabric#489]
Greetings,
First of all thanks a lot for a really great tool.  But I have a problem with parrallel executions.

My setup:
- ActivePython 2.7.2.5 (ActiveState Software Inc.) based on Python 2.7.2 (default, Jun 24 2011, 12:21:10) [MSC v.1500 32 bit (Intel)] on win32
- Fabric 1.3.3 (installed via `pypm install fabric` )
- WinXP

I have a script wich works perfectly with serial executions. But when I add  `@parallel` decorator to one of the tasks, for ex:

``` python
@roles('app', 'db')
@parallel
def checkout_or_update(branch):
    path = podman_sources + branch
    if not exists(path):
        with cd(podman_sources):
            run(checkout_command % {"branch" : branch})
    else:
        with cd(path):
            run('svn up')
```

the I get something like that:

``` shell
$ fab deploy:trunk,staging
[192.168.102.183] Executing task 'checkout_or_update'
[192.168.102.169] Executing task 'checkout_or_update'
[192.168.102.167] Executing task 'checkout_or_update'
Traceback (most recent call last):
  File "C:\Documents and Settings\me\Application Data\Python\Python27\site-packages\fabric\main.py", line 682, in
main
    *args, **kwargs
  File "C:\Documents and Settings\me\Application Data\Python\Python27\site-packages\fabric\tasks.py", line 248, in execute
    task.run(*args, **new_kwargs)
  File "C:\Documents and Settings\me\Application Data\Python\Python27\site-packages\fabric\tasks.py", line 105, in run
    return self.wrapped(*args, **kwargs)
  File "D:\Mishail\My Documents\wspace\app\fabfile.py", line 122, in deploy
    execute(checkout_or_update, branch)
  File "C:\Documents and Settings\me\Application Data\Python\Python27\site-packages\fabric\tasks.py", line 237, in execute
    exitcodes = jobs.run()
  File "C:\Documents and Settings\me\Application Data\Python\Python27\site-packages\fabric\job_queue.py", line 124, in run
    _advance_the_queue()
  File "C:\Documents and Settings\me\Application Data\Python\Python27\site-packages\fabric\job_queue.py", line 114, in _advance_the_queue
    job.start()
  File "D:\Technologies\Python27\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "D:\Technologies\Python27\lib\multiprocessing\forking.py", line 271, in __init__
    dump(process_obj, to_child, HIGHEST_PROTOCOL)
  File "D:\Technologies\Python27\lib\multiprocessing\forking.py", line 193, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "D:\Technologies\Python27\lib\pickle.py", line 224, in dump
    self.save(obj)
  File "D:\Technologies\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "D:\Technologies\Python27\lib\pickle.py", line 419, in save_reduce
    save(state)
  File "D:\Technologies\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "D:\Technologies\Python27\lib\pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "D:\Technologies\Python27\lib\pickle.py", line 681, in _batch_setitems
    save(v)
  File "D:\Technologies\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "D:\Technologies\Python27\lib\pickle.py", line 748, in save_global
    (obj, module, name))
pickle.PicklingError: Can't pickle <function inner at 0x00F73F70>: it's not found as fabric.tasks.inner
$ Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Technologies\Python27\lib\multiprocessing\forking.py", line 374, in main
    self = load(from_parent)
  File "D:\Technologies\Python27\lib\pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "D:\Technologies\Python27\lib\pickle.py", line 858, in load
    dispatch[key](self)
  File "D:\Technologies\Python27\lib\pickle.py", line 880, in load_eof
    raise EOFError
EOFError
```

**Comment by arjunagi** [comment]
@bitprophet , I am using Fabric 1.10 and python 2.7 on Windows 7. When I use the /@parallel decorator, I am getting the above mentioned PicklingError. I was wondering if this issue has been resolved as this ticket has been closed.

**Comment by bitprophet** [comment]
@arjunagi It was closed as "wontfix" (implicitly, github has no status field, sadly), see https://github.com/fabric/fabric/issues/489#issuecomment-4232091

**Comment by fake-name** [comment]
So, seeing as this issue is now *3 years* old, and fabric 2 is *still* not trivially available (not on PyPi, for instance), is the there any chance to revisit this?

**Comment by fake-name** [comment]
I'm not sure why my comment was deleted, but I threw up my workaround to this (which probably basically re-implemented the stuff done by classner) in a branch here: https://github.com/fake-name/fabric/commit/00bd9584a9df6d50490a200ca058fbacf7a8a2e4

Note: I'm not totally sure this is completely safe, it hasn't exploded on me yet. I'm still confused why this ever used `multiprocessing`.

**Comment by jaraco** [comment]
@fake-name: Maybe consider taking the work I did in #974 and contributing it to [mathiasertl/fabric](https://github.com/mathiasertl/fabric), which gets released as [fabric3](https://pypi.org/project/fabric3).

**Comment by fake-name** [comment]
The above branch is already forked off fabric3, since I need python 3 compat. 

Mostly, since I can't see a reason that fabric is using `multiprocessing`, I'm kind of uncomfortable suggesting changes in any branches people use for serious work, since I assume the choice must have a motivation I'm just missing.

**Comment by bitprophet** [comment]
@fake-name Fabric (1) uses multiprocessing because its original design isn't threadsafe - all the state-keeping is in global module state :( so adding parallelism to that design required process boundaries.

v2 has moved the state tracking to explicit objects and is thus much easier to thread or do whatever else with. See pyinvoke/invoke#63 for other ideas around that.

**Comment by fake-name** [comment]
Uh, every time I've added parallelism to a existing codebase, the process has been "make sure things are now thread safe", not "completely duplicate the world". Unless you're worrying about end-user stuff breaking when threaded, there's not a lot of stuff to even have to worry about.

**Comment by ploxiln** [comment]
"make sure things are now thread safe" was done and the result is fabric v2, available now in alpha
