### ISSUE TITLE
Better failure diagnostics needed

### ISSUE THREAD

**Issue by roysmith** [fabric/fabric#672]
I just completed a deployment which took about 15 minutes and produced gazillions of lines of output.  The final lines printed were:

```
Fatal error: One or more hosts failed while executing task 'prep'

Aborting.
```

This isn't very useful.  At the very least, it should tell me which hosts failed so I have some clue where to look for what went wrong.

**Comment by bgard6977** [comment]
+1

**Comment by usmanismail** [comment]
+1 Still need to know which host, the exceptions printing in line is not useful when you run this on 50 hosts

**Comment by haridsv** [comment]
I was bothered by this myself and was experimenting a few days back with the below change:

https://github.com/fabric/fabric/commit/38e00d7e4581391142dfe8d33cc6fc0adf1a4fc1

It seemed to work in the case that I tested, but I have a feeling that it is incomplete. Any comments or feedback?

**Comment by nhooey** [comment]
Is there any plan to print a list of hosts that failed in parallel mode?

**Comment by longquanzheng** [comment]
+1

**Comment by longquanzheng** [comment]
Fatal error: One or more hosts failed while executing task 'run_workload'

Underlying exception:
    'ascii' codec can't encode character u'\ufffd' in position 150: ordinal not in range(128)

Aborting.

**Comment by longquanzheng** [comment]
[ec2-35-161-54-47.us-west-2.compute.amazonaws.com] out: 2016-11-02Traceback (most recent call last):
  File "/local/home/qlong/Ycsb/src/DaxYcsbRunner/test/ycsb/fabfile.py", line 52, in run_workload
    run(cmd)
  File "/opt/brazil-pkg-cache/packages/Fabric/Fabric-1.10.x.14.578/RHEL5_64/DEV.STD.PTHREAD/build/lib/python2.7/site-packages/fabric/network.py", line 647, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/opt/brazil-pkg-cache/packages/Fabric/Fabric-1.10.x.14.578/RHEL5_64/DEV.STD.PTHREAD/build/lib/python2.7/site-packages/fabric/operations.py", line 1048, in run
    shell_escape=shell_escape)
  File "/opt/brazil-pkg-cache/packages/Fabric/Fabric-1.10.x.14.578/RHEL5_64/DEV.STD.PTHREAD/build/lib/python2.7/site-packages/fabric/operations.py", line 917, in _run_command
    stderr=stderr, timeout=timeout)
  File "/opt/brazil-pkg-cache/packages/Fabric/Fabric-1.10.x.14.578/RHEL5_64/DEV.STD.PTHREAD/build/lib/python2.7/site-packages/fabric/operations.py", line 801, in _execute
    worker.raise_if_needed()
  File "/opt/brazil-pkg-cache/packages/Fabric/Fabric-1.10.x.14.578/RHEL5_64/DEV.STD.PTHREAD/build/lib/python2.7/site-packages/fabric/thread_handling.py", line 12, in wrapper
    callable(*args, **kwargs)
  File "/opt/brazil-pkg-cache/packages/Fabric/Fabric-1.10.x.14.578/RHEL5_64/DEV.STD.PTHREAD/build/lib/python2.7/site-packages/fabric/io.py", line 32, in output_loop
    OutputLooper(*args, **kwargs).loop()
  File "/opt/brazil-pkg-cache/packages/Fabric/Fabric-1.10.x.14.578/RHEL5_64/DEV.STD.PTHREAD/build/lib/python2.7/site-packages/fabric/io.py", line 134, in loop
    self._flush("".join(line) + end_of_line + "\n")
  File "/opt/brazil-pkg-cache/packages/Fabric/Fabric-1.10.x.14.578/RHEL5_64/DEV.STD.PTHREAD/build/lib/python2.7/site-packages/fabric/io.py", line 53, in _flush
    self.stream.write(text)
  File "/opt/brazil-pkg-cache/packages/Nose/Nose-1.x.x.5208.8493/RHEL5_64/DEV.STD.PTHREAD/build/lib/python2.7/site-packages/nose/plugins/xunit.py", line 129, in write
    s.write(data)
  File "/opt/brazil-pkg-cache/packages/Nose/Nose-1.x.x.5208.8493/RHEL5_64/DEV.STD.PTHREAD/build/lib/python2.7/site-packages/nose/plugins/xunit.py", line 129, in write
    s.write(data)
  File "/opt/brazil-pkg-cache/packages/Nose/Nose-1.x.x.5208.8493/RHEL5_64/DEV.STD.PTHREAD/build/lib/python2.7/site-packages/nose/plugins/xunit.py", line 129, in write
    s.write(data)
UnicodeEncodeError: 'ascii' codec can't encode character u'\ufffd' in position 151: ordinal not in range(128)

**Comment by DaveHewy** [comment]
I found similar issues. The 2 hosts being operated on, seemingly worked fine. However the line is always outputted.

Fatal error: Needed to prompt for a connection or sudo password (host: 10.86.XX.XX), but input would be ambiguous in parallel mode.

My guess is poor handling of any sudo() cmds during parallel runs?
