### ISSUE TITLE
fabric.contrib.files.exists() fails with an error "'OutputRedirector' object has no attribute 'isatty'" when using with boto

### ISSUE THREAD

**Issue by kowalcj0** [fabric/fabric#916]
Hi,

My current config is python 2.7.3 + virtualenv 1.9.1 with:
* Fabric==1.6.1
* boto==2.9.5

Whenever I'm trying to check whether file exists on remote machine I'm getting errors like the one below:
```python
Traceback (most recent call last):
  File "~/myproject/helpers.py", line 63, in download_audio_files
    if exists('~/%s.wav' % (filename_pattern)):
  File "/home/jay/.virtualenvs/boto/local/lib/python2.7/site-packages/fabric/contrib/files.py", line 36, in exists
    return not func(cmd).failed
  File "/home/jay/.virtualenvs/boto/local/lib/python2.7/site-packages/fabric/network.py", line 535, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/home/jay/.virtualenvs/boto/local/lib/python2.7/site-packages/fabric/operations.py", line 1015, in run
    warn_only=warn_only, stdout=stdout, stderr=stderr, timeout=timeout)
  File "/home/jay/.virtualenvs/boto/local/lib/python2.7/site-packages/fabric/operations.py", line 891, in _run_command
    stderr=stderr, timeout=timeout)
  File "/home/jay/.virtualenvs/boto/local/lib/python2.7/site-packages/fabric/operations.py", line 737, in _execute
    rows, cols = _pty_size()
  File "/home/jay/.virtualenvs/boto/local/lib/python2.7/site-packages/fabric/utils.py", line 253, in _pty_size
    if not win32 and sys.stdout.isatty():
AttributeError: 'OutputRedirector' object has no attribute 'isatty'
```

At the moment I'm using a simple workaround:
```python
with settings(host_string=instance.public_dns_name,
  key_filename=CONN_CONFIG['key_path'],
  user=CONN_CONFIG['user_name'],
  connection_attempts=10):
    if run('~/%s.wav' % (filename_pattern), warn_only=True, pty=False).succeeded:
        get('~/%s.wav' % (filename_pattern), "./")
```

And as the exists() method calls the run() method, could you please add an option to call exists() with all the params allowed when calling run()? (especially pty & warn_only) :)

Thanks

**Comment by toastdriven** [comment]
Boto does **not** replace `sys.stdout` under most circumstances (https://github.com/boto/boto/search?utf8=%E2%9C%93&q=stdout shows all the places `stdout` is referenced). There's no `OutputRedirector` in the Boto either. It would help greatly to have the original code to compare against the workaround.

**Comment by bitprophet** [comment]
Closing for now, can reopen if new details appear. Thanks for the boto checkup @toastdriven !
